In [1]:
import pandas as pd

data_s=pd.read_csv('owid-energy-data.csv')
pd.set_option('display.max_info_columns', 200)

data_s.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23377 entries, 0 to 23376
Data columns (total 130 columns):
 #    Column                                        Non-Null Count  Dtype
---   ------                                        --------------  -----
 0    country                                       23377 non-null  object
 1    year                                          23377 non-null  int64
 2    iso_code                                      17265 non-null  object
 3    population                                    18894 non-null  float64
 4    gdp                                           11780 non-null  float64
 5    biofuel_cons_change_pct                       2070 non-null   float64
 6    biofuel_cons_change_twh                       7903 non-null   float64
 7    biofuel_cons_per_capita                       6338 non-null   float64
 8    biofuel_consumption                           8057 non-null   float64
 9    biofuel_elec_per_capita                       6015 non-null   float64
 10   biofuel_electricity                           6337 non-null   float64
 11   biofuel_share_elec                            6311 non-null   float64
 12   biofuel_share_energy                          6379 non-null   float64
 13   carbon_intensity_elec                         6332 non-null   float64
 14   coal_cons_change_pct                          5827 non-null   float64
 15   coal_cons_change_twh                          6293 non-null   float64
 16   coal_cons_per_capita                          5145 non-null   float64
 17   coal_consumption                              6405 non-null   float64
 18   coal_elec_per_capita                          6486 non-null   float64
 19   coal_electricity                              7168 non-null   float64
 20   coal_prod_change_pct                          9922 non-null   float64
 21   coal_prod_change_twh                          16562 non-null  float64
 22   coal_prod_per_capita                          14808 non-null  float64
 23   coal_production                               16822 non-null  float64
 24   coal_share_elec                               7142 non-null   float64
 25   coal_share_energy                             6379 non-null   float64
 26   electricity_demand                            6378 non-null   float64
 27   electricity_demand_per_capita                 6056 non-null   float64
 28   electricity_generation                        7913 non-null   float64
 29   electricity_share_energy                      4103 non-null   float64
 30   energy_cons_change_pct                        12745 non-null  float64
 31   energy_cons_change_twh                        12978 non-null  float64
 32   energy_per_capita                             11086 non-null  float64
 33   energy_per_gdp                                7882 non-null   float64
 34   fossil_cons_change_pct                        6267 non-null   float64
 35   fossil_cons_change_twh                        6293 non-null   float64
 36   fossil_elec_per_capita                        6526 non-null   float64
 37   fossil_electricity                            7208 non-null   float64
 38   fossil_energy_per_capita                      5145 non-null   float64
 39   fossil_fuel_consumption                       6405 non-null   float64
 40   fossil_share_elec                             7182 non-null   float64
 41   fossil_share_energy                           6379 non-null   float64
 42   gas_cons_change_pct                           5643 non-null   float64
 43   gas_cons_change_twh                           6293 non-null   float64
 44   gas_consumption                               6405 non-null   float64
 45   gas_elec_per_capita                           6343 non-null   float64
 46   gas_electricity                               7025 non-null   float64
 47   gas_energy_per_capita                         5145 non-null   float64
 48   gas_prod_change_pct                           8103 non-null   float64
 49   gas_prod_change_twh                           16990 non-null  float64
 50   gas_prod_per_capita                           15028 non-null  float64
 51   gas_production                                17251 non-null  float64
 52   gas_share_elec                                6999 non-null   float64
 53   gas_share_energy                              6379 non-null   float64
 54   greenhouse_gas_emissions                      6028 non-null   float64
 55   hydro_cons_change_pct                         5686 non-null   float64
 56   hydro_cons_change_twh                         6293 non-null   float64
 57   hydro_consumption                             6405 non-null   float64
 58   hydro_elec_per_capita                         8501 non-null   float64
 59   hydro_electricity                             9603 non-null   float64
 60   hydro_energy_per_capita                       5145 non-null   float64
 61   hydro_share_elec                              7777 non-null   float64
 62   hydro_share_energy                            6379 non-null   float64
 63   low_carbon_cons_change_pct                    5902 non-null   float64
 64   low_carbon_cons_change_twh                    6293 non-null   float64
 65   low_carbon_consumption                        6405 non-null   float64
 66   low_carbon_elec_per_capita                    8596 non-null   float64
 67   low_carbon_electricity                        9698 non-null   float64
 68   low_carbon_energy_per_capita                  5145 non-null   float64
 69   low_carbon_share_elec                         7872 non-null   float64
 70   low_carbon_share_energy                       6379 non-null   float64
 71   net_elec_imports                              6056 non-null   float64
 72   net_elec_imports_share_demand                 6032 non-null   float64
 73   nuclear_cons_change_pct                       2579 non-null   float64
 74   nuclear_cons_change_twh                       7717 non-null   float64
 75   nuclear_consumption                           7859 non-null   float64
 76   nuclear_elec_per_capita                       9090 non-null   float64
 77   nuclear_electricity                           10192 non-null  float64
 78   nuclear_energy_per_capita                     6585 non-null   float64
 79   nuclear_share_elec                            7718 non-null   float64
 80   nuclear_share_energy                          6379 non-null   float64
 81   oil_cons_change_pct                           6267 non-null   float64
 82   oil_cons_change_twh                           6293 non-null   float64
 83   oil_consumption                               6405 non-null   float64
 84   oil_elec_per_capita                           6465 non-null   float64
 85   oil_electricity                               7147 non-null   float64
 86   oil_energy_per_capita                         5145 non-null   float64
 87   oil_prod_change_pct                           10182 non-null  float64
 88   oil_prod_change_twh                           17729 non-null  float64
 89   oil_prod_per_capita                           15574 non-null  float64
 90   oil_production                                17992 non-null  float64
 91   oil_share_elec                                7121 non-null   float64
 92   oil_share_energy                              6379 non-null   float64
 93   other_renewable_consumption                   6405 non-null   float64
 94   other_renewable_electricity                   9670 non-null   float64
 95   other_renewable_exc_biofuel_electricity       5716 non-null   float64
 96   other_renewables_cons_change_pct              3988 non-null   float64
 97   other_renewables_cons_change_twh              6293 non-null   float64
 98   other_renewables_elec_per_capita              8568 non-null   float64
 99   other_renewables_elec_per_capita_exc_biofuel  5394 non-null   float64
 100  other_renewables_energy_per_capita            5145 non-null   float64
 101  other_renewables_share_elec                   7844 non-null   float64
 102  other_renewables_share_elec_exc_biofuel       5690 non-null   float64
 103  other_renewables_share_energy                 6379 non-null   float64
 104  per_capita_electricity                        7071 non-null   float64
 105  primary_energy_consumption                    13255 non-null  float64
 106  renewables_cons_change_pct                    5895 non-null   float64
 107  renewables_cons_change_twh                    6293 non-null   float64
 108  renewables_consumption                        6405 non-null   float64
 109  renewables_elec_per_capita                    8596 non-null   float64
 110  renewables_electricity                        9698 non-null   float64
 111  renewables_energy_per_capita                  5145 non-null   float64
 112  renewables_share_elec                         7872 non-null   float64
 113  renewables_share_energy                       6379 non-null   float64
 114  solar_cons_change_pct                         2515 non-null   float64
 115  solar_cons_change_twh                         6293 non-null   float64
 116  solar_consumption                             6405 non-null   float64
 117  solar_elec_per_capita                         8613 non-null   float64
 118  solar_electricity                             9715 non-null   float64
 119  solar_energy_per_capita                       5145 non-null   float64
 120  solar_share_elec                              7869 non-null   float64
 121  solar_share_energy                            6379 non-null   float64
 122  wind_cons_change_pct                          2798 non-null   float64
 123  wind_cons_change_twh                          6293 non-null   float64
 124  wind_consumption                              6405 non-null   float64
 125  wind_elec_per_capita                          8405 non-null   float64
 126  wind_electricity                              9507 non-null   float64
 127  wind_energy_per_capita                        5145 non-null   float64
 128  wind_share_elec                               7661 non-null   float64
 129  wind_share_energy                             6379 non-null   float64
dtypes: float64(127), int64(1), object(2)
memory usage: 23.2+ MB

In [2]:
# Stage 1 of cleaning database - remove data for continents

country=pd.DataFrame(data_s[data_s["iso_code"].notnull()])
country.head(200)

,country,year,iso_code,population,gdp,biofuel_cons_change_pct,biofuel_cons_change_twh,biofuel_cons_per_capita,biofuel_consumption,biofuel_elec_per_capita,...,solar_share_elec,solar_share_energy,wind_cons_change_pct,wind_cons_change_twh,wind_consumption,wind_elec_per_capita,wind_electricity,wind_energy_per_capita,wind_share_elec,wind_share_energy
26,Afghanistan,1900,AFG,4707744.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,Afghanistan,1901,AFG,4751177.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Afghanistan,1902,AFG,4802500.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Afghanistan,1903,AFG,4861833.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,Afghanistan,1904,AFG,4921891.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
593,Albania,1970,ALB,2181226.0,6.888219e+09,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
594,Albania,1971,ALB,2234995.0,7.337364e+09,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
595,Albania,1972,ALB,2289265.0,7.811525e+09,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
596,Albania,1973,ALB,2344108.0,8.317288e+09,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
597,Albania,1974,ALB,2399397.0,8.539400e+09,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
country["iso_code"].unique()

array(['AFG', 'ALB', 'DZA', 'ASM', 'AGO', 'ATA', 'ATG', 'ARG', 'ARM',
       'ABW', 'AUS', 'AUT', 'AZE', 'BHS', 'BHR', 'BGD', 'BRB', 'BLR',
       'BEL', 'BLZ', 'BEN', 'BMU', 'BTN', 'BOL', 'BIH', 'BWA', 'BRA',
       'VGB', 'BRN', 'BGR', 'BFA', 'BDI', 'KHM', 'CMR', 'CAN', 'CPV',
       'CYM', 'CAF', 'TCD', 'CHL', 'CHN', 'COL', 'COM', 'COG', 'COK',
       'CRI', 'CIV', 'HRV', 'CUB', 'CUW', 'CYP', 'CZE', 'COD', 'DNK',
       'DJI', 'DMA', 'DOM', 'TLS', 'ECU', 'EGY', 'SLV', 'GNQ', 'ERI',
       'EST', 'SWZ', 'ETH', 'FLK', 'FRO', 'FJI', 'FIN', 'FRA', 'GUF',
       'PYF', 'GAB', 'GMB', 'GEO', 'DEU', 'GHA', 'GIB', 'GRC', 'GRL',
       'GRD', 'GLP', 'GUM', 'GTM', 'GIN', 'GNB', 'GUY', 'HTI', 'HND',
       'HKG', 'HUN', 'ISL', 'IND', 'IDN', 'IRN', 'IRQ', 'IRL', 'ISR',
       'ITA', 'JAM', 'JPN', 'JOR', 'KAZ', 'KEN', 'KIR', 'KWT', 'KGZ',
       'LAO', 'LVA', 'LBN', 'LSO', 'LBR', 'LBY', 'LTU', 'LUX', 'MAC',
       'MDG', 'MWI', 'MYS', 'MDV', 'MLI', 'MLT', 'MTQ', 'MRT', 'MUS',
       'MEX', 'FSM', 'MDA', 'MNG', 'MNE', 'MSR', 'MAR', 'MOZ', 'MMR',
       'NAM', 'NRU', 'NPL', 'NLD', 'ANT', 'NCL', 'NZL', 'NIC', 'NER',
       'NGA', 'NIU', 'PRK', 'MKD', 'MNP', 'NOR', 'OMN', 'PAK', 'PSE',
       'PAN', 'PNG', 'PRY', 'PER', 'PHL', 'POL', 'PRT', 'PRI', 'QAT',
       'REU', 'ROU', 'RUS', 'RWA', 'SHN', 'KNA', 'LCA', 'SPM', 'VCT',
       'WSM', 'STP', 'SAU', 'SEN', 'SRB', 'SYC', 'SLE', 'SGP', 'SVK',
       'SVN', 'SLB', 'SOM', 'ZAF', 'KOR', 'SSD', 'ESP', 'LKA', 'SDN',
       'SUR', 'SWE', 'CHE', 'SYR', 'TWN', 'TJK', 'TZA', 'THA', 'TGO',
       'TON', 'TTO', 'TUN', 'TUR', 'TKM', 'TCA', 'TUV', 'UGA', 'UKR',
       'ARE', 'GBR', 'USA', 'VIR', 'URY', 'UZB', 'VUT', 'VEN', 'VNM',
       'ESH', 'YEM', 'ZMB', 'ZWE'], dtype=object)

In [4]:
country['country'].unique()

array(['Afghanistan', 'Albania', 'Algeria', 'American Samoa', 'Angola',
       'Antarctica', 'Antigua and Barbuda', 'Argentina', 'Armenia',
       'Aruba', 'Australia', 'Austria', 'Azerbaijan', 'Bahamas',
       'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium',
       'Belize', 'Benin', 'Bermuda', 'Bhutan', 'Bolivia',
       'Bosnia and Herzegovina', 'Botswana', 'Brazil',
       'British Virgin Islands', 'Brunei', 'Bulgaria', 'Burkina Faso',
       'Burundi', 'Cambodia', 'Cameroon', 'Canada', 'Cape Verde',
       'Cayman Islands', 'Central African Republic', 'Chad', 'Chile',
       'China', 'Colombia', 'Comoros', 'Congo', 'Cook Islands',
       'Costa Rica', "Cote d'Ivoire", 'Croatia', 'Cuba', 'Curacao',
       'Cyprus', 'Czechia', 'Democratic Republic of Congo', 'Denmark',
       'Djibouti', 'Dominica', 'Dominican Republic', 'East Timor',
       'Ecuador', 'Egypt', 'El Salvador', 'Equatorial Guinea', 'Eritrea',
       'Estonia', 'Eswatini', 'Ethiopia', 'Falkland Islands',
       'Faroe Islands', 'Fiji', 'Finland', 'France', 'French Guiana',
       'French Polynesia', 'Gabon', 'Gambia', 'Georgia', 'Germany',
       'Ghana', 'Gibraltar', 'Greece', 'Greenland', 'Grenada',
       'Guadeloupe', 'Guam', 'Guatemala', 'Guinea', 'Guinea-Bissau',
       'Guyana', 'Haiti', 'Honduras', 'Hong Kong', 'Hungary', 'Iceland',
       'India', 'Indonesia', 'Iran', 'Iraq', 'Ireland', 'Israel', 'Italy',
       'Jamaica', 'Japan', 'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati',
       'Kuwait', 'Kyrgyzstan', 'Laos', 'Latvia', 'Lebanon', 'Lesotho',
       'Liberia', 'Libya', 'Lithuania', 'Luxembourg', 'Macao',
       'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta',
       'Martinique', 'Mauritania', 'Mauritius', 'Mexico',
       'Micronesia (country)', 'Moldova', 'Mongolia', 'Montenegro',
       'Montserrat', 'Morocco', 'Mozambique', 'Myanmar', 'Namibia',
       'Nauru', 'Nepal', 'Netherlands', 'Netherlands Antilles',
       'New Caledonia', 'New Zealand', 'Nicaragua', 'Niger', 'Nigeria',
       'Niue', 'North Korea', 'North Macedonia',
       'Northern Mariana Islands', 'Norway', 'Oman', 'Pakistan',
       'Palestine', 'Panama', 'Papua New Guinea', 'Paraguay', 'Peru',
       'Philippines', 'Poland', 'Portugal', 'Puerto Rico', 'Qatar',
       'Reunion', 'Romania', 'Russia', 'Rwanda', 'Saint Helena',
       'Saint Kitts and Nevis', 'Saint Lucia',
       'Saint Pierre and Miquelon', 'Saint Vincent and the Grenadines',
       'Samoa', 'Sao Tome and Principe', 'Saudi Arabia', 'Senegal',
       'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore', 'Slovakia',
       'Slovenia', 'Solomon Islands', 'Somalia', 'South Africa',
       'South Korea', 'South Sudan', 'Spain', 'Sri Lanka', 'Sudan',
       'Suriname', 'Sweden', 'Switzerland', 'Syria', 'Taiwan',
       'Tajikistan', 'Tanzania', 'Thailand', 'Togo', 'Tonga',
       'Trinidad and Tobago', 'Tunisia', 'Turkey', 'Turkmenistan',
       'Turks and Caicos Islands', 'Tuvalu', 'Uganda', 'Ukraine',
       'United Arab Emirates', 'United Kingdom', 'United States',
       'United States Virgin Islands', 'Uruguay', 'Uzbekistan', 'Vanuatu',
       'Venezuela', 'Vietnam', 'Western Sahara', 'Yemen', 'Zambia',
       'Zimbabwe'], dtype=object)

In [5]:
territories_to_exclude = [
    'ATA',  # Antarctica
    'ASM', 'GUM', 'MNP', 'PRI', 'VIR',  # US territories
    'BMU', 'VGB', 'CYM', 'FLK', 'GIB', 'MSR', 'SHN', 'TCA',  # British territories
    'GUF', 'PYF', 'GLP', 'MTQ', 'NCL', 'REU', 'SPM',  # French territories
    'FRO', 'GRL', 'CUW', 'ANT', 'COK', 'NIU',  # Danish/Dutch/NZ territories
    'HKG', 'MAC', 'TWN', 'ESH', 'PSE'  # judgment calls you chose to exclude
]
sovereign_countries =country[~country['iso_code'].isin(territories_to_exclude)]

In [6]:

print(type(sovereign_countries))
print(sovereign_countries.shape)
sovereign_countries.head(100)

<class 'pandas.core.frame.DataFrame'>
(15649, 130)

,country,year,iso_code,population,gdp,biofuel_cons_change_pct,biofuel_cons_change_twh,biofuel_cons_per_capita,biofuel_consumption,biofuel_elec_per_capita,...,solar_share_elec,solar_share_energy,wind_cons_change_pct,wind_cons_change_twh,wind_consumption,wind_elec_per_capita,wind_electricity,wind_energy_per_capita,wind_share_elec,wind_share_energy
26,Afghanistan,1900,AFG,4707744.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,Afghanistan,1901,AFG,4751177.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Afghanistan,1902,AFG,4802500.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Afghanistan,1903,AFG,4861833.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,Afghanistan,1904,AFG,4921891.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121,Afghanistan,1995,AFG,17065837.0,1.230753e+10,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
122,Afghanistan,1996,AFG,17763266.0,1.207013e+10,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
123,Afghanistan,1997,AFG,18452100.0,1.185075e+10,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
124,Afghanistan,1998,AFG,19159996.0,1.169217e+10,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
125,Afghanistan,1999,AFG,19887792.0,1.151732e+10,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
# For every year, how many countries actually have a non-null value for each column.

pd.set_option('display.max_rows', None)
sovereign_countries.groupby('year')[['gdp', 'renewables_share_energy', 'fossil_share_energy']].count()

      gdp  renewables_share_energy  fossil_share_energy
year
1900   36                        0                    0
1901   32                        0                    0
1902   33                        0                    0
1903   33                        0                    0
1904   33                        0                    0
1905   33                        0                    0
1906   34                        0                    0
1907   33                        0                    0
1908   33                        0                    0
1909   33                        0                    0
1910   38                        0                    0
1911   36                        0                    0
1912   34                        0                    0
1913   54                        0                    0
1914   34                        0                    0
1915   34                        0                    0
1916   35                        0                    0
1917   34                        0                    0
1918   34                        0                    0
1919   34                        0                    0
1920   39                        0                    0
1921   39                        0                    0
1922   37                        0                    0
1923   38                        0                    0
1924   40                        0                    0
1925   40                        0                    0
1926   41                        0                    0
1927   40                        0                    0
1928   40                        0                    0
1929   44                        0                    0
1930   42                        0                    0
1931   43                        0                    0
1932   42                        0                    0
1933   42                        0                    0
1934   42                        0                    0
1935   42                        0                    0
1936   43                        0                    0
1937   42                        0                    0
1938   44                        0                    0
1939   40                        0                    0
1940   40                        0                    0
1941   39                        0                    0
1942   38                        0                    0
1943   36                        0                    0
1944   35                        0                    0
1945   35                        0                    0
1946   37                        0                    0
1947   38                        0                    0
1948   40                        0                    0
1949   41                        0                    0
1950   86                        0                    0
1951   86                        0                    0
1952   86                        0                    0
1953   86                        0                    0
1954   86                        0                    0
1955   86                        0                    0
1956   86                        0                    0
1957   86                        0                    0
1958   86                        0                    0
1959   86                        0                    0
1960   86                        0                    0
1961   86                        0                    0
1962   86                        0                    0
1963   86                        0                    0
1964   86                        0                    0
1965   94                       63                   63
1966   94                       63                   63
1967   94                       63                   63
1968   94                       63                   63
1969   94                       63                   63
1970   95                       63                   63
1971   95                       64                   64
1972   95                       64                   64
1973   96                       64                   64
1974   95                       64                   64
1975   95                       64                   64
1976   95                       64                   64
1977   95                       64                   64
1978   95                       64                   64
1979   95                       64                   64
1980  137                       64                   64
1981  137                       64                   64
1982  137                       64                   64
1983  137                       64                   64
1984  137                       64                   64
1985  148                       74                   74
1986  148                       74                   74
1987  148                       74                   74
1988  148                       74                   74
1989  148                       74                   74
1990  154                       77                   77
1991  153                       77                   77
1992  159                       77                   77
1993  160                       77                   77
1994  160                       77                   77
1995  160                       77                   77
1996  160                       77                   77
1997  160                       77                   77
1998  160                       77                   77
1999  160                       77                   77
2000  160                       77                   77
2001  160                       77                   77
2002  160                       77                   77
2003  160                       77                   77
2004  160                       77                   77
2005  161                       77                   77
2006  161                       77                   77
2007  161                       77                   77
2008  161                       77                   77
2009  161                       77                   77
2010  161                       77                   77
2011  161                       77                   77
2012  161                       77                   77
2013  161                       77                   77
2014  161                       77                   77
2015  161                       77                   77
2016  161                       77                   77
2017  161                       77                   77
2018  161                       77                   77
2019  161                       77                   77
2020  161                       77                   77
2021  161                       77                   77
2022  161                       77                   77
2023    0                       77                   77
2024    0                       77                   77
2025    0                        0                    0

In [8]:
# The set of country codes that had non-null renewables data in 1990.
# The second line does the exact same thing, but for year 2010.
# The & operator between two Python sets computes their intersection — the elements present in both sets

countries_1990 = set(sovereign_countries[sovereign_countries.year==1990].dropna(subset=['renewables_share_energy'])['iso_code'])
countries_2010 = set(sovereign_countries[sovereign_countries.year==2010].dropna(subset=['renewables_share_energy'])['iso_code'])
print(len(countries_1990 & countries_2010))  # intersection

77

In [9]:
# Checking the availability of data for the time frame t0=1995, t1=2010, t2=2015

countries_t0 = set(sovereign_countries[sovereign_countries.year==1995].dropna(subset=['renewables_share_energy','fossil_share_energy'])['iso_code'])
countries_t1 = set(sovereign_countries[sovereign_countries.year==2010].dropna(subset=['renewables_share_energy','fossil_share_energy','gdp'])['iso_code'])
countries_t2 = set(sovereign_countries[sovereign_countries.year==2015].dropna(subset=['gdp'])['iso_code'])

survivors = countries_t0 & countries_t1 & countries_t2
print(len(survivors))

77

In [10]:
# Data size after extending the set of features our model will use 

final_features = [
    'renewables_share_energy', 'fossil_share_energy', 
    'coal_share_energy', 'oil_share_energy', 'gas_share_energy',
    'nuclear_share_energy',
    'renewables_share_elec', 'nuclear_share_elec'
]

countries_t0 = set(sovereign_countries[sovereign_countries.year==1995].dropna(subset=final_features)['iso_code'])
countries_t1 = set(sovereign_countries[sovereign_countries.year==2010].dropna(subset=final_features + ['gdp'])['iso_code'])
countries_t2 = set(sovereign_countries[sovereign_countries.year==2015].dropna(subset=['gdp'])['iso_code'])

final_survivors = countries_t0 & countries_t1 & countries_t2
print(len(final_survivors))

77

In [11]:
sub_1995 = sovereign_countries[(sovereign_countries.year==1995) & (sovereign_countries.iso_code.isin(final_survivors))]
print(sub_1995[final_features].eq(0).sum())
print()
print((sub_1995[final_features] < 0.01).sum())  # near-zero, not just exactly 0

renewables_share_energy     6
fossil_share_energy         0
coal_share_energy           7
oil_share_energy            0
gas_share_energy            5
nuclear_share_energy       48
renewables_share_elec       6
nuclear_share_elec         48
dtype: int64

renewables_share_energy     6
fossil_share_energy         0
coal_share_energy           9
oil_share_energy            0
gas_share_energy            5
nuclear_share_energy       48
renewables_share_elec       6
nuclear_share_elec         48
dtype: int64

In [12]:
# Step 1: Creating three slices, each keeping iso_code + the relevant columns,
# renamed with a year suffix so nothing collides when merged

t0_slice = sovereign_countries[
    (sovereign_countries.year == 1995) & 
    (sovereign_countries.iso_code.isin(final_survivors))
][['iso_code'] + final_features].copy()
t0_slice = t0_slice.rename(columns={col: f"{col}_1995" for col in final_features})

t1_slice = sovereign_countries[
    (sovereign_countries.year == 2010) & 
    (sovereign_countries.iso_code.isin(final_survivors))
][['iso_code'] + final_features + ['gdp']].copy()
t1_slice = t1_slice.rename(columns={col: f"{col}_2010" for col in final_features})
t1_slice = t1_slice.rename(columns={'gdp': 'gdp_2010'})

t2_slice = sovereign_countries[
    (sovereign_countries.year == 2015) & 
    (sovereign_countries.iso_code.isin(final_survivors))
][['iso_code', 'gdp']].copy()
t2_slice = t2_slice.rename(columns={'gdp': 'gdp_2015'})

# Step 2: Merging all three into one wide table, one row per country
model_data = t0_slice.merge(t1_slice, on='iso_code', how='inner')
model_data = model_data.merge(t2_slice, on='iso_code', how='inner')

print(model_data.shape)
model_data.head(80)

(77, 19)

,iso_code,renewables_share_energy_1995,fossil_share_energy_1995,coal_share_energy_1995,oil_share_energy_1995,gas_share_energy_1995,nuclear_share_energy_1995,renewables_share_elec_1995,nuclear_share_elec_1995,renewables_share_energy_2010,fossil_share_energy_2010,coal_share_energy_2010,oil_share_energy_2010,gas_share_energy_2010,nuclear_share_energy_2010,renewables_share_elec_2010,nuclear_share_elec_2010,gdp_2010,gdp_2015
0,DZA,0.171,99.829,2.303,32.941,64.585,0.000,0.979,0.000,0.108,99.892,0.821,41.373,57.698,0.000,0.372,0.000,4.507058e+11,5.515217e+11
1,ARG,11.830,85.032,1.185,41.882,41.965,3.138,39.635,10.520,11.092,86.765,1.538,37.183,48.044,2.143,27.595,5.722,7.857852e+11,8.503566e+11
2,AUS,4.002,95.998,42.049,37.152,16.798,0.000,9.408,0.000,4.088,95.912,40.350,34.499,21.063,0.000,8.830,0.000,9.938540e+11,1.139303e+12
3,AUT,30.140,69.860,11.177,37.580,21.102,0.000,70.681,0.000,30.113,69.887,9.496,37.189,23.202,0.000,66.337,0.000,3.388322e+11,3.581083e+11
4,AZE,2.695,97.305,0.022,48.437,48.847,0.000,9.129,0.000,7.021,92.979,0.038,29.131,63.810,0.000,18.265,0.000,1.442966e+11,1.640369e+11
5,BGD,0.965,99.035,3.486,32.561,62.988,0.000,3.443,0.000,0.834,99.166,3.457,18.982,76.727,0.000,2.031,0.000,4.000878e+11,5.521047e+11
6,BLR,0.022,99.978,4.416,49.587,45.975,0.000,0.080,0.000,0.252,99.748,2.452,29.597,67.698,0.000,0.401,0.000,1.662399e+11,1.737098e+11
7,BEL,0.294,82.549,15.373,48.579,18.598,17.157,0.911,56.257,3.125,80.474,5.727,49.258,25.489,16.401,7.061,51.526,4.112617e+11,4.415515e+11
8,BRA,43.373,56.252,7.377,46.074,2.802,0.375,94.157,0.914,42.505,56.281,5.397,42.034,8.849,1.214,84.802,2.815,2.820493e+12,3.021043e+12
9,BGR,2.226,80.096,32.813,27.766,19.518,17.677,5.210,41.441,7.258,73.795,38.193,22.851,12.750,18.948,12.541,33.203,1.090452e+11,1.144986e+11
10,CAN,28.664,63.196,9.236,30.661,23.299,8.140,61.172,17.417,26.567,67.085,7.771,34.516,24.798,6.349,61.063,14.831,1.406355e+12,1.568026e+12
11,CHL,24.921,75.079,12.065,53.912,9.102,0.000,72.404,0.000,18.941,81.059,14.511,50.601,15.947,0.000,40.199,0.000,3.214574e+11,3.862513e+11
12,CHN,5.239,94.415,74.988,17.695,1.733,0.346,19.286,1.274,7.195,92.132,70.336,18.031,3.765,0.673,18.691,1.776,1.285881e+13,1.830122e+13
13,COL,28.416,71.584,13.202,45.339,13.043,0.000,68.374,0.000,27.404,72.596,13.389,38.264,20.943,0.000,70.513,0.000,4.898702e+11,6.127509e+11
14,HRV,18.212,81.788,2.341,53.540,25.907,0.000,61.580,0.000,22.716,77.284,7.443,41.142,28.699,0.000,62.880,0.000,8.130379e+10,8.173111e+10
15,CYP,0.000,100.000,4.932,95.068,0.000,0.000,0.000,0.000,1.095,98.905,0.501,98.405,0.000,0.000,1.501,0.000,2.728556e+10,2.531251e+10
16,CZE,1.445,91.552,56.220,19.624,15.707,7.003,3.978,20.188,3.759,81.984,42.719,20.906,18.358,14.258,6.935,32.856,2.712320e+11,2.982761e+11
17,DNK,2.209,97.791,31.008,51.520,15.263,0.000,5.085,0.000,14.973,85.027,19.406,43.499,22.123,0.000,32.077,0.000,2.381902e+11,2.554013e+11
18,ECU,15.267,84.733,0.004,81.285,3.443,0.000,61.227,0.000,15.137,84.863,0.075,80.760,4.027,0.000,44.130,0.000,1.379133e+11,1.725384e+11
19,EGY,7.134,92.866,1.853,63.187,27.827,0.000,22.096,0.000,4.198,95.802,0.605,46.558,48.640,0.000,9.963,0.000,8.987514e+11,1.079612e+12
20,EST,0.030,99.970,65.161,23.911,10.898,0.000,0.115,0.000,4.380,95.620,64.102,22.561,8.956,0.000,8.096,0.000,2.758697e+10,3.210602e+10
21,FIN,17.208,66.559,20.863,35.757,9.938,16.233,30.547,30.031,19.122,64.696,21.509,31.932,11.255,16.181,29.985,28.274,2.017460e+11,2.027067e+11
22,FRA,7.396,56.073,6.271,37.810,11.992,36.531,15.051,77.079,7.882,54.455,4.662,33.064,16.728,37.663,13.635,76.200,2.342490e+12,2.464954e+12
23,DEU,1.788,87.406,26.606,41.176,19.624,10.806,4.884,28.846,8.465,81.963,23.434,35.500,23.029,9.571,16.887,22.518,3.301123e+12,3.628074e+12
24,GRC,3.131,96.869,29.711,66.996,0.161,0.000,8.696,0.000,7.696,92.304,24.295,57.007,11.002,0.000,18.601,0.000,2.909844e+11,2.423237e+11
25,HUN,0.220,86.154,17.678,31.158,37.318,13.626,0.647,41.240,3.999,81.163,11.318,28.576,41.268,14.838,8.084,42.184,2.004966e+11,2.264746e+11
26,ISL,60.333,39.667,3.201,36.466,0.000,0.000,99.789,0.000,83.047,16.953,1.925,15.028,0.000,0.000,100.000,0.000,1.153145e+10,1.314788e+10
27,IND,7.258,92.025,55.329,30.565,6.130,0.717,18.022,1.783,6.057,92.977,53.804,29.700,9.474,0.966,15.114,2.465,5.361371e+12,7.391522e+12
28,IDN,3.445,96.555,7.255,56.453,32.847,0.000,19.412,0.000,4.417,95.583,24.679,45.601,25.303,0.000,19.503,0.000,2.039335e+12,2.684764e+12
29,IRN,2.188,97.812,1.136,66.510,30.165,0.000,9.867,0.000,1.106,98.894,0.544,39.574,58.776,0.000,4.425,0.000,1.310507e+12,1.331012e+12
30,IRQ,5.564,94.436,0.000,85.962,8.473,0.000,26.869,0.000,2.404,97.596,0.000,79.378,18.219,0.000,9.753,0.000,2.975072e+11,4.360107e+11
31,IRL,1.517,98.483,25.798,52.307,20.378,0.000,4.155,0.000,6.149,93.851,12.998,50.085,30.768,0.000,13.388,0.000,2.218524e+11,2.499559e+11
32,ISR,0.036,99.964,24.599,75.243,0.122,0.000,0.082,0.000,0.222,99.778,33.927,46.729,19.122,0.000,0.290,0.000,2.103276e+11,2.512239e+11
33,ITA,5.386,94.614,6.518,64.072,24.023,0.000,17.466,0.000,10.921,89.079,7.744,42.790,38.545,0.000,25.948,0.000,2.080546e+12,2.025809e+12
34,JPN,4.483,81.966,16.662,54.996,10.308,13.551,9.213,28.380,5.404,81.799,22.738,42.263,16.798,12.797,10.228,25.290,4.480296e+12,4.707025e+12
35,KAZ,3.875,96.088,53.195,23.946,18.948,0.037,12.483,0.119,3.426,96.574,63.667,18.547,14.360,0.000,9.704,0.000,3.333417e+11,4.219771e+11
36,KWT,0.000,100.000,0.000,41.454,58.546,0.000,0.000,0.000,0.000,100.000,0.011,65.483,34.506,0.000,0.000,0.000,1.760370e+11,2.194060e+11
37,LVA,18.407,81.593,7.011,50.687,23.895,0.000,73.684,0.000,19.887,80.113,2.569,42.617,34.927,0.000,54.902,0.000,3.588118e+10,4.377419e+10
38,LTU,1.051,65.643,2.895,38.816,23.932,33.306,2.737,87.426,4.494,95.506,3.644,47.987,43.874,0.000,18.200,0.000,5.607378e+10,6.753966e+10
39,LUX,0.900,99.100,16.942,63.126,19.031,0.000,22.449,0.000,2.428,97.572,1.556,68.227,27.789,0.000,8.333,0.000,2.752670e+10,3.097649e+10
40,MYS,4.343,95.657,4.877,56.745,34.035,0.000,13.351,0.000,2.202,97.798,18.388,38.701,40.709,0.000,6.094,0.000,5.250566e+11,6.852377e+11
41,MEX,6.739,91.627,4.059,66.188,21.380,1.634,22.630,5.615,5.953,93.326,6.982,55.212,31.131,0.722,16.863,2.134,1.638272e+12,1.916009e+12
42,MAR,1.658,98.342,18.557,79.659,0.125,0.000,5.053,0.000,5.532,94.468,16.688,73.981,3.799,0.000,18.775,0.000,2.256438e+11,2.746900e+11
43,NLD,0.442,98.413,10.631,45.915,41.867,1.145,1.767,5.039,3.039,96.077,7.507,48.579,39.991,0.884,9.475,3.362,7.281932e+11,7.610833e+11
44,NZL,40.821,59.179,6.486,31.494,21.199,0.000,83.934,0.000,38.311,61.689,6.890,36.039,18.760,0.000,73.121,0.000,1.394788e+11,1.607822e+11
45,MKD,7.805,92.195,58.326,33.869,0.000,0.000,13.051,0.000,18.923,81.077,44.971,32.794,3.311,0.000,33.471,0.000,2.258313e+10,2.558382e+10
46,NOR,69.429,30.571,2.304,21.939,6.328,0.000,99.656,0.000,64.629,35.371,1.855,25.071,8.444,0.000,95.793,0.000,3.837609e+11,4.307890e+11
47,OMN,0.000,100.000,0.000,47.792,52.208,0.000,0.000,0.000,0.000,100.000,0.145,30.761,69.093,0.000,0.000,0.000,1.351983e+11,1.617701e+11
48,PAK,15.541,84.103,6.322,45.742,32.039,0.356,35.681,0.818,10.436,88.675,8.406,32.770,47.498,0.890,34.715,2.708,8.054915e+11,1.010825e+12
49,PER,27.773,72.227,3.318,65.962,2.946,0.000,77.485,0.000,25.513,74.487,4.264,45.769,24.453,0.000,57.704,0.000,2.303533e+11,2.906427e+11
50,PHL,14.080,85.920,7.379,78.521,0.020,0.000,36.857,0.000,15.667,84.333,23.752,50.342,10.239,0.000,26.296,0.000,5.655148e+11,7.626790e+11
51,POL,0.492,99.508,73.789,16.281,9.438,0.000,1.430,0.000,3.379,96.621,55.407,27.172,14.042,0.000,6.940,0.000,7.956199e+11,9.360438e+11
52,PRT,10.868,89.132,20.089,69.042,0.000,0.000,28.502,0.000,26.402,73.598,6.395,49.887,17.317,0.000,53.010,0.000,2.672774e+11,2.569119e+11
53,QAT,0.000,100.000,0.000,10.518,89.482,0.000,0.000,0.000,0.000,100.000,0.000,24.175,75.825,0.000,0.000,0.000,2.386481e+11,3.612427e+11
54,ROU,8.403,91.597,22.267,28.779,40.551,0.000,28.264,0.000,13.830,78.453,20.877,25.590,31.986,7.716,33.598,19.232,3.354896e+11,3.843065e+11
55,RUS,6.390,90.002,18.114,23.295,48.593,3.607,20.501,11.573,5.597,88.695,13.538,20.640,54.518,5.707,16.090,16.417,3.105249e+12,3.456430e+12
56,SAU,0.000,100.000,0.000,63.909,36.091,0.000,0.000,0.000,0.000,100.000,0.032,65.992,33.975,0.000,0.000,0.000,1.156842e+12,1.591797e+12
57,SGP,0.197,99.803,0.034,96.105,3.664,0.000,1.111,0.000,0.233,99.767,0.011,89.230,10.525,0.000,2.601,0.000,2.975868e+11,3.745874e+11
58,SVK,6.511,78.229,30.410,18.675,29.144,15.260,18.464,43.284,8.314,73.053,21.988,22.480,28.585,18.633,21.668,53.059,1.183443e+11,1.327556e+11
59,SVN,12.293,69.641,21.814,36.127,11.699,18.066,25.194,37.054,15.228,67.530,19.543,36.251,11.737,17.242,29.213,34.809,5.364978e+10,5.441424e+10
60,ZAF,0.132,97.057,74.297,21.604,1.156,2.811,0.283,6.054,0.310,97.282,73.792,20.673,2.818,2.408,0.613,5.212,6.076016e+11,6.959332e+11
61,KOR,0.476,89.040,19.328,64.282,5.430,10.484,1.480,32.930,0.630,86.668,30.073,41.819,14.777,12.702,1.149,30.018,1.562823e+12,1.803764e+12
62,ESP,5.624,81.665,18.203,56.052,7.410,12.711,14.769,33.598,16.490,73.916,4.796,47.479,21.642,9.593,32.831,20.816,1.480376e+12,1.488099e+12
63,LKA,31.403,68.597,0.029,68.567,0.000,0.000,94.036,0.000,21.793,78.206,1.016,77.191,0.000,0.000,53.451,0.000,1.806428e+11,2.449143e+11
64,SWE,30.274,39.844,4.978,33.656,1.209,29.883,47.579,47.161,37.370,37.797,5.134,30.108,2.555,24.833,55.298,38.956,3.998390e+11,4.290374e+11
65,CHE,29.600,49.972,0.659,42.478,6.836,20.428,56.872,39.327,27.969,52.380,0.491,41.935,9.955,19.650,56.730,39.879,4.511397e+11,5.004847e+11
66,THA,3.056,96.944,13.606,66.122,17.216,0.000,8.447,0.000,2.750,97.250,15.233,45.349,36.668,0.000,5.566,0.000,8.701093e+11,1.002012e+12
67,TTO,0.116,99.884,0.000,16.920,82.964,0.000,0.766,0.000,0.005,99.995,0.000,11.180,88.815,0.000,0.000,0.000,4.128543e+10,4.543580e+10
68,TUR,14.165,85.835,27.330,49.262,9.242,0.000,41.570,0.000,11.710,88.290,29.389,30.107,28.793,0.000,26.385,0.000,1.240497e+12,1.727193e+12
69,TKM,0.011,99.989,0.056,27.121,72.813,0.000,0.040,0.000,0.003,99.997,0.000,25.951,74.046,0.000,0.000,0.000,7.111515e+10,9.334615e+10
70,UKR,1.500,87.876,32.169,16.586,39.120,10.625,5.091,36.079,2.464,81.179,31.342,11.396,38.440,16.357,7.091,47.214,4.394298e+11,3.980454e+11
71,ARE,0.000,100.000,0.000,50.151,49.849,0.000,0.000,0.000,0.005,99.995,0.787,38.260,60.948,0.000,0.021,0.000,4.900489e+11,6.747427e+11
72,GBR,0.752,89.543,21.676,38.879,28.988,9.705,1.980,26.365,3.043,90.401,14.375,36.122,39.904,6.556,6.852,16.264,2.190920e+12,2.426436e+12
73,USA,4.551,87.328,23.069,39.595,24.664,8.121,10.602,19.870,5.642,85.799,22.443,38.277,25.079,8.559,10.318,19.616,1.523959e+13,1.693763e+13
74,UZB,3.398,96.602,2.051,15.314,79.237,0.000,13.040,0.000,4.069,95.931,1.761,10.158,84.012,0.000,15.759,0.000,1.951602e+11,2.739836e+11
75,VEN,19.900,80.100,0.008,37.587,42.505,0.000,70.051,0.000,21.151,78.849,0.246,45.477,33.126,0.000,67.493,0.000,4.775917e+11,4.849755e+11
76,VNM,23.467,76.533,28.752,46.659,1.121,0.000,72.242,0.000,13.931,86.069,31.618,37.503,16.948,0.000,31.204,0.000,4.136663e+11,5.558221e+11

In [13]:
# Step 3: Compute absolute change for each energy feature, in a loop
for feature in final_features:
    model_data[f"{feature}_change"] = model_data[f"{feature}_2010"] - model_data[f"{feature}_1995"]

# Step 4: Compute GDP growth (percentage)
model_data['gdp_growth'] = (model_data['gdp_2015'] - model_data['gdp_2010']) / model_data['gdp_2010']

# Step 5: Median split into binary target
model_data['high_growth'] = (model_data['gdp_growth'] > model_data['gdp_growth'].median()).astype(int)

model_data.head()

,iso_code,renewables_share_energy_1995,fossil_share_energy_1995,coal_share_energy_1995,oil_share_energy_1995,gas_share_energy_1995,nuclear_share_energy_1995,renewables_share_elec_1995,nuclear_share_elec_1995,renewables_share_energy_2010,...,renewables_share_energy_change,fossil_share_energy_change,coal_share_energy_change,oil_share_energy_change,gas_share_energy_change,nuclear_share_energy_change,renewables_share_elec_change,nuclear_share_elec_change,gdp_growth,high_growth
0,DZA,0.171,99.829,2.303,32.941,64.585,0.000,0.979,0.00,0.108,...,-0.063,0.063,-1.482,8.432,-6.887,0.000,-0.607,0.000,0.223685,1
1,ARG,11.830,85.032,1.185,41.882,41.965,3.138,39.635,10.52,11.092,...,-0.738,1.733,0.353,-4.699,6.079,-0.995,-12.040,-4.798,0.082174,0
2,AUS,4.002,95.998,42.049,37.152,16.798,0.000,9.408,0.00,4.088,...,0.086,-0.086,-1.699,-2.653,4.265,0.000,-0.578,0.000,0.146349,1
3,AUT,30.140,69.860,11.177,37.580,21.102,0.000,70.681,0.00,30.113,...,-0.027,0.027,-1.681,-0.391,2.100,0.000,-4.344,0.000,0.056890,0
4,AZE,2.695,97.305,0.022,48.437,48.847,0.000,9.129,0.00,7.021,...,4.326,-4.326,0.016,-19.306,14.963,0.000,9.136,0.000,0.136804,0

In [14]:
model_data['high_growth'].value_counts()

high_growth
0    39
1    38
Name: count, dtype: int64

In [15]:
model_data.head(80)

,iso_code,renewables_share_energy_1995,fossil_share_energy_1995,coal_share_energy_1995,oil_share_energy_1995,gas_share_energy_1995,nuclear_share_energy_1995,renewables_share_elec_1995,nuclear_share_elec_1995,renewables_share_energy_2010,...,renewables_share_energy_change,fossil_share_energy_change,coal_share_energy_change,oil_share_energy_change,gas_share_energy_change,nuclear_share_energy_change,renewables_share_elec_change,nuclear_share_elec_change,gdp_growth,high_growth
0,DZA,0.171,99.829,2.303,32.941,64.585,0.000,0.979,0.000,0.108,...,-0.063,0.063,-1.482,8.432,-6.887,0.000,-0.607,0.000,0.223685,1
1,ARG,11.830,85.032,1.185,41.882,41.965,3.138,39.635,10.520,11.092,...,-0.738,1.733,0.353,-4.699,6.079,-0.995,-12.040,-4.798,0.082174,0
2,AUS,4.002,95.998,42.049,37.152,16.798,0.000,9.408,0.000,4.088,...,0.086,-0.086,-1.699,-2.653,4.265,0.000,-0.578,0.000,0.146349,1
3,AUT,30.140,69.860,11.177,37.580,21.102,0.000,70.681,0.000,30.113,...,-0.027,0.027,-1.681,-0.391,2.100,0.000,-4.344,0.000,0.056890,0
4,AZE,2.695,97.305,0.022,48.437,48.847,0.000,9.129,0.000,7.021,...,4.326,-4.326,0.016,-19.306,14.963,0.000,9.136,0.000,0.136804,0
5,BGD,0.965,99.035,3.486,32.561,62.988,0.000,3.443,0.000,0.834,...,-0.131,0.131,-0.029,-13.579,13.739,0.000,-1.412,0.000,0.379959,1
6,BLR,0.022,99.978,4.416,49.587,45.975,0.000,0.080,0.000,0.252,...,0.230,-0.230,-1.964,-19.990,21.723,0.000,0.321,0.000,0.044935,0
7,BEL,0.294,82.549,15.373,48.579,18.598,17.157,0.911,56.257,3.125,...,2.831,-2.075,-9.646,0.679,6.891,-0.756,6.150,-4.731,0.073651,0
8,BRA,43.373,56.252,7.377,46.074,2.802,0.375,94.157,0.914,42.505,...,-0.868,0.029,-1.980,-4.040,6.047,0.839,-9.355,1.901,0.071105,0
9,BGR,2.226,80.096,32.813,27.766,19.518,17.677,5.210,41.441,7.258,...,5.032,-6.301,5.380,-4.915,-6.768,1.271,7.331,-8.238,0.050010,0
10,CAN,28.664,63.196,9.236,30.661,23.299,8.140,61.172,17.417,26.567,...,-2.097,3.889,-1.465,3.855,1.499,-1.791,-0.109,-2.586,0.114957,0
11,CHL,24.921,75.079,12.065,53.912,9.102,0.000,72.404,0.000,18.941,...,-5.980,5.980,2.446,-3.311,6.845,0.000,-32.205,0.000,0.201563,1
12,CHN,5.239,94.415,74.988,17.695,1.733,0.346,19.286,1.274,7.195,...,1.956,-2.283,-4.652,0.336,2.032,0.327,-0.595,0.502,0.423244,1
13,COL,28.416,71.584,13.202,45.339,13.043,0.000,68.374,0.000,27.404,...,-1.012,1.012,0.187,-7.075,7.900,0.000,2.139,0.000,0.250843,1
14,HRV,18.212,81.788,2.341,53.540,25.907,0.000,61.580,0.000,22.716,...,4.504,-4.504,5.102,-12.398,2.792,0.000,1.300,0.000,0.005256,0
15,CYP,0.000,100.000,4.932,95.068,0.000,0.000,0.000,0.000,1.095,...,1.095,-1.095,-4.431,3.337,0.000,0.000,1.501,0.000,-0.072311,0
16,CZE,1.445,91.552,56.220,19.624,15.707,7.003,3.978,20.188,3.759,...,2.314,-9.568,-13.501,1.282,2.651,7.255,2.957,12.668,0.099708,0
17,DNK,2.209,97.791,31.008,51.520,15.263,0.000,5.085,0.000,14.973,...,12.764,-12.764,-11.602,-8.021,6.860,0.000,26.992,0.000,0.072258,0
18,ECU,15.267,84.733,0.004,81.285,3.443,0.000,61.227,0.000,15.137,...,-0.130,0.130,0.071,-0.525,0.584,0.000,-17.097,0.000,0.251065,1
19,EGY,7.134,92.866,1.853,63.187,27.827,0.000,22.096,0.000,4.198,...,-2.936,2.936,-1.248,-16.629,20.813,0.000,-12.133,0.000,0.201235,1
20,EST,0.030,99.970,65.161,23.911,10.898,0.000,0.115,0.000,4.380,...,4.350,-4.350,-1.059,-1.350,-1.942,0.000,7.981,0.000,0.163811,1
21,FIN,17.208,66.559,20.863,35.757,9.938,16.233,30.547,30.031,19.122,...,1.914,-1.863,0.646,-3.825,1.317,-0.052,-0.562,-1.757,0.004762,0
22,FRA,7.396,56.073,6.271,37.810,11.992,36.531,15.051,77.079,7.882,...,0.486,-1.618,-1.609,-4.746,4.736,1.132,-1.416,-0.879,0.052279,0
23,DEU,1.788,87.406,26.606,41.176,19.624,10.806,4.884,28.846,8.465,...,6.677,-5.443,-3.172,-5.676,3.405,-1.235,12.003,-6.328,0.099042,0
24,GRC,3.131,96.869,29.711,66.996,0.161,0.000,8.696,0.000,7.696,...,4.565,-4.565,-5.416,-9.989,10.841,0.000,9.905,0.000,-0.167228,0
25,HUN,0.220,86.154,17.678,31.158,37.318,13.626,0.647,41.240,3.999,...,3.779,-4.991,-6.360,-2.582,3.950,1.212,7.437,0.944,0.129568,0
26,ISL,60.333,39.667,3.201,36.466,0.000,0.000,99.789,0.000,83.047,...,22.714,-22.714,-1.276,-21.438,0.000,0.000,0.211,0.000,0.140176,0
27,IND,7.258,92.025,55.329,30.565,6.130,0.717,18.022,1.783,6.057,...,-1.201,0.952,-1.525,-0.865,3.344,0.249,-2.908,0.682,0.378662,1
28,IDN,3.445,96.555,7.255,56.453,32.847,0.000,19.412,0.000,4.417,...,0.972,-0.972,17.424,-10.852,-7.544,0.000,0.091,0.000,0.316490,1
29,IRN,2.188,97.812,1.136,66.510,30.165,0.000,9.867,0.000,1.106,...,-1.082,1.082,-0.592,-26.936,28.611,0.000,-5.442,0.000,0.015647,0
30,IRQ,5.564,94.436,0.000,85.962,8.473,0.000,26.869,0.000,2.404,...,-3.160,3.160,0.000,-6.584,9.746,0.000,-17.116,0.000,0.465547,1
31,IRL,1.517,98.483,25.798,52.307,20.378,0.000,4.155,0.000,6.149,...,4.632,-4.632,-12.800,-2.222,10.390,0.000,9.233,0.000,0.126676,0
32,ISR,0.036,99.964,24.599,75.243,0.122,0.000,0.082,0.000,0.222,...,0.186,-0.186,9.328,-28.514,19.000,0.000,0.208,0.000,0.194441,1
33,ITA,5.386,94.614,6.518,64.072,24.023,0.000,17.466,0.000,10.921,...,5.535,-5.535,1.226,-21.282,14.522,0.000,8.482,0.000,-0.026309,0
34,JPN,4.483,81.966,16.662,54.996,10.308,13.551,9.213,28.380,5.404,...,0.921,-0.167,6.076,-12.733,6.490,-0.754,1.015,-3.090,0.050606,0
35,KAZ,3.875,96.088,53.195,23.946,18.948,0.037,12.483,0.119,3.426,...,-0.449,0.486,10.472,-5.399,-4.588,-0.037,-2.779,-0.119,0.265899,1
36,KWT,0.000,100.000,0.000,41.454,58.546,0.000,0.000,0.000,0.000,...,0.000,0.000,0.011,24.029,-24.040,0.000,0.000,0.000,0.246364,1
37,LVA,18.407,81.593,7.011,50.687,23.895,0.000,73.684,0.000,19.887,...,1.480,-1.480,-4.442,-8.070,11.032,0.000,-18.782,0.000,0.219976,1
38,LTU,1.051,65.643,2.895,38.816,23.932,33.306,2.737,87.426,4.494,...,3.443,29.863,0.749,9.171,19.942,-33.306,15.463,-87.426,0.204479,1
39,LUX,0.900,99.100,16.942,63.126,19.031,0.000,22.449,0.000,2.428,...,1.528,-1.528,-15.386,5.101,8.758,0.000,-14.116,0.000,0.125325,0
40,MYS,4.343,95.657,4.877,56.745,34.035,0.000,13.351,0.000,2.202,...,-2.141,2.141,13.511,-18.044,6.674,0.000,-7.257,0.000,0.305074,1
41,MEX,6.739,91.627,4.059,66.188,21.380,1.634,22.630,5.615,5.953,...,-0.786,1.699,2.923,-10.976,9.751,-0.912,-5.767,-3.481,0.169531,1
42,MAR,1.658,98.342,18.557,79.659,0.125,0.000,5.053,0.000,5.532,...,3.874,-3.874,-1.869,-5.678,3.674,0.000,13.722,0.000,0.217361,1
43,NLD,0.442,98.413,10.631,45.915,41.867,1.145,1.767,5.039,3.039,...,2.597,-2.336,-3.124,2.664,-1.876,-0.261,7.708,-1.677,0.045167,0
44,NZL,40.821,59.179,6.486,31.494,21.199,0.000,83.934,0.000,38.311,...,-2.510,2.510,0.404,4.545,-2.439,0.000,-10.813,0.000,0.152736,1
45,MKD,7.805,92.195,58.326,33.869,0.000,0.000,13.051,0.000,18.923,...,11.118,-11.118,-13.355,-1.075,3.311,0.000,20.420,0.000,0.132873,0
46,NOR,69.429,30.571,2.304,21.939,6.328,0.000,99.656,0.000,64.629,...,-4.800,4.800,-0.449,3.132,2.116,0.000,-3.863,0.000,0.122545,0
47,OMN,0.000,100.000,0.000,47.792,52.208,0.000,0.000,0.000,0.000,...,0.000,0.000,0.145,-17.031,16.885,0.000,0.000,0.000,0.196539,1
48,PAK,15.541,84.103,6.322,45.742,32.039,0.356,35.681,0.818,10.436,...,-5.105,4.572,2.084,-12.972,15.459,0.534,-0.966,1.890,0.254917,1
49,PER,27.773,72.227,3.318,65.962,2.946,0.000,77.485,0.000,25.513,...,-2.260,2.260,0.946,-20.193,21.507,0.000,-19.781,0.000,0.261726,1
50,PHL,14.080,85.920,7.379,78.521,0.020,0.000,36.857,0.000,15.667,...,1.587,-1.587,16.373,-28.179,10.219,0.000,-10.561,0.000,0.348645,1
51,POL,0.492,99.508,73.789,16.281,9.438,0.000,1.430,0.000,3.379,...,2.887,-2.887,-18.382,10.891,4.604,0.000,5.510,0.000,0.176496,1
52,PRT,10.868,89.132,20.089,69.042,0.000,0.000,28.502,0.000,26.402,...,15.534,-15.534,-13.694,-19.155,17.317,0.000,24.508,0.000,-0.038782,0
53,QAT,0.000,100.000,0.000,10.518,89.482,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,13.657,-13.657,0.000,0.000,0.000,0.513705,1
54,ROU,8.403,91.597,22.267,28.779,40.551,0.000,28.264,0.000,13.830,...,5.427,-13.144,-1.390,-3.189,-8.565,7.716,5.334,19.232,0.145509,1
55,RUS,6.390,90.002,18.114,23.295,48.593,3.607,20.501,11.573,5.597,...,-0.793,-1.307,-4.576,-2.655,5.925,2.100,-4.411,4.844,0.113093,0
56,SAU,0.000,100.000,0.000,63.909,36.091,0.000,0.000,0.000,0.000,...,0.000,0.000,0.032,2.083,-2.116,0.000,0.000,0.000,0.375985,1
57,SGP,0.197,99.803,0.034,96.105,3.664,0.000,1.111,0.000,0.233,...,0.036,-0.036,-0.023,-6.875,6.861,0.000,1.490,0.000,0.258750,1
58,SVK,6.511,78.229,30.410,18.675,29.144,15.260,18.464,43.284,8.314,...,1.803,-5.176,-8.422,3.805,-0.559,3.373,3.204,9.775,0.121774,0
59,SVN,12.293,69.641,21.814,36.127,11.699,18.066,25.194,37.054,15.228,...,2.935,-2.111,-2.271,0.124,0.038,-0.824,4.019,-2.245,0.014249,0
60,ZAF,0.132,97.057,74.297,21.604,1.156,2.811,0.283,6.054,0.310,...,0.178,0.225,-0.505,-0.931,1.662,-0.403,0.330,-0.842,0.145377,0
61,KOR,0.476,89.040,19.328,64.282,5.430,10.484,1.480,32.930,0.630,...,0.154,-2.372,10.745,-22.463,9.347,2.218,-0.331,-2.912,0.154170,1
62,ESP,5.624,81.665,18.203,56.052,7.410,12.711,14.769,33.598,16.490,...,10.866,-7.749,-13.407,-8.573,14.232,-3.118,18.062,-12.782,0.005217,0
63,LKA,31.403,68.597,0.029,68.567,0.000,0.000,94.036,0.000,21.793,...,-9.610,9.609,0.987,8.624,0.000,0.000,-40.585,0.000,0.355793,1
64,SWE,30.274,39.844,4.978,33.656,1.209,29.883,47.579,47.161,37.370,...,7.096,-2.047,0.156,-3.548,1.346,-5.050,7.719,-8.205,0.073026,0
65,CHE,29.600,49.972,0.659,42.478,6.836,20.428,56.872,39.327,27.969,...,-1.631,2.408,-0.168,-0.543,3.119,-0.778,-0.142,0.552,0.109378,0
66,THA,3.056,96.944,13.606,66.122,17.216,0.000,8.447,0.000,2.750,...,-0.306,0.306,1.627,-20.773,19.452,0.000,-2.881,0.000,0.151593,1
67,TTO,0.116,99.884,0.000,16.920,82.964,0.000,0.766,0.000,0.005,...,-0.111,0.111,0.000,-5.740,5.851,0.000,-0.766,0.000,0.100529,0
68,TUR,14.165,85.835,27.330,49.262,9.242,0.000,41.570,0.000,11.710,...,-2.455,2.455,2.059,-19.155,19.551,0.000,-15.185,0.000,0.392340,1
69,TKM,0.011,99.989,0.056,27.121,72.813,0.000,0.040,0.000,0.003,...,-0.008,0.008,-0.056,-1.170,1.233,0.000,-0.040,0.000,0.312606,1
70,UKR,1.500,87.876,32.169,16.586,39.120,10.625,5.091,36.079,2.464,...,0.964,-6.697,-0.827,-5.190,-0.680,5.732,2.000,11.135,-0.094177,0
71,ARE,0.000,100.000,0.000,50.151,49.849,0.000,0.000,0.000,0.005,...,0.005,-0.005,0.787,-11.891,11.099,0.000,0.021,0.000,0.376888,1
72,GBR,0.752,89.543,21.676,38.879,28.988,9.705,1.980,26.365,3.043,...,2.291,0.858,-7.301,-2.757,10.916,-3.149,4.872,-10.101,0.107496,0
73,USA,4.551,87.328,23.069,39.595,24.664,8.121,10.602,19.870,5.642,...,1.091,-1.529,-0.626,-1.318,0.415,0.438,-0.284,-0.254,0.111423,0
74,UZB,3.398,96.602,2.051,15.314,79.237,0.000,13.040,0.000,4.069,...,0.671,-0.671,-0.290,-5.156,4.775,0.000,2.719,0.000,0.403891,1
75,VEN,19.900,80.100,0.008,37.587,42.505,0.000,70.051,0.000,21.151,...,1.251,-1.251,0.238,7.890,-9.379,0.000,-2.558,0.000,0.015460,0
76,VNM,23.467,76.533,28.752,46.659,1.121,0.000,72.242,0.000,13.931,...,-9.536,9.536,2.866,-9.156,15.827,0.000,-41.038,0.000,0.343649,1

In [16]:
X=model_data[["renewables_share_energy_change","fossil_share_energy_change","coal_share_energy_change","oil_share_energy_change","gas_share_energy_change","nuclear_share_energy_change","renewables_share_elec_change","nuclear_share_elec_change"]]  #Predictor 
Y=model_data["high_growth"] #Response 

print(X.shape) 
print(Y.shape)

(77, 8)
(77,)

In [17]:
data_s2=pd.DataFrame(sovereign_countries).copy()
data_s2.dropna()
data_s2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 15649 entries, 26 to 23376
Data columns (total 130 columns):
 #    Column                                        Non-Null Count  Dtype
---   ------                                        --------------  -----
 0    country                                       15649 non-null  object
 1    year                                          15649 non-null  int64
 2    iso_code                                      15649 non-null  object
 3    population                                    15599 non-null  float64
 4    gdp                                           11319 non-null  float64
 5    biofuel_cons_change_pct                       1107 non-null   float64
 6    biofuel_cons_change_twh                       5286 non-null   float64
 7    biofuel_cons_per_capita                       5392 non-null   float64
 8    biofuel_consumption                           5392 non-null   float64
 9    biofuel_elec_per_capita                       5025 non-null   float64
 10   biofuel_electricity                           5025 non-null   float64
 11   biofuel_share_elec                            5023 non-null   float64
 12   biofuel_share_energy                          4339 non-null   float64
 13   carbon_intensity_elec                         5039 non-null   float64
 14   coal_cons_change_pct                          3846 non-null   float64
 15   coal_cons_change_twh                          4268 non-null   float64
 16   coal_cons_per_capita                          4345 non-null   float64
 17   coal_consumption                              4345 non-null   float64
 18   coal_elec_per_capita                          5364 non-null   float64
 19   coal_electricity                              5364 non-null   float64
 20   coal_prod_change_pct                          6274 non-null   float64
 21   coal_prod_change_twh                          11591 non-null  float64
 22   coal_prod_per_capita                          11777 non-null  float64
 23   coal_production                               11777 non-null  float64
 24   coal_share_elec                               5362 non-null   float64
 25   coal_share_energy                             4339 non-null   float64
 26   electricity_demand                            5041 non-null   float64
 27   electricity_demand_per_capita                 5041 non-null   float64
 28   electricity_generation                        5871 non-null   float64
 29   electricity_share_energy                      3063 non-null   float64
 30   energy_cons_change_pct                        8763 non-null   float64
 31   energy_cons_change_twh                        8832 non-null   float64
 32   energy_per_capita                             9020 non-null   float64
 33   energy_per_gdp                                7632 non-null   float64
 34   fossil_cons_change_pct                        4262 non-null   float64
 35   fossil_cons_change_twh                        4268 non-null   float64
 36   fossil_elec_per_capita                        5401 non-null   float64
 37   fossil_electricity                            5401 non-null   float64
 38   fossil_energy_per_capita                      4345 non-null   float64
 39   fossil_fuel_consumption                       4345 non-null   float64
 40   fossil_share_elec                             5399 non-null   float64
 41   fossil_share_energy                           4339 non-null   float64
 42   gas_cons_change_pct                           3781 non-null   float64
 43   gas_cons_change_twh                           4268 non-null   float64
 44   gas_consumption                               4345 non-null   float64
 45   gas_elec_per_capita                           5314 non-null   float64
 46   gas_electricity                               5314 non-null   float64
 47   gas_energy_per_capita                         4345 non-null   float64
 48   gas_prod_change_pct                           4991 non-null   float64
 49   gas_prod_change_twh                           11883 non-null  float64
 50   gas_prod_per_capita                           12069 non-null  float64
 51   gas_production                                12069 non-null  float64
 52   gas_share_elec                                5312 non-null   float64
 53   gas_share_energy                              4339 non-null   float64
 54   greenhouse_gas_emissions                      4711 non-null   float64
 55   hydro_cons_change_pct                         3740 non-null   float64
 56   hydro_cons_change_twh                         4268 non-null   float64
 57   hydro_consumption                             4345 non-null   float64
 58   hydro_elec_per_capita                         7075 non-null   float64
 59   hydro_electricity                             7075 non-null   float64
 60   hydro_energy_per_capita                       4345 non-null   float64
 61   hydro_share_elec                              5793 non-null   float64
 62   hydro_share_energy                            4339 non-null   float64
 63   low_carbon_cons_change_pct                    3938 non-null   float64
 64   low_carbon_cons_change_twh                    4268 non-null   float64
 65   low_carbon_consumption                        4345 non-null   float64
 66   low_carbon_elec_per_capita                    7151 non-null   float64
 67   low_carbon_electricity                        7151 non-null   float64
 68   low_carbon_energy_per_capita                  4345 non-null   float64
 69   low_carbon_share_elec                         5869 non-null   float64
 70   low_carbon_share_energy                       4339 non-null   float64
 71   net_elec_imports                              5041 non-null   float64
 72   net_elec_imports_share_demand                 5041 non-null   float64
 73   nuclear_cons_change_pct                       1436 non-null   float64
 74   nuclear_cons_change_twh                       5486 non-null   float64
 75   nuclear_consumption                           5589 non-null   float64
 76   nuclear_elec_per_capita                       7671 non-null   float64
 77   nuclear_electricity                           7671 non-null   float64
 78   nuclear_energy_per_capita                     5589 non-null   float64
 79   nuclear_share_elec                            5796 non-null   float64
 80   nuclear_share_energy                          4339 non-null   float64
 81   oil_cons_change_pct                           4262 non-null   float64
 82   oil_cons_change_twh                           4268 non-null   float64
 83   oil_consumption                               4345 non-null   float64
 84   oil_elec_per_capita                           5400 non-null   float64
 85   oil_electricity                               5400 non-null   float64
 86   oil_energy_per_capita                         4345 non-null   float64
 87   oil_prod_change_pct                           6296 non-null   float64
 88   oil_prod_change_twh                           12429 non-null  float64
 89   oil_prod_per_capita                           12615 non-null  float64
 90   oil_production                                12615 non-null  float64
 91   oil_share_elec                                5398 non-null   float64
 92   oil_share_energy                              4339 non-null   float64
 93   other_renewable_consumption                   4345 non-null   float64
 94   other_renewable_electricity                   7135 non-null   float64
 95   other_renewable_exc_biofuel_electricity       4455 non-null   float64
 96   other_renewables_cons_change_pct              2412 non-null   float64
 97   other_renewables_cons_change_twh              4268 non-null   float64
 98   other_renewables_elec_per_capita              7135 non-null   float64
 99   other_renewables_elec_per_capita_exc_biofuel  4455 non-null   float64
 100  other_renewables_energy_per_capita            4345 non-null   float64
 101  other_renewables_share_elec                   5853 non-null   float64
 102  other_renewables_share_elec_exc_biofuel       4453 non-null   float64
 103  other_renewables_share_energy                 4339 non-null   float64
 104  per_capita_electricity                        5871 non-null   float64
 105  primary_energy_consumption                    9020 non-null   float64
 106  renewables_cons_change_pct                    3931 non-null   float64
 107  renewables_cons_change_twh                    4268 non-null   float64
 108  renewables_consumption                        4345 non-null   float64
 109  renewables_elec_per_capita                    7151 non-null   float64
 110  renewables_electricity                        7151 non-null   float64
 111  renewables_energy_per_capita                  4345 non-null   float64
 112  renewables_share_elec                         5869 non-null   float64
 113  renewables_share_energy                       4339 non-null   float64
 114  solar_cons_change_pct                         1558 non-null   float64
 115  solar_cons_change_twh                         4268 non-null   float64
 116  solar_consumption                             4345 non-null   float64
 117  solar_elec_per_capita                         7148 non-null   float64
 118  solar_electricity                             7148 non-null   float64
 119  solar_energy_per_capita                       4345 non-null   float64
 120  solar_share_elec                              5866 non-null   float64
 121  solar_share_energy                            4339 non-null   float64
 122  wind_cons_change_pct                          1737 non-null   float64
 123  wind_cons_change_twh                          4268 non-null   float64
 124  wind_consumption                              4345 non-null   float64
 125  wind_elec_per_capita                          6977 non-null   float64
 126  wind_electricity                              6977 non-null   float64
 127  wind_energy_per_capita                        4345 non-null   float64
 128  wind_share_elec                               5695 non-null   float64
 129  wind_share_energy                             4339 non-null   float64
dtypes: float64(127), int64(1), object(2)
memory usage: 15.6+ MB

In [25]:
final_countries_full_history = sovereign_countries[
    sovereign_countries['iso_code'].isin(model_data['iso_code'])
]

print(final_countries_full_history.shape)
final_countries_full_history.dropna()
final_countries_full_history.head(100)

(8132, 130)

,country,year,iso_code,population,gdp,biofuel_cons_change_pct,biofuel_cons_change_twh,biofuel_cons_per_capita,biofuel_consumption,biofuel_elec_per_capita,...,solar_share_elec,solar_share_energy,wind_cons_change_pct,wind_cons_change_twh,wind_consumption,wind_elec_per_capita,wind_electricity,wind_energy_per_capita,wind_share_elec,wind_share_energy
648,Algeria,1900,DZA,4721802.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
649,Algeria,1901,DZA,4787149.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
650,Algeria,1902,DZA,4859600.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
651,Algeria,1903,DZA,4939332.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
652,Algeria,1904,DZA,5020372.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
653,Algeria,1905,DZA,5102742.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
654,Algeria,1906,DZA,5186463.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
655,Algeria,1907,DZA,5271557.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
656,Algeria,1908,DZA,5358048.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
657,Algeria,1909,DZA,5433528.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
658,Algeria,1910,DZA,5497750.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
659,Algeria,1911,DZA,5550464.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
660,Algeria,1912,DZA,5591415.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
661,Algeria,1913,DZA,5620343.0,1.019144e+10,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
662,Algeria,1914,DZA,5649420.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
663,Algeria,1915,DZA,5678648.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
664,Algeria,1916,DZA,5708027.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
665,Algeria,1917,DZA,5737558.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
666,Algeria,1918,DZA,5766569.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
667,Algeria,1919,DZA,5802743.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
668,Algeria,1920,DZA,5846192.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
669,Algeria,1921,DZA,5897033.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
670,Algeria,1922,DZA,5955381.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
671,Algeria,1923,DZA,6021355.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
672,Algeria,1924,DZA,6088060.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
673,Algeria,1925,DZA,6155505.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
674,Algeria,1926,DZA,6223696.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
675,Algeria,1927,DZA,6292643.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
676,Algeria,1928,DZA,6362353.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
677,Algeria,1929,DZA,6441431.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
678,Algeria,1930,DZA,6530132.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
679,Algeria,1931,DZA,6628718.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
680,Algeria,1932,DZA,6737455.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
681,Algeria,1933,DZA,6856617.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
682,Algeria,1934,DZA,6977885.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
683,Algeria,1935,DZA,7101299.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
684,Algeria,1936,DZA,7226895.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
685,Algeria,1937,DZA,7354713.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
686,Algeria,1938,DZA,7484792.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
687,Algeria,1939,DZA,7613042.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
688,Algeria,1940,DZA,7739370.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
689,Algeria,1941,DZA,7863680.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
690,Algeria,1942,DZA,7985870.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
691,Algeria,1943,DZA,8105839.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
692,Algeria,1944,DZA,8227611.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
693,Algeria,1945,DZA,8351211.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
694,Algeria,1946,DZA,8476669.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
695,Algeria,1947,DZA,8604011.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
696,Algeria,1948,DZA,8733267.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
697,Algeria,1949,DZA,8871792.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
698,Algeria,1950,DZA,9018423.0,1.935055e+10,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
699,Algeria,1951,DZA,9269870.0,1.948038e+10,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
700,Algeria,1952,DZA,9521212.0,2.035000e+10,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
701,Algeria,1953,DZA,9772644.0,2.079819e+10,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
702,Algeria,1954,DZA,10014393.0,2.201901e+10,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
703,Algeria,1955,DZA,10247429.0,2.266578e+10,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
704,Algeria,1956,DZA,10482183.0,2.489140e+10,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
705,Algeria,1957,DZA,10717503.0,2.772104e+10,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
706,Algeria,1958,DZA,10953641.0,2.872869e+10,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
707,Algeria,1959,DZA,11189621.0,3.399315e+10,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
708,Algeria,1960,DZA,11424930.0,3.630613e+10,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
709,Algeria,1961,DZA,11628877.0,3.189688e+10,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
710,Algeria,1962,DZA,11800768.0,2.512617e+10,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
711,Algeria,1963,DZA,11982121.0,3.176697e+10,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
712,Algeria,1964,DZA,12179807.0,3.343342e+10,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
713,Algeria,1965,DZA,12365979.0,3.566197e+10,NaN,NaN,0.0,0.0,NaN,...,NaN,0.0,NaN,NaN,0.0,0.0,0.0,0.0,NaN,0.0
714,Algeria,1966,DZA,12590068.0,3.393263e+10,NaN,0.0,0.0,0.0,NaN,...,NaN,0.0,NaN,0.0,0.0,0.0,0.0,0.0,NaN,0.0
715,Algeria,1967,DZA,12876115.0,3.709477e+10,NaN,0.0,0.0,0.0,NaN,...,NaN,0.0,NaN,0.0,0.0,0.0,0.0,0.0,NaN,0.0
716,Algeria,1968,DZA,13172615.0,4.142389e+10,NaN,0.0,0.0,0.0,NaN,...,NaN,0.0,NaN,0.0,0.0,0.0,0.0,0.0,NaN,0.0
717,Algeria,1969,DZA,13475959.0,4.538746e+10,NaN,0.0,0.0,0.0,NaN,...,NaN,0.0,NaN,0.0,0.0,0.0,0.0,0.0,NaN,0.0
718,Algeria,1970,DZA,13783722.0,4.994567e+10,NaN,0.0,0.0,0.0,NaN,...,NaN,0.0,NaN,0.0,0.0,0.0,0.0,0.0,NaN,0.0
719,Algeria,1971,DZA,14098937.0,4.570122e+10,NaN,0.0,0.0,0.0,NaN,...,NaN,0.0,NaN,0.0,0.0,0.0,0.0,0.0,NaN,0.0
720,Algeria,1972,DZA,14427075.0,5.529391e+10,NaN,0.0,0.0,0.0,NaN,...,NaN,0.0,NaN,0.0,0.0,0.0,0.0,0.0,NaN,0.0
721,Algeria,1973,DZA,14771150.0,5.709785e+10,NaN,0.0,0.0,0.0,NaN,...,NaN,0.0,NaN,0.0,0.0,0.0,0.0,0.0,NaN,0.0
722,Algeria,1974,DZA,15133508.0,6.057788e+10,NaN,0.0,0.0,0.0,NaN,...,NaN,0.0,NaN,0.0,0.0,0.0,0.0,0.0,NaN,0.0
723,Algeria,1975,DZA,15678603.0,6.488381e+10,NaN,0.0,0.0,0.0,NaN,...,NaN,0.0,NaN,0.0,0.0,0.0,0.0,0.0,NaN,0.0
724,Algeria,1976,DZA,16409171.0,6.915010e+10,NaN,0.0,0.0,0.0,NaN,...,NaN,0.0,NaN,0.0,0.0,0.0,0.0,0.0,NaN,0.0
725,Algeria,1977,DZA,17015988.0,7.543804e+10,NaN,0.0,0.0,0.0,NaN,...,NaN,0.0,NaN,0.0,0.0,0.0,0.0,0.0,NaN,0.0
726,Algeria,1978,DZA,17506977.0,8.510391e+10,NaN,0.0,0.0,0.0,NaN,...,NaN,0.0,NaN,0.0,0.0,0.0,0.0,0.0,NaN,0.0
727,Algeria,1979,DZA,18036655.0,9.275389e+10,NaN,0.0,0.0,0.0,NaN,...,NaN,0.0,NaN,0.0,0.0,0.0,0.0,0.0,NaN,0.0
728,Algeria,1980,DZA,18607175.0,9.448165e+10,NaN,0.0,0.0,0.0,NaN,...,NaN,0.0,NaN,0.0,0.0,0.0,0.0,0.0,NaN,0.0
729,Algeria,1981,DZA,19220708.0,9.686051e+10,NaN,0.0,0.0,0.0,NaN,...,NaN,0.0,NaN,0.0,0.0,0.0,0.0,0.0,NaN,0.0
730,Algeria,1982,DZA,19872353.0,1.030737e+11,NaN,0.0,0.0,0.0,NaN,...,NaN,0.0,NaN,0.0,0.0,0.0,0.0,0.0,NaN,0.0
731,Algeria,1983,DZA,20558120.0,1.084304e+11,NaN,0.0,0.0,0.0,NaN,...,NaN,0.0,NaN,0.0,0.0,0.0,0.0,0.0,NaN,0.0
732,Algeria,1984,DZA,21271969.0,1.144067e+11,NaN,0.0,0.0,0.0,NaN,...,NaN,0.0,NaN,0.0,0.0,0.0,0.0,0.0,NaN,0.0
733,Algeria,1985,DZA,22008542.0,1.203642e+11,NaN,0.0,0.0,0.0,NaN,...,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
734,Algeria,1986,DZA,22745501.0,1.191450e+11,NaN,0.0,0.0,0.0,NaN,...,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
735,Algeria,1987,DZA,23443627.0,1.183212e+11,NaN,0.0,0.0,0.0,NaN,...,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
736,Algeria,1988,DZA,24109538.0,1.158217e+11,NaN,0.0,0.0,0.0,NaN,...,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
737,Algeria,1989,DZA,24754488.0,1.197624e+11,NaN,0.0,0.0,0.0,NaN,...,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
738,Algeria,1990,DZA,25375815.0,1.178432e+11,NaN,0.0,0.0,0.0,NaN,...,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
739,Algeria,1991,DZA,25987937.0,1.211051e+11,NaN,0.0,0.0,0.0,NaN,...,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
740,Algeria,1992,DZA,26628570.0,1.279827e+11,NaN,0.0,0.0,0.0,NaN,...,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
741,Algeria,1993,DZA,27277042.0,1.302758e+11,NaN,0.0,0.0,0.0,NaN,...,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
742,Algeria,1994,DZA,27887277.0,1.342799e+11,NaN,0.0,0.0,0.0,NaN,...,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
743,Algeria,1995,DZA,28470194.0,1.450547e+11,NaN,0.0,0.0,0.0,NaN,...,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
744,Algeria,1996,DZA,29033045.0,1.565791e+11,NaN,0.0,0.0,0.0,NaN,...,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
745,Algeria,1997,DZA,29579299.0,1.646445e+11,NaN,0.0,0.0,0.0,NaN,...,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
746,Algeria,1998,DZA,30054135.0,1.799629e+11,NaN,0.0,0.0,0.0,NaN,...,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
747,Algeria,1999,DZA,30474360.0,1.931798e+11,NaN,0.0,0.0,0.0,NaN,...,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [19]:
final_countries_full_history_clean = final_countries_full_history.dropna(subset=['renewables_share_energy'])  # or whatever subset you actually need
print(final_countries_full_history_clean.shape)
final_countries_full_history_clean

(4339, 130)

                    country  year iso_code    population           gdp  \
713                 Algeria  1965      DZA  1.236598e+07  3.566197e+10
714                 Algeria  1966      DZA  1.259007e+07  3.393263e+10
715                 Algeria  1967      DZA  1.287612e+07  3.709477e+10
716                 Algeria  1968      DZA  1.317262e+07  4.142389e+10
717                 Algeria  1969      DZA  1.347596e+07  4.538746e+10
718                 Algeria  1970      DZA  1.378372e+07  4.994567e+10
719                 Algeria  1971      DZA  1.409894e+07  4.570122e+10
720                 Algeria  1972      DZA  1.442708e+07  5.529391e+10
721                 Algeria  1973      DZA  1.477115e+07  5.709785e+10
722                 Algeria  1974      DZA  1.513351e+07  6.057788e+10
723                 Algeria  1975      DZA  1.567860e+07  6.488381e+10
724                 Algeria  1976      DZA  1.640917e+07  6.915010e+10
725                 Algeria  1977      DZA  1.701599e+07  7.543804e+10
726                 Algeria  1978      DZA  1.750698e+07  8.510391e+10
727                 Algeria  1979      DZA  1.803666e+07  9.275389e+10
728                 Algeria  1980      DZA  1.860718e+07  9.448165e+10
729                 Algeria  1981      DZA  1.922071e+07  9.686051e+10
730                 Algeria  1982      DZA  1.987235e+07  1.030737e+11
731                 Algeria  1983      DZA  2.055812e+07  1.084304e+11
732                 Algeria  1984      DZA  2.127197e+07  1.144067e+11
733                 Algeria  1985      DZA  2.200854e+07  1.203642e+11
734                 Algeria  1986      DZA  2.274550e+07  1.191450e+11
735                 Algeria  1987      DZA  2.344363e+07  1.183212e+11
736                 Algeria  1988      DZA  2.410954e+07  1.158217e+11
737                 Algeria  1989      DZA  2.475449e+07  1.197624e+11
738                 Algeria  1990      DZA  2.537582e+07  1.178432e+11
739                 Algeria  1991      DZA  2.598794e+07  1.211051e+11
740                 Algeria  1992      DZA  2.662857e+07  1.279827e+11
741                 Algeria  1993      DZA  2.727704e+07  1.302758e+11
742                 Algeria  1994      DZA  2.788728e+07  1.342799e+11
743                 Algeria  1995      DZA  2.847019e+07  1.450547e+11
744                 Algeria  1996      DZA  2.903304e+07  1.565791e+11
745                 Algeria  1997      DZA  2.957930e+07  1.646445e+11
746                 Algeria  1998      DZA  3.005414e+07  1.799629e+11
747                 Algeria  1999      DZA  3.047436e+07  1.931798e+11
748                 Algeria  2000      DZA  3.090389e+07  2.085542e+11
749                 Algeria  2001      DZA  3.133123e+07  2.234203e+11
750                 Algeria  2002      DZA  3.175083e+07  2.453609e+11
751                 Algeria  2003      DZA  3.217581e+07  2.735686e+11
752                 Algeria  2004      DZA  3.262829e+07  2.967736e+11
753                 Algeria  2005      DZA  3.310926e+07  3.268545e+11
754                 Algeria  2006      DZA  3.362350e+07  3.457053e+11
755                 Algeria  2007      DZA  3.418942e+07  3.716653e+11
756                 Algeria  2008      DZA  3.481696e+07  3.956585e+11
757                 Algeria  2009      DZA  3.549044e+07  4.182477e+11
758                 Algeria  2010      DZA  3.618824e+07  4.507058e+11
759                 Algeria  2011      DZA  3.690337e+07  4.820287e+11
760                 Algeria  2012      DZA  3.764616e+07  4.984176e+11
761                 Algeria  2013      DZA  3.841418e+07  5.123733e+11
762                 Algeria  2014      DZA  3.920504e+07  5.318435e+11
763                 Algeria  2015      DZA  4.001953e+07  5.515217e+11
764                 Algeria  2016      DZA  4.085072e+07  5.691704e+11
765                 Algeria  2017      DZA  4.168930e+07  5.771388e+11
766                 Algeria  2018      DZA  4.250503e+07  5.840644e+11
767                 Algeria  2019      DZA  4.329455e+07  5.899051e+11
768                 Algeria  2020      DZA  4.404209e+07  5.598200e+11
769                 Algeria  2021      DZA  4.476110e+07  5.788538e+11
770                 Algeria  2022      DZA  4.547739e+07  5.958201e+11
771                 Algeria  2023      DZA  4.616422e+07           NaN
772                 Algeria  2024      DZA  4.681430e+07           NaN
1097              Argentina  1965      ARG  2.211263e+07  2.262849e+11
1098              Argentina  1966      ARG  2.245390e+07  2.278345e+11
1099              Argentina  1967      ARG  2.279906e+07  2.339291e+11
1100              Argentina  1968      ARG  2.315058e+07  2.438865e+11
1101              Argentina  1969      ARG  2.350872e+07  2.647215e+11
1102              Argentina  1970      ARG  2.387833e+07  2.788974e+11
1103              Argentina  1971      ARG  2.425721e+07  2.924389e+11
1104              Argentina  1972      ARG  2.464433e+07  3.015702e+11
1105              Argentina  1973      ARG  2.504601e+07  3.199379e+11
1106              Argentina  1974      ARG  2.546135e+07  3.406864e+11
1107              Argentina  1975      ARG  2.587411e+07  3.376560e+11
1108              Argentina  1976      ARG  2.628228e+07  3.368411e+11
1109              Argentina  1977      ARG  2.670182e+07  3.571579e+11
1110              Argentina  1978      ARG  2.713216e+07  3.414667e+11
1111              Argentina  1979      ARG  2.756889e+07  3.659064e+11
1112              Argentina  1980      ARG  2.801160e+07  3.710770e+11
1113              Argentina  1981      ARG  2.846396e+07  3.497820e+11
1114              Argentina  1982      ARG  2.892427e+07  3.387615e+11
1115              Argentina  1983      ARG  2.939133e+07  3.507066e+11
1116              Argentina  1984      ARG  2.986309e+07  3.578443e+11
1117              Argentina  1985      ARG  3.033645e+07  3.341714e+11
1118              Argentina  1986      ARG  3.081198e+07  3.586347e+11
1119              Argentina  1987      ARG  3.129176e+07  3.678936e+11
1120              Argentina  1988      ARG  3.178053e+07  3.609212e+11
1121              Argentina  1989      ARG  3.227096e+07  3.385208e+11
1122              Argentina  1990      ARG  3.275591e+07  3.387511e+11
1123              Argentina  1991      ARG  3.323029e+07  3.760579e+11
1124              Argentina  1992      ARG  3.369353e+07  4.166798e+11
1125              Argentina  1993      ARG  3.415272e+07  4.447803e+11
1126              Argentina  1994      ARG  3.461349e+07  4.729268e+11
1127              Argentina  1995      ARG  3.507002e+07  4.616010e+11
1128              Argentina  1996      ARG  3.551380e+07  4.894065e+11
1129              Argentina  1997      ARG  3.594779e+07  5.315264e+11
1130              Argentina  1998      ARG  3.637286e+07  5.545671e+11
1131              Argentina  1999      ARG  3.679469e+07  5.382706e+11
1132              Argentina  2000      ARG  3.721399e+07  5.364810e+11
1133              Argentina  2001      ARG  3.762482e+07  5.148673e+11
1134              Argentina  2002      ARG  3.802934e+07  4.605585e+11
1135              Argentina  2003      ARG  3.842428e+07  5.031042e+11
1136              Argentina  2004      ARG  3.881592e+07  5.503063e+11
1137              Argentina  2005      ARG  3.921679e+07  6.010504e+11
1138              Argentina  2006      ARG  3.962211e+07  6.522968e+11
1139              Argentina  2007      ARG  4.001677e+07  7.147252e+11
1140              Argentina  2008      ARG  4.042415e+07  7.471574e+11
1141              Argentina  2009      ARG  4.085483e+07  7.059208e+11
1142              Argentina  2010      ARG  4.128869e+07  7.857852e+11
1143              Argentina  2011      ARG  4.173066e+07  8.377427e+11
1144              Argentina  2012      ARG  4.216172e+07  8.291474e+11
1145              Argentina  2013      ARG  4.258245e+07  8.490884e+11
1146              Argentina  2014      ARG  4.302407e+07  8.277508e+11
1147              Argentina  2015      ARG  4.347701e+07  8.503566e+11
1148              Argentina  2016      ARG  4.390031e+07  8.326693e+11
1149              Argentina  2017      ARG  4.428890e+07  8.561422e+11
1150              Argentina  2018      ARG  4.465488e+07  8.337370e+11
1151              Argentina  2019      ARG  4.497347e+07  8.170539e+11
1152              Argentina  2020      ARG  4.519196e+07  7.358143e+11
1153              Argentina  2021      ARG  4.531228e+07  8.123242e+11
1154              Argentina  2022      ARG  4.540790e+07  8.549144e+11
1155              Argentina  2023      ARG  4.553840e+07           NaN
1156              Argentina  2024      ARG  4.569615e+07           NaN
1668              Australia  1965      AUS  1.135748e+07  1.851121e+11
1669              Australia  1966      AUS  1.159248e+07  1.902576e+11
1670              Australia  1967      AUS  1.181052e+07  2.031107e+11
1671              Australia  1968      AUS  1.203001e+07  2.150465e+11
1672              Australia  1969      AUS  1.227239e+07  2.281273e+11
1673              Australia  1970      AUS  1.259941e+07  2.426446e+11
1674              Australia  1971      AUS  1.299796e+07  2.534398e+11
1675              Australia  1972      AUS  1.330490e+07  2.605356e+11
1676              Australia  1973      AUS  1.351869e+07  2.746595e+11
1677              Australia  1974      AUS  1.371950e+07  2.814742e+11
1678              Australia  1975      AUS  1.389399e+07  2.891030e+11
1679              Australia  1976      AUS  1.404676e+07  3.007557e+11
1680              Australia  1977      AUS  1.420351e+07  3.038880e+11
1681              Australia  1978      AUS  1.436710e+07  3.127283e+11
1682              Australia  1979      AUS  1.453303e+07  3.291943e+11
1683              Australia  1980      AUS  1.472134e+07  3.357565e+11
1684              Australia  1981      AUS  1.494921e+07  3.487267e+11
1685              Australia  1982      AUS  1.519248e+07  3.483015e+11
1686              Australia  1983      AUS  1.541489e+07  3.483536e+11
1687              Australia  1984      AUS  1.562065e+07  3.723796e+11
1688              Australia  1985      AUS  1.583574e+07  3.912293e+11
1689              Australia  1986      AUS  1.606963e+07  3.993444e+11
1690              Australia  1987      AUS  1.632227e+07  4.190940e+11
1691              Australia  1988      AUS  1.659410e+07  4.379128e+11
1692              Australia  1989      AUS  1.686936e+07  4.571762e+11
1693              Australia  1990      AUS  1.712630e+07  4.641366e+11
1694              Australia  1991      AUS  1.735319e+07  4.613021e+11
1695              Australia  1992      AUS  1.754929e+07  4.786337e+11
1696              Australia  1993      AUS  1.772290e+07  5.015248e+11
1697              Australia  1994      AUS  1.789743e+07  5.279932e+11
1698              Australia  1995      AUS  1.809534e+07  5.490387e+11
1699              Australia  1996      AUS  1.830530e+07  5.747656e+11
1700              Australia  1997      AUS  1.850491e+07  6.014728e+11
1701              Australia  1998      AUS  1.870171e+07  6.348471e+11
1702              Australia  1999      AUS  1.890998e+07  6.645207e+11
1703              Australia  2000      AUS  1.913247e+07  6.920593e+11
1704              Australia  2001      AUS  1.936544e+07  7.138901e+11
1705              Australia  2002      AUS  1.959536e+07  7.470657e+11
1706              Australia  2003      AUS  1.981945e+07  7.744510e+11
1707              Australia  2004      AUS  2.004668e+07  8.097924e+11
1708              Australia  2005      AUS  2.029449e+07  8.400924e+11
1709              Australia  2006      AUS  2.059057e+07  8.666787e+11
1710              Australia  2007      AUS  2.095454e+07  9.112507e+11
1711              Australia  2008      AUS  2.137060e+07  9.378896e+11
1712              Australia  2009      AUS  2.178301e+07  9.631299e+11
1713              Australia  2010      AUS  2.214158e+07  9.938540e+11
1714              Australia  2011      AUS  2.247978e+07  1.024000e+12
1715              Australia  2012      AUS  2.285265e+07  1.062663e+12
1716              Australia  2013      AUS  2.323627e+07  1.086068e+12
1717              Australia  2014      AUS  2.359560e+07  1.113888e+12
1718              Australia  2015      AUS  2.394800e+07  1.139303e+12
1719              Australia  2016      AUS  2.432996e+07  1.169967e+12
1720              Australia  2017      AUS  2.473104e+07  1.197833e+12
1721              Australia  2018      AUS  2.511970e+07  1.231577e+12
1722              Australia  2019      AUS  2.548271e+07  1.255506e+12
1723              Australia  2020      AUS  2.574379e+07  1.232260e+12
1724              Australia  2021      AUS  2.595642e+07  1.296705e+12
1725              Australia  2022      AUS  2.620099e+07  1.344251e+12
1726              Australia  2023      AUS  2.645113e+07           NaN
1727              Australia  2024      AUS  2.671321e+07           NaN
1838                Austria  1965      AUT  7.270413e+06  8.963552e+10
1839                Austria  1966      AUT  7.321524e+06  9.467431e+10
1840                Austria  1967      AUT  7.376293e+06  9.756080e+10
1841                Austria  1968      AUT  7.414627e+06  1.019025e+11
1842                Austria  1969      AUT  7.440306e+06  1.083046e+11
1843                Austria  1970      AUT  7.466320e+06  1.160161e+11
1844                Austria  1971      AUT  7.499635e+06  1.219503e+11
1845                Austria  1972      AUT  7.543263e+06  1.295264e+11
1846                Austria  1973      AUT  7.585107e+06  1.358522e+11
1847                Austria  1974      AUT  7.597963e+06  1.412129e+11
1848                Austria  1975      AUT  7.577833e+06  1.406948e+11
1849                Austria  1976      AUT  7.564457e+06  1.471343e+11
1850                Austria  1977      AUT  7.567332e+06  1.540176e+11
1851                Austria  1978      AUT  7.561203e+06  1.534619e+11
1852                Austria  1979      AUT  7.548345e+06  1.618295e+11
1853                Austria  1980      AUT  7.548407e+06  1.655742e+11
1854                Austria  1981      AUT  7.567550e+06  1.654082e+11
1855                Austria  1982      AUT  7.573078e+06  1.685654e+11
1856                Austria  1983      AUT  7.561166e+06  1.732936e+11
1857                Austria  1984      AUT  7.560715e+06  1.738659e+11
1858                Austria  1985      AUT  7.564310e+06  1.777606e+11
1859                Austria  1986      AUT  7.569397e+06  1.819330e+11
1860                Austria  1987      AUT  7.574314e+06  1.849934e+11
1861                Austria  1988      AUT  7.585346e+06  1.908460e+11
1862                Austria  1989      AUT  7.620405e+06  1.989194e+11
1863                Austria  1990      AUT  7.679627e+06  2.079791e+11
1864                Austria  1991      AUT  7.757140e+06  2.159927e+11
1865                Austria  1992      AUT  7.842715e+06  2.214009e+11
1866                Austria  1993      AUT  7.907492e+06  2.234629e+11
1867                Austria  1994      AUT  7.938157e+06  2.297493e+11
1868                Austria  1995      AUT  7.950322e+06  2.368245e+11
1869                Austria  1996      AUT  7.960917e+06  2.434807e+11
1870                Austria  1997      AUT  7.969804e+06  2.498473e+11
1871                Austria  1998      AUT  7.978465e+06  2.597763e+11
1872                Austria  1999      AUT  7.993894e+06  2.701862e+11
1873                Austria  2000      AUT  8.012929e+06  2.804102e+11
1874                Austria  2001      AUT  8.042233e+06  2.853357e+11
1875                Austria  2002      AUT  8.081640e+06  2.912314e+11
1876                Austria  2003      AUT  8.122604e+06  2.944893e+11
1877                Austria  2004      AUT  8.173496e+06  3.036925e+11
1878                Austria  2005      AUT  8.229204e+06  3.114411e+11
1879                Austria  2006      AUT  8.269901e+06  3.232369e+11
1880                Austria  2007      AUT  8.296948e+06  3.363040e+11
1881                Austria  2008      AUT  8.323250e+06  3.428925e+11
1882                Austria  2009      AUT  8.345073e+06  3.311190e+11
1883                Austria  2010      AUT  8.365087e+06  3.388322e+11
1884                Austria  2011      AUT  8.393272e+06  3.497135e+11
1885                Austria  2012      AUT  8.431599e+06  3.520931e+11
1886                Austria  2013      AUT  8.481411e+06  3.521829e+11
1887                Austria  2014      AUT  8.547812e+06  3.545118e+11
1888                Austria  2015      AUT  8.644037e+06  3.581083e+11
1889                Austria  2016      AUT  8.737920e+06  3.652327e+11
1890                Austria  2017      AUT  8.798779e+06  3.734817e+11
1891                Austria  2018      AUT  8.841653e+06  3.825400e+11
1892                Austria  2019      AUT  8.880876e+06  3.883447e+11
1893                Austria  2020      AUT  8.921402e+06  3.632811e+11
1894                Austria  2021      AUT  8.967053e+06  3.798352e+11
1895                Austria  2022      AUT  9.064678e+06  3.988154e+11
1896                Austria  2023      AUT  9.130434e+06           NaN
1897                Austria  2024      AUT  9.120815e+06           NaN
1899             Azerbaijan  1985      AZE  6.799823e+06  5.718188e+10
1900             Azerbaijan  1986      AZE  6.891349e+06  5.870459e+10
1901             Azerbaijan  1987      AZE  6.977658e+06  6.183143e+10
1902             Azerbaijan  1988      AZE  7.081404e+06  6.507024e+10
1903             Azerbaijan  1989      AZE  7.167583e+06  5.980371e+10
1904             Azerbaijan  1990      AZE  7.231084e+06  5.323560e+10
1905             Azerbaijan  1991      AZE  7.314317e+06  5.342662e+10
1906             Azerbaijan  1992      AZE  7.405781e+06  4.179530e+10
1907             Azerbaijan  1993      AZE  7.504119e+06  3.248644e+10
1908             Azerbaijan  1994      AZE  7.608894e+06  2.637210e+10
1909             Azerbaijan  1995      AZE  7.719283e+06  2.318828e+10
1910             Azerbaijan  1996      AZE  7.830981e+06  2.402638e+10
1911             Azerbaijan  1997      AZE  7.936220e+06  2.643693e+10
1912             Azerbaijan  1998      AZE  8.025808e+06  2.832846e+10
1913             Azerbaijan  1999      AZE  8.100472e+06  3.189857e+10
1914             Azerbaijan  2000      AZE  8.174784e+06  3.425571e+10
1915             Azerbaijan  2001      AZE  8.251776e+06  3.686218e+10
1916             Azerbaijan  2002      AZE  8.326141e+06  4.029522e+10
1917             Azerbaijan  2003      AZE  8.400528e+06  4.499464e+10
1918             Azerbaijan  2004      AZE  8.489874e+06  5.010748e+10
1919             Azerbaijan  2005      AZE  8.597248e+06  6.401918e+10
1920             Azerbaijan  2006      AZE  8.711380e+06  8.702641e+10
1921             Azerbaijan  2007      AZE  8.828313e+06  1.099443e+11
1922             Azerbaijan  2008      AZE  8.942637e+06  1.231300e+11
1923             Azerbaijan  2009      AZE  9.046336e+06  1.360202e+11
1924             Azerbaijan  2010      AZE  9.146852e+06  1.442966e+11
1925             Azerbaijan  2011      AZE  9.256156e+06  1.459805e+11
1926             Azerbaijan  2012      AZE  9.376179e+06  1.491964e+11
1927             Azerbaijan  2013      AZE  9.504417e+06  1.579140e+11
1928             Azerbaijan  2014      AZE  9.631136e+06  1.623324e+11
1929             Azerbaijan  2015      AZE  9.752859e+06  1.640369e+11
1930             Azerbaijan  2016      AZE  9.868434e+06  1.590108e+11
1931             Azerbaijan  2017      AZE  9.968510e+06  1.592557e+11
1932             Azerbaijan  2018      AZE  1.003978e+07  1.616445e+11
1933             Azerbaijan  2019      AZE  1.011048e+07  1.656533e+11
1934             Azerbaijan  2020      AZE  1.018174e+07  1.586975e+11
1935             Azerbaijan  2021      AZE  1.023437e+07  1.675846e+11
1936             Azerbaijan  2022      AZE  1.029531e+07  1.753706e+11
1937             Azerbaijan  2023      AZE  1.031821e+07           NaN
1938             Azerbaijan  2024      AZE  1.033658e+07           NaN

In [20]:
# Dataframe with features

new_data=pd.DataFrame(final_countries_full_history_clean[[
    "country",
    "year",
    "iso_code",
    "population",
    "electricity_generation",
    "primary_energy_consumption",
    "fossil_share_energy",
    "energy_per_capita",
    "gdp"
]])
new_data.head(1000)

,country,year,iso_code,population,electricity_generation,primary_energy_consumption,fossil_share_energy,energy_per_capita,gdp
713,Algeria,1965,DZA,1.236598e+07,NaN,24.833,95.513,2008.143,3.566197e+10
714,Algeria,1966,DZA,1.259007e+07,NaN,29.833,96.687,2369.529,3.393263e+10
715,Algeria,1967,DZA,1.287612e+07,NaN,28.247,95.958,2193.783,3.709477e+10
716,Algeria,1968,DZA,1.317262e+07,NaN,30.345,94.829,2303.642,4.142389e+10
717,Algeria,1969,DZA,1.347596e+07,NaN,33.539,97.004,2488.817,4.538746e+10
718,Algeria,1970,DZA,1.378372e+07,NaN,36.759,95.605,2666.834,4.994567e+10
719,Algeria,1971,DZA,1.409894e+07,NaN,39.733,97.689,2818.145,4.570122e+10
720,Algeria,1972,DZA,1.442708e+07,NaN,44.648,96.914,3094.726,5.529391e+10
721,Algeria,1973,DZA,1.477115e+07,NaN,53.251,96.067,3605.046,5.709785e+10
722,Algeria,1974,DZA,1.513351e+07,NaN,58.909,97.653,3892.616,6.057788e+10
723,Algeria,1975,DZA,1.567860e+07,NaN,70.370,98.704,4488.262,6.488381e+10
724,Algeria,1976,DZA,1.640917e+07,NaN,82.102,98.683,5003.428,6.915010e+10
725,Algeria,1977,DZA,1.701599e+07,NaN,90.213,99.171,5301.638,7.543804e+10
726,Algeria,1978,DZA,1.750698e+07,NaN,113.361,99.387,6475.217,8.510391e+10
727,Algeria,1979,DZA,1.803666e+07,NaN,148.540,99.456,8235.463,9.275389e+10
728,Algeria,1980,DZA,1.860718e+07,NaN,177.143,99.597,9520.142,9.448165e+10
729,Algeria,1981,DZA,1.922071e+07,NaN,215.186,99.527,11195.538,9.686051e+10
730,Algeria,1982,DZA,1.987235e+07,NaN,248.112,99.464,12485.292,1.030737e+11
731,Algeria,1983,DZA,2.055812e+07,NaN,270.967,99.759,13180.519,1.084304e+11
732,Algeria,1984,DZA,2.127197e+07,NaN,260.196,99.517,12231.881,1.144067e+11
733,Algeria,1985,DZA,2.200854e+07,12.274,262.297,99.316,11917.944,1.203642e+11
734,Algeria,1986,DZA,2.274550e+07,12.981,277.491,99.750,12199.799,1.191450e+11
735,Algeria,1987,DZA,2.344363e+07,12.722,285.168,99.514,12163.992,1.183212e+11
736,Algeria,1988,DZA,2.410954e+07,13.966,305.422,99.834,12668.091,1.158217e+11
737,Algeria,1989,DZA,2.475449e+07,15.324,297.068,99.789,12000.583,1.197624e+11
738,Algeria,1990,DZA,2.537582e+07,16.104,314.974,99.881,12412.359,1.178432e+11
739,Algeria,1991,DZA,2.598794e+07,17.345,312.095,99.739,12009.229,1.211051e+11
740,Algeria,1992,DZA,2.662857e+07,18.286,320.227,99.827,12025.688,1.279827e+11
741,Algeria,1993,DZA,2.727704e+07,19.414,297.995,99.671,10924.754,1.302758e+11
742,Algeria,1994,DZA,2.788728e+07,19.883,301.921,99.847,10826.482,1.342799e+11
743,Algeria,1995,DZA,2.847019e+07,19.715,313.145,99.829,10999.042,1.450547e+11
744,Algeria,1996,DZA,2.903304e+07,20.654,309.925,99.879,10674.896,1.565791e+11
745,Algeria,1997,DZA,2.957930e+07,21.497,297.860,99.930,10069.873,1.646445e+11
746,Algeria,1998,DZA,3.005414e+07,23.262,308.349,99.806,10259.786,1.799629e+11
747,Algeria,1999,DZA,3.047436e+07,24.757,311.434,99.819,10219.548,1.931798e+11
748,Algeria,2000,DZA,3.090389e+07,25.400,299.946,99.950,9705.756,2.085542e+11
749,Algeria,2001,DZA,3.133123e+07,26.620,310.813,99.939,9920.229,2.234203e+11
750,Algeria,2002,DZA,3.175083e+07,27.650,321.951,99.951,10139.907,2.453609e+11
751,Algeria,2003,DZA,3.217581e+07,29.570,336.922,99.786,10471.285,2.735686e+11
752,Algeria,2004,DZA,3.262829e+07,31.250,349.778,99.806,10720.079,2.967736e+11
753,Algeria,2005,DZA,3.310926e+07,33.910,366.272,99.592,11062.512,3.268545e+11
754,Algeria,2006,DZA,3.362350e+07,35.230,379.220,99.847,11278.422,3.457053e+11
755,Algeria,2007,DZA,3.418942e+07,37.190,399.640,99.850,11688.989,3.716653e+11
756,Algeria,2008,DZA,3.481696e+07,40.230,423.557,99.824,12165.246,3.956585e+11
757,Algeria,2009,DZA,3.549044e+07,38.500,448.859,99.800,12647.330,4.182477e+11
758,Algeria,2010,DZA,3.618824e+07,45.730,438.995,99.892,12130.873,4.507058e+11
759,Algeria,2011,DZA,3.690337e+07,51.220,464.488,99.779,12586.607,4.820287e+11
760,Algeria,2012,DZA,3.764616e+07,57.400,507.672,99.789,13485.354,4.984176e+11
761,Algeria,2013,DZA,3.841418e+07,59.890,536.977,99.939,13978.610,5.123733e+11
762,Algeria,2014,DZA,3.920504e+07,64.270,585.613,99.890,14937.195,5.318435e+11
763,Algeria,2015,DZA,4.001953e+07,68.840,617.518,99.909,15430.422,5.515217e+11
764,Algeria,2016,DZA,4.085072e+07,71.040,616.996,99.863,15103.672,5.691704e+11
765,Algeria,2017,DZA,4.168930e+07,76.070,623.795,99.768,14962.943,5.771388e+11
766,Algeria,2018,DZA,4.250503e+07,76.750,669.620,99.729,15753.894,5.840644e+11
767,Algeria,2019,DZA,4.329455e+07,81.610,694.349,99.723,16037.789,5.899051e+11
768,Algeria,2020,DZA,4.404209e+07,79.370,648.899,99.717,14733.604,5.598200e+11
769,Algeria,2021,DZA,4.476110e+07,85.600,707.627,99.762,15808.980,5.788538e+11
770,Algeria,2022,DZA,4.547739e+07,91.470,734.248,99.772,16145.337,5.958201e+11
771,Algeria,2023,DZA,4.616422e+07,95.880,784.532,99.773,16994.377,NaN
772,Algeria,2024,DZA,4.681430e+07,96.360,760.133,99.758,16237.188,NaN
1097,Argentina,1965,ARG,2.211263e+07,NaN,328.528,98.963,14857.010,2.262849e+11
1098,Argentina,1966,ARG,2.245390e+07,NaN,339.175,98.983,15105.385,2.278345e+11
1099,Argentina,1967,ARG,2.279906e+07,NaN,349.032,98.988,15309.062,2.339291e+11
1100,Argentina,1968,ARG,2.315058e+07,NaN,360.844,98.846,15586.842,2.438865e+11
1101,Argentina,1969,ARG,2.350872e+07,NaN,372.911,98.999,15862.656,2.647215e+11
1102,Argentina,1970,ARG,2.387833e+07,NaN,353.487,98.726,14803.654,2.788974e+11
1103,Argentina,1971,ARG,2.425721e+07,NaN,374.742,98.804,15448.672,2.924389e+11
1104,Argentina,1972,ARG,2.464433e+07,NaN,379.448,98.837,15396.966,3.015702e+11
1105,Argentina,1973,ARG,2.504601e+07,NaN,396.458,97.850,15829.181,3.199379e+11
1106,Argentina,1974,ARG,2.546135e+07,NaN,412.278,95.881,16192.301,3.406864e+11
1107,Argentina,1975,ARG,2.587411e+07,NaN,402.571,94.615,15558.845,3.376560e+11
1108,Argentina,1976,ARG,2.628228e+07,NaN,422.714,94.957,16083.609,3.368411e+11
1109,Argentina,1977,ARG,2.670182e+07,NaN,441.458,95.284,16532.896,3.571579e+11
1110,Argentina,1978,ARG,2.713216e+07,NaN,444.487,93.280,16382.302,3.414667e+11
1111,Argentina,1979,ARG,2.756889e+07,NaN,475.767,92.109,17257.400,3.659064e+11
1112,Argentina,1980,ARG,2.801160e+07,NaN,473.282,89.612,16895.920,3.710770e+11
1113,Argentina,1981,ARG,2.846396e+07,NaN,458.869,89.281,16121.061,3.497820e+11
1114,Argentina,1982,ARG,2.892427e+07,NaN,470.355,88.349,16261.604,3.387615e+11
1115,Argentina,1983,ARG,2.939133e+07,NaN,490.868,87.462,16701.121,3.507066e+11
1116,Argentina,1984,ARG,2.986309e+07,NaN,492.394,85.986,16488.375,3.578443e+11
1117,Argentina,1985,ARG,3.033645e+07,45.304,486.092,84.698,16023.380,3.341714e+11
1118,Argentina,1986,ARG,3.081198e+07,49.022,509.708,85.231,16542.523,3.586347e+11
1119,Argentina,1987,ARG,3.129176e+07,52.115,532.661,85.018,17022.387,3.678936e+11
1120,Argentina,1988,ARG,3.178053e+07,52.500,541.383,89.062,17035.045,3.609212e+11
1121,Argentina,1989,ARG,3.227096e+07,50.863,522.113,90.189,16179.043,3.385208e+11
1122,Argentina,1990,ARG,3.275591e+07,51.005,513.625,86.305,15680.393,3.387511e+11
1123,Argentina,1991,ARG,3.323029e+07,53.854,522.459,87.280,15722.361,3.760579e+11
1124,Argentina,1992,ARG,3.369353e+07,56.107,560.339,86.826,16630.447,4.166798e+11
1125,Argentina,1993,ARG,3.415272e+07,61.869,578.831,84.698,16948.301,4.447803e+11
1126,Argentina,1994,ARG,3.461349e+07,65.622,611.176,83.661,17657.168,4.729268e+11
1127,Argentina,1995,ARG,3.507002e+07,67.169,630.652,85.032,17982.643,4.616010e+11
1128,Argentina,1996,ARG,3.551380e+07,69.760,659.104,87.189,18559.109,4.894065e+11
1129,Argentina,1997,ARG,3.594779e+07,72.462,668.982,84.886,18609.811,5.315264e+11
1130,Argentina,1998,ARG,3.637286e+07,74.170,694.257,86.215,19087.227,5.545671e+11
1131,Argentina,1999,ARG,3.679469e+07,80.745,705.548,88.579,19175.273,5.382706e+11
1132,Argentina,2000,ARG,3.721399e+07,88.980,703.635,85.985,18907.803,5.364810e+11
1133,Argentina,2001,ARG,3.762482e+07,90.140,687.341,82.098,18268.281,5.148673e+11
1134,Argentina,2002,ARG,3.802934e+07,84.590,658.151,82.217,17306.400,4.605585e+11
1135,Argentina,2003,ARG,3.842428e+07,92.070,704.758,83.435,18341.469,5.031042e+11
1136,Argentina,2004,ARG,3.881592e+07,100.260,751.157,85.674,19351.779,5.503063e+11
1137,Argentina,2005,ARG,3.921679e+07,105.750,796.367,85.629,20306.785,6.010504e+11
1138,Argentina,2006,ARG,3.962211e+07,113.430,836.059,84.832,21100.816,6.522968e+11
1139,Argentina,2007,ARG,4.001677e+07,113.520,869.076,87.741,21717.797,7.147252e+11
1140,Argentina,2008,ARG,4.042415e+07,121.910,879.072,87.894,21746.203,7.471574e+11
1141,Argentina,2009,ARG,4.085483e+07,122.320,852.154,86.267,20858.098,7.059208e+11
1142,Argentina,2010,ARG,4.128869e+07,126.000,882.268,86.765,21368.264,7.857852e+11
1143,Argentina,2011,ARG,4.173066e+07,129.490,907.376,87.749,21743.625,8.377427e+11
1144,Argentina,2012,ARG,4.216172e+07,136.020,944.132,88.541,22393.107,8.291474e+11
1145,Argentina,2013,ARG,4.258245e+07,139.450,1009.449,88.284,23705.746,8.490884e+11
1146,Argentina,2014,ARG,4.302407e+07,138.540,993.008,88.183,23080.285,8.277508e+11
1147,Argentina,2015,ARG,4.347701e+07,145.420,1009.992,87.950,23230.486,8.503566e+11
1148,Argentina,2016,ARG,4.390031e+07,147.180,1005.722,88.332,22909.215,8.326693e+11
1149,Argentina,2017,ARG,4.428890e+07,145.610,996.988,88.019,22511.016,8.561422e+11
1150,Argentina,2018,ARG,4.465488e+07,146.780,986.055,87.432,22081.684,8.337370e+11
1151,Argentina,2019,ARG,4.497347e+07,139.530,925.658,86.311,20582.312,8.170539e+11
1152,Argentina,2020,ARG,4.519196e+07,144.640,863.972,85.285,19117.824,7.358143e+11
1153,Argentina,2021,ARG,4.531228e+07,153.150,948.187,86.394,20925.615,8.123242e+11
1154,Argentina,2022,ARG,4.540790e+07,145.610,1001.241,86.146,22049.938,8.549144e+11
1155,Argentina,2023,ARG,4.553840e+07,148.560,1004.261,83.705,22053.053,NaN
1156,Argentina,2024,ARG,4.569615e+07,152.510,983.105,82.583,21513.947,NaN
1668,Australia,1965,AUS,1.135748e+07,NaN,425.760,94.748,37487.191,1.851121e+11
1669,Australia,1966,AUS,1.159248e+07,NaN,446.102,95.213,38481.957,1.902576e+11
1670,Australia,1967,AUS,1.181052e+07,NaN,473.093,95.329,40056.914,2.031107e+11
1671,Australia,1968,AUS,1.203001e+07,NaN,501.694,95.409,41703.523,2.150465e+11
1672,Australia,1969,AUS,1.227239e+07,NaN,522.428,95.200,42569.410,2.281273e+11
1673,Australia,1970,AUS,1.259941e+07,NaN,570.102,94.885,45248.266,2.426446e+11
1674,Australia,1971,AUS,1.299796e+07,NaN,598.808,94.506,46069.344,2.534398e+11
1675,Australia,1972,AUS,1.330490e+07,NaN,626.095,94.717,47057.488,2.605356e+11
1676,Australia,1973,AUS,1.351869e+07,NaN,669.356,94.726,49513.375,2.746595e+11
1677,Australia,1974,AUS,1.371950e+07,NaN,711.901,94.378,51889.727,2.814742e+11
1678,Australia,1975,AUS,1.389399e+07,NaN,723.900,94.054,52101.688,2.891030e+11
1679,Australia,1976,AUS,1.404676e+07,NaN,749.088,94.531,53328.191,3.007557e+11
1680,Australia,1977,AUS,1.420351e+07,NaN,785.969,95.027,55336.211,3.038880e+11
1681,Australia,1978,AUS,1.436710e+07,NaN,811.221,94.802,56463.793,3.127283e+11
1682,Australia,1979,AUS,1.453303e+07,NaN,841.291,95.126,57888.219,3.291943e+11
1683,Australia,1980,AUS,1.472134e+07,NaN,844.247,95.413,57348.492,3.357565e+11
1684,Australia,1981,AUS,1.494921e+07,NaN,857.794,95.349,57380.551,3.487267e+11
1685,Australia,1982,AUS,1.519248e+07,NaN,849.919,95.625,55943.414,3.483015e+11
1686,Australia,1983,AUS,1.541489e+07,NaN,841.572,95.827,54594.711,3.483536e+11
1687,Australia,1984,AUS,1.562065e+07,NaN,871.355,95.646,55782.266,3.723796e+11
1688,Australia,1985,AUS,1.583574e+07,123.673,896.293,95.508,56599.375,3.912293e+11
1689,Australia,1986,AUS,1.606963e+07,129.527,912.411,95.560,56778.605,3.993444e+11
1690,Australia,1987,AUS,1.632227e+07,135.815,937.538,95.799,57439.195,4.190940e+11
1691,Australia,1988,AUS,1.659410e+07,143.374,981.314,95.698,59136.320,4.379128e+11
1692,Australia,1989,AUS,1.686936e+07,151.433,1029.713,95.899,61040.418,4.571762e+11
1693,Australia,1990,AUS,1.712630e+07,155.654,1051.079,95.863,61372.223,4.641366e+11
1694,Australia,1991,AUS,1.735319e+07,157.964,1043.940,95.606,60158.379,4.613021e+11
1695,Australia,1992,AUS,1.754929e+07,161.400,1060.420,95.611,60425.266,4.786337e+11
1696,Australia,1993,AUS,1.772290e+07,165.383,1084.443,95.593,61188.770,5.015248e+11
1697,Australia,1994,AUS,1.789743e+07,170.143,1125.552,95.804,62888.992,5.279932e+11
1698,Australia,1995,AUS,1.809534e+07,175.225,1154.299,95.998,63789.848,5.490387e+11
1699,Australia,1996,AUS,1.830530e+07,180.127,1188.137,96.000,64906.695,5.747656e+11
1700,Australia,1997,AUS,1.850491e+07,188.980,1217.288,96.086,65781.891,6.014728e+11
1701,Australia,1998,AUS,1.870171e+07,199.471,1246.330,96.187,66642.594,6.348471e+11
1702,Australia,1999,AUS,1.890998e+07,206.900,1297.347,96.214,68606.484,6.645207e+11
1703,Australia,2000,AUS,1.913247e+07,216.830,1305.260,96.235,68222.211,6.920593e+11
1704,Australia,2001,AUS,1.936544e+07,224.260,1315.385,96.345,67924.375,7.138901e+11
1705,Australia,2002,AUS,1.959536e+07,223.490,1341.745,96.289,68472.609,7.470657e+11
1706,Australia,2003,AUS,1.981945e+07,225.950,1360.862,96.203,68662.977,7.744510e+11
1707,Australia,2004,AUS,2.004668e+07,229.230,1404.444,96.171,70058.688,8.097924e+11
1708,Australia,2005,AUS,2.029449e+07,230.740,1410.350,95.905,69494.242,8.400924e+11
1709,Australia,2006,AUS,2.059057e+07,237.990,1470.838,95.976,71432.609,8.666787e+11
1710,Australia,2007,AUS,2.095454e+07,243.190,1506.167,96.214,71877.820,9.112507e+11
1711,Australia,2008,AUS,2.137060e+07,245.380,1531.745,96.501,71675.375,9.378896e+11
1712,Australia,2009,AUS,2.178301e+07,249.900,1509.545,96.278,69299.156,9.631299e+11
1713,Australia,2010,AUS,2.214158e+07,250.970,1508.838,95.912,68144.984,9.938540e+11
1714,Australia,2011,AUS,2.247978e+07,256.280,1558.602,94.608,69333.531,1.024000e+12
1715,Australia,2012,AUS,2.285265e+07,250.660,1536.113,94.600,67218.164,1.062663e+12
1716,Australia,2013,AUS,2.323627e+07,249.560,1555.586,93.827,66946.461,1.086068e+12
1717,Australia,2014,AUS,2.359560e+07,247.650,1566.458,94.337,66387.727,1.113888e+12
1718,Australia,2015,AUS,2.394800e+07,253.990,1601.626,94.045,66879.320,1.139303e+12
1719,Australia,2016,AUS,2.432996e+07,258.230,1606.889,93.215,66045.680,1.169967e+12
1720,Australia,2017,AUS,2.473104e+07,258.970,1602.028,93.627,64778.020,1.197833e+12
1721,Australia,2018,AUS,2.511970e+07,262.630,1625.908,92.152,64726.418,1.231577e+12
1722,Australia,2019,AUS,2.548271e+07,265.900,1680.293,91.593,65938.531,1.255506e+12
1723,Australia,2020,AUS,2.574379e+07,265.150,1585.412,89.708,61584.258,1.232260e+12
1724,Australia,2021,AUS,2.595642e+07,267.450,1589.323,87.717,61230.445,1.296705e+12
1725,Australia,2022,AUS,2.620099e+07,272.920,1660.790,86.753,63386.535,1.344251e+12
1726,Australia,2023,AUS,2.645113e+07,273.110,1657.377,85.677,62658.078,NaN
1727,Australia,2024,AUS,2.671321e+07,281.640,1672.114,85.267,62595.039,NaN
1838,Austria,1965,AUT,7.270413e+06,NaN,189.498,76.060,26064.307,8.963552e+10
1839,Austria,1966,AUT,7.321524e+06,NaN,198.325,75.340,27087.949,9.467431e+10
1840,Austria,1967,AUT,7.376293e+06,NaN,200.363,75.069,27163.170,9.756080e+10
1841,Austria,1968,AUT,7.414627e+06,NaN,214.242,76.058,28894.449,1.019025e+11
1842,Austria,1969,AUT,7.440306e+06,NaN,221.926,78.788,29827.604,1.083046e+11
1843,Austria,1970,AUT,7.466320e+06,NaN,254.149,76.376,34039.426,1.160161e+11
1844,Austria,1971,AUT,7.499635e+06,NaN,253.084,81.316,33746.195,1.219503e+11
1845,Austria,1972,AUT,7.543263e+06,NaN,261.826,81.440,34709.883,1.295264e+11
1846,Austria,1973,AUT,7.585107e+06,NaN,281.510,80.811,37113.535,1.358522e+11
1847,Austria,1974,AUT,7.597963e+06,NaN,282.962,77.379,37241.844,1.412129e+11
1848,Austria,1975,AUT,7.577833e+06,NaN,281.064,76.121,37090.230,1.406948e+11
1849,Austria,1976,AUT,7.564457e+06,NaN,290.894,80.110,38455.332,1.471343e+11
1850,Austria,1977,AUT,7.567332e+06,NaN,291.598,75.891,38533.754,1.540176e+11
1851,Austria,1978,AUT,7.561203e+06,NaN,304.190,76.885,40230.348,1.534619e+11
1852,Austria,1979,AUT,7.548345e+06,NaN,322.217,75.394,42687.133,1.618295e+11
1853,Austria,1980,AUT,7.548407e+06,NaN,320.874,74.383,42508.809,1.655742e+11
1854,Austria,1981,AUT,7.567550e+06,NaN,311.520,71.997,41165.254,1.654082e+11
1855,Austria,1982,AUT,7.573078e+06,NaN,301.322,70.985,39788.531,1.685654e+11
1856,Austria,1983,AUT,7.561166e+06,NaN,300.495,71.182,39741.906,1.732936e+11
1857,Austria,1984,AUT,7.560715e+06,NaN,297.469,74.516,39343.980,1.738659e+11
1858,Austria,1985,AUT,7.564310e+06,43.742,315.806,71.494,41749.422,1.777606e+11
1859,Austria,1986,AUT,7.569397e+06,43.977,316.435,71.086,41804.465,1.819330e+11
1860,Austria,1987,AUT,7.574314e+06,49.688,334.019,69.131,44098.918,1.849934e+11
1861,Austria,1988,AUT,7.585346e+06,48.149,329.132,68.600,43390.504,1.908460e+11
1862,Austria,1989,AUT,7.620405e+06,49.155,330.973,68.916,43432.500,1.989194e+11
1863,Austria,1990,AUT,7.679627e+06,49.270,333.824,72.236,43468.785,2.079791e+11
1864,Austria,1991,AUT,7.757140e+06,50.160,349.400,73.472,45042.395,2.159927e+11
1865,Austria,1992,AUT,7.842715e+06,49.890,344.792,70.172,43963.363,2.214009e+11
1866,Austria,1993,AUT,7.907492e+06,51.310,352.443,69.282,44570.805,2.234629e+11
1867,Austria,1994,AUT,7.938157e+06,51.950,349.408,69.972,44016.273,2.297493e+11
1868,Austria,1995,AUT,7.950322e+06,55.050,367.661,69.860,46244.852,2.368245e+11
1869,Austria,1996,AUT,7.960917e+06,53.450,375.696,72.926,47192.613,2.434807e+11
1870,Austria,1997,AUT,7.969804e+06,55.590,380.569,71.736,47751.309,2.498473e+11
1871,Austria,1998,AUT,7.978465e+06,55.820,389.247,71.468,48787.238,2.597763e+11
1872,Austria,1999,AUT,7.993894e+06,59.720,392.804,69.332,49137.969,2.701862e+11
1873,Austria,2000,AUT,8.012929e+06,59.640,395.171,68.732,49316.637,2.804102e+11
1874,Austria,2001,AUT,8.042233e+06,60.980,406.593,70.589,50557.285,2.853357e+11
1875,Austria,2002,AUT,8.081640e+06,60.630,406.828,71.077,50339.801,2.912314e+11
1876,Austria,2003,AUT,8.122604e+06,57.970,407.704,75.879,50193.703,2.944893e+11
1877,Austria,2004,AUT,8.173496e+06,61.850,422.457,73.881,51686.262,3.036925e+11
1878,Austria,2005,AUT,8.229204e+06,64.370,431.350,73.683,52416.992,3.114411e+11
1879,Austria,2006,AUT,8.269901e+06,62.210,425.865,73.010,51495.746,3.232369e+11
1880,Austria,2007,AUT,8.296948e+06,62.830,420.066,70.906,50628.930,3.363040e+11
1881,Austria,2008,AUT,8.323250e+06,64.380,424.560,70.423,51008.945,3.428925e+11
1882,Austria,2009,AUT,8.345073e+06,66.210,409.772,67.452,49103.516,3.311190e+11
1883,Austria,2010,AUT,8.365087e+06,67.820,421.558,69.887,50394.973,3.388322e+11
1884,Austria,2011,AUT,8.393272e+06,62.200,395.869,70.842,47165.023,3.497135e+11
1885,Austria,2012,AUT,8.431599e+06,68.650,414.402,65.502,49148.723,3.520931e+11
1886,Austria,2013,AUT,8.481411e+06,64.550,410.852,65.976,48441.508,3.521829e+11
1887,Austria,2014,AUT,8.547812e+06,61.550,394.889,64.983,46197.699,3.545118e+11
1888,Austria,2015,AUT,8.644037e+06,61.780,396.383,66.948,45856.262,3.581083e+11
1889,Austria,2016,AUT,8.737920e+06,64.870,409.651,65.974,46881.992,3.652327e+11
1890,Austria,2017,AUT,8.798779e+06,67.090,417.569,66.787,47457.570,3.734817e+11
1891,Austria,2018,AUT,8.841653e+06,64.670,408.402,66.861,46190.699,3.825400e+11
1892,Austria,2019,AUT,8.880876e+06,70.690,427.960,65.811,48188.984,3.883447e+11
1893,Austria,2020,AUT,8.921402e+06,69.030,400.144,63.120,44852.156,3.632811e+11
1894,Austria,2021,AUT,8.967053e+06,66.670,406.335,65.362,45314.195,3.798352e+11
1895,Austria,2022,AUT,9.064678e+06,64.470,381.823,64.866,42122.105,3.988154e+11
1896,Austria,2023,AUT,9.130434e+06,70.980,393.960,59.978,43148.035,NaN
1897,Austria,2024,AUT,9.120815e+06,78.470,412.337,56.653,45208.309,NaN
1899,Azerbaijan,1985,AZE,6.799823e+06,20.702,234.951,98.447,34552.445,5.718188e+10
1900,Azerbaijan,1986,AZE,6.891349e+06,21.542,252.834,99.116,36688.668,5.870459e+10
1901,Azerbaijan,1987,AZE,6.977658e+06,22.909,245.023,99.088,35115.332,6.183143e+10
1902,Azerbaijan,1988,AZE,7.081404e+06,23.572,245.204,99.209,34626.512,6.507024e+10
1903,Azerbaijan,1989,AZE,7.167583e+06,23.300,250.052,99.224,34886.496,5.980371e+10
1904,Azerbaijan,1990,AZE,7.231084e+06,23.152,260.551,98.230,36032.113,5.323560e+10
1905,Azerbaijan,1991,AZE,7.314317e+06,23.449,250.351,98.046,34227.562,5.342662e+10
1906,Azerbaijan,1992,AZE,7.405781e+06,19.763,214.394,97.733,28949.521,4.179530e+10

In [21]:
clean_data=new_data[new_data["year"]>1994]
clean_data=new_data[new_data["year"]<2016]
clean_data.head(1000)

,country,year,iso_code,population,electricity_generation,primary_energy_consumption,fossil_share_energy,energy_per_capita,gdp
713,Algeria,1965,DZA,1.236598e+07,NaN,24.833,95.513,2008.143,3.566197e+10
714,Algeria,1966,DZA,1.259007e+07,NaN,29.833,96.687,2369.529,3.393263e+10
715,Algeria,1967,DZA,1.287612e+07,NaN,28.247,95.958,2193.783,3.709477e+10
716,Algeria,1968,DZA,1.317262e+07,NaN,30.345,94.829,2303.642,4.142389e+10
717,Algeria,1969,DZA,1.347596e+07,NaN,33.539,97.004,2488.817,4.538746e+10
718,Algeria,1970,DZA,1.378372e+07,NaN,36.759,95.605,2666.834,4.994567e+10
719,Algeria,1971,DZA,1.409894e+07,NaN,39.733,97.689,2818.145,4.570122e+10
720,Algeria,1972,DZA,1.442708e+07,NaN,44.648,96.914,3094.726,5.529391e+10
721,Algeria,1973,DZA,1.477115e+07,NaN,53.251,96.067,3605.046,5.709785e+10
722,Algeria,1974,DZA,1.513351e+07,NaN,58.909,97.653,3892.616,6.057788e+10
723,Algeria,1975,DZA,1.567860e+07,NaN,70.370,98.704,4488.262,6.488381e+10
724,Algeria,1976,DZA,1.640917e+07,NaN,82.102,98.683,5003.428,6.915010e+10
725,Algeria,1977,DZA,1.701599e+07,NaN,90.213,99.171,5301.638,7.543804e+10
726,Algeria,1978,DZA,1.750698e+07,NaN,113.361,99.387,6475.217,8.510391e+10
727,Algeria,1979,DZA,1.803666e+07,NaN,148.540,99.456,8235.463,9.275389e+10
728,Algeria,1980,DZA,1.860718e+07,NaN,177.143,99.597,9520.142,9.448165e+10
729,Algeria,1981,DZA,1.922071e+07,NaN,215.186,99.527,11195.538,9.686051e+10
730,Algeria,1982,DZA,1.987235e+07,NaN,248.112,99.464,12485.292,1.030737e+11
731,Algeria,1983,DZA,2.055812e+07,NaN,270.967,99.759,13180.519,1.084304e+11
732,Algeria,1984,DZA,2.127197e+07,NaN,260.196,99.517,12231.881,1.144067e+11
733,Algeria,1985,DZA,2.200854e+07,12.274,262.297,99.316,11917.944,1.203642e+11
734,Algeria,1986,DZA,2.274550e+07,12.981,277.491,99.750,12199.799,1.191450e+11
735,Algeria,1987,DZA,2.344363e+07,12.722,285.168,99.514,12163.992,1.183212e+11
736,Algeria,1988,DZA,2.410954e+07,13.966,305.422,99.834,12668.091,1.158217e+11
737,Algeria,1989,DZA,2.475449e+07,15.324,297.068,99.789,12000.583,1.197624e+11
738,Algeria,1990,DZA,2.537582e+07,16.104,314.974,99.881,12412.359,1.178432e+11
739,Algeria,1991,DZA,2.598794e+07,17.345,312.095,99.739,12009.229,1.211051e+11
740,Algeria,1992,DZA,2.662857e+07,18.286,320.227,99.827,12025.688,1.279827e+11
741,Algeria,1993,DZA,2.727704e+07,19.414,297.995,99.671,10924.754,1.302758e+11
742,Algeria,1994,DZA,2.788728e+07,19.883,301.921,99.847,10826.482,1.342799e+11
743,Algeria,1995,DZA,2.847019e+07,19.715,313.145,99.829,10999.042,1.450547e+11
744,Algeria,1996,DZA,2.903304e+07,20.654,309.925,99.879,10674.896,1.565791e+11
745,Algeria,1997,DZA,2.957930e+07,21.497,297.860,99.930,10069.873,1.646445e+11
746,Algeria,1998,DZA,3.005414e+07,23.262,308.349,99.806,10259.786,1.799629e+11
747,Algeria,1999,DZA,3.047436e+07,24.757,311.434,99.819,10219.548,1.931798e+11
748,Algeria,2000,DZA,3.090389e+07,25.400,299.946,99.950,9705.756,2.085542e+11
749,Algeria,2001,DZA,3.133123e+07,26.620,310.813,99.939,9920.229,2.234203e+11
750,Algeria,2002,DZA,3.175083e+07,27.650,321.951,99.951,10139.907,2.453609e+11
751,Algeria,2003,DZA,3.217581e+07,29.570,336.922,99.786,10471.285,2.735686e+11
752,Algeria,2004,DZA,3.262829e+07,31.250,349.778,99.806,10720.079,2.967736e+11
753,Algeria,2005,DZA,3.310926e+07,33.910,366.272,99.592,11062.512,3.268545e+11
754,Algeria,2006,DZA,3.362350e+07,35.230,379.220,99.847,11278.422,3.457053e+11
755,Algeria,2007,DZA,3.418942e+07,37.190,399.640,99.850,11688.989,3.716653e+11
756,Algeria,2008,DZA,3.481696e+07,40.230,423.557,99.824,12165.246,3.956585e+11
757,Algeria,2009,DZA,3.549044e+07,38.500,448.859,99.800,12647.330,4.182477e+11
758,Algeria,2010,DZA,3.618824e+07,45.730,438.995,99.892,12130.873,4.507058e+11
759,Algeria,2011,DZA,3.690337e+07,51.220,464.488,99.779,12586.607,4.820287e+11
760,Algeria,2012,DZA,3.764616e+07,57.400,507.672,99.789,13485.354,4.984176e+11
761,Algeria,2013,DZA,3.841418e+07,59.890,536.977,99.939,13978.610,5.123733e+11
762,Algeria,2014,DZA,3.920504e+07,64.270,585.613,99.890,14937.195,5.318435e+11
763,Algeria,2015,DZA,4.001953e+07,68.840,617.518,99.909,15430.422,5.515217e+11
1097,Argentina,1965,ARG,2.211263e+07,NaN,328.528,98.963,14857.010,2.262849e+11
1098,Argentina,1966,ARG,2.245390e+07,NaN,339.175,98.983,15105.385,2.278345e+11
1099,Argentina,1967,ARG,2.279906e+07,NaN,349.032,98.988,15309.062,2.339291e+11
1100,Argentina,1968,ARG,2.315058e+07,NaN,360.844,98.846,15586.842,2.438865e+11
1101,Argentina,1969,ARG,2.350872e+07,NaN,372.911,98.999,15862.656,2.647215e+11
1102,Argentina,1970,ARG,2.387833e+07,NaN,353.487,98.726,14803.654,2.788974e+11
1103,Argentina,1971,ARG,2.425721e+07,NaN,374.742,98.804,15448.672,2.924389e+11
1104,Argentina,1972,ARG,2.464433e+07,NaN,379.448,98.837,15396.966,3.015702e+11
1105,Argentina,1973,ARG,2.504601e+07,NaN,396.458,97.850,15829.181,3.199379e+11
1106,Argentina,1974,ARG,2.546135e+07,NaN,412.278,95.881,16192.301,3.406864e+11
1107,Argentina,1975,ARG,2.587411e+07,NaN,402.571,94.615,15558.845,3.376560e+11
1108,Argentina,1976,ARG,2.628228e+07,NaN,422.714,94.957,16083.609,3.368411e+11
1109,Argentina,1977,ARG,2.670182e+07,NaN,441.458,95.284,16532.896,3.571579e+11
1110,Argentina,1978,ARG,2.713216e+07,NaN,444.487,93.280,16382.302,3.414667e+11
1111,Argentina,1979,ARG,2.756889e+07,NaN,475.767,92.109,17257.400,3.659064e+11
1112,Argentina,1980,ARG,2.801160e+07,NaN,473.282,89.612,16895.920,3.710770e+11
1113,Argentina,1981,ARG,2.846396e+07,NaN,458.869,89.281,16121.061,3.497820e+11
1114,Argentina,1982,ARG,2.892427e+07,NaN,470.355,88.349,16261.604,3.387615e+11
1115,Argentina,1983,ARG,2.939133e+07,NaN,490.868,87.462,16701.121,3.507066e+11
1116,Argentina,1984,ARG,2.986309e+07,NaN,492.394,85.986,16488.375,3.578443e+11
1117,Argentina,1985,ARG,3.033645e+07,45.304,486.092,84.698,16023.380,3.341714e+11
1118,Argentina,1986,ARG,3.081198e+07,49.022,509.708,85.231,16542.523,3.586347e+11
1119,Argentina,1987,ARG,3.129176e+07,52.115,532.661,85.018,17022.387,3.678936e+11
1120,Argentina,1988,ARG,3.178053e+07,52.500,541.383,89.062,17035.045,3.609212e+11
1121,Argentina,1989,ARG,3.227096e+07,50.863,522.113,90.189,16179.043,3.385208e+11
1122,Argentina,1990,ARG,3.275591e+07,51.005,513.625,86.305,15680.393,3.387511e+11
1123,Argentina,1991,ARG,3.323029e+07,53.854,522.459,87.280,15722.361,3.760579e+11
1124,Argentina,1992,ARG,3.369353e+07,56.107,560.339,86.826,16630.447,4.166798e+11
1125,Argentina,1993,ARG,3.415272e+07,61.869,578.831,84.698,16948.301,4.447803e+11
1126,Argentina,1994,ARG,3.461349e+07,65.622,611.176,83.661,17657.168,4.729268e+11
1127,Argentina,1995,ARG,3.507002e+07,67.169,630.652,85.032,17982.643,4.616010e+11
1128,Argentina,1996,ARG,3.551380e+07,69.760,659.104,87.189,18559.109,4.894065e+11
1129,Argentina,1997,ARG,3.594779e+07,72.462,668.982,84.886,18609.811,5.315264e+11
1130,Argentina,1998,ARG,3.637286e+07,74.170,694.257,86.215,19087.227,5.545671e+11
1131,Argentina,1999,ARG,3.679469e+07,80.745,705.548,88.579,19175.273,5.382706e+11
1132,Argentina,2000,ARG,3.721399e+07,88.980,703.635,85.985,18907.803,5.364810e+11
1133,Argentina,2001,ARG,3.762482e+07,90.140,687.341,82.098,18268.281,5.148673e+11
1134,Argentina,2002,ARG,3.802934e+07,84.590,658.151,82.217,17306.400,4.605585e+11
1135,Argentina,2003,ARG,3.842428e+07,92.070,704.758,83.435,18341.469,5.031042e+11
1136,Argentina,2004,ARG,3.881592e+07,100.260,751.157,85.674,19351.779,5.503063e+11
1137,Argentina,2005,ARG,3.921679e+07,105.750,796.367,85.629,20306.785,6.010504e+11
1138,Argentina,2006,ARG,3.962211e+07,113.430,836.059,84.832,21100.816,6.522968e+11
1139,Argentina,2007,ARG,4.001677e+07,113.520,869.076,87.741,21717.797,7.147252e+11
1140,Argentina,2008,ARG,4.042415e+07,121.910,879.072,87.894,21746.203,7.471574e+11
1141,Argentina,2009,ARG,4.085483e+07,122.320,852.154,86.267,20858.098,7.059208e+11
1142,Argentina,2010,ARG,4.128869e+07,126.000,882.268,86.765,21368.264,7.857852e+11
1143,Argentina,2011,ARG,4.173066e+07,129.490,907.376,87.749,21743.625,8.377427e+11
1144,Argentina,2012,ARG,4.216172e+07,136.020,944.132,88.541,22393.107,8.291474e+11
1145,Argentina,2013,ARG,4.258245e+07,139.450,1009.449,88.284,23705.746,8.490884e+11
1146,Argentina,2014,ARG,4.302407e+07,138.540,993.008,88.183,23080.285,8.277508e+11
1147,Argentina,2015,ARG,4.347701e+07,145.420,1009.992,87.950,23230.486,8.503566e+11
1668,Australia,1965,AUS,1.135748e+07,NaN,425.760,94.748,37487.191,1.851121e+11
1669,Australia,1966,AUS,1.159248e+07,NaN,446.102,95.213,38481.957,1.902576e+11
1670,Australia,1967,AUS,1.181052e+07,NaN,473.093,95.329,40056.914,2.031107e+11
1671,Australia,1968,AUS,1.203001e+07,NaN,501.694,95.409,41703.523,2.150465e+11
1672,Australia,1969,AUS,1.227239e+07,NaN,522.428,95.200,42569.410,2.281273e+11
1673,Australia,1970,AUS,1.259941e+07,NaN,570.102,94.885,45248.266,2.426446e+11
1674,Australia,1971,AUS,1.299796e+07,NaN,598.808,94.506,46069.344,2.534398e+11
1675,Australia,1972,AUS,1.330490e+07,NaN,626.095,94.717,47057.488,2.605356e+11
1676,Australia,1973,AUS,1.351869e+07,NaN,669.356,94.726,49513.375,2.746595e+11
1677,Australia,1974,AUS,1.371950e+07,NaN,711.901,94.378,51889.727,2.814742e+11
1678,Australia,1975,AUS,1.389399e+07,NaN,723.900,94.054,52101.688,2.891030e+11
1679,Australia,1976,AUS,1.404676e+07,NaN,749.088,94.531,53328.191,3.007557e+11
1680,Australia,1977,AUS,1.420351e+07,NaN,785.969,95.027,55336.211,3.038880e+11
1681,Australia,1978,AUS,1.436710e+07,NaN,811.221,94.802,56463.793,3.127283e+11
1682,Australia,1979,AUS,1.453303e+07,NaN,841.291,95.126,57888.219,3.291943e+11
1683,Australia,1980,AUS,1.472134e+07,NaN,844.247,95.413,57348.492,3.357565e+11
1684,Australia,1981,AUS,1.494921e+07,NaN,857.794,95.349,57380.551,3.487267e+11
1685,Australia,1982,AUS,1.519248e+07,NaN,849.919,95.625,55943.414,3.483015e+11
1686,Australia,1983,AUS,1.541489e+07,NaN,841.572,95.827,54594.711,3.483536e+11
1687,Australia,1984,AUS,1.562065e+07,NaN,871.355,95.646,55782.266,3.723796e+11
1688,Australia,1985,AUS,1.583574e+07,123.673,896.293,95.508,56599.375,3.912293e+11
1689,Australia,1986,AUS,1.606963e+07,129.527,912.411,95.560,56778.605,3.993444e+11
1690,Australia,1987,AUS,1.632227e+07,135.815,937.538,95.799,57439.195,4.190940e+11
1691,Australia,1988,AUS,1.659410e+07,143.374,981.314,95.698,59136.320,4.379128e+11
1692,Australia,1989,AUS,1.686936e+07,151.433,1029.713,95.899,61040.418,4.571762e+11
1693,Australia,1990,AUS,1.712630e+07,155.654,1051.079,95.863,61372.223,4.641366e+11
1694,Australia,1991,AUS,1.735319e+07,157.964,1043.940,95.606,60158.379,4.613021e+11
1695,Australia,1992,AUS,1.754929e+07,161.400,1060.420,95.611,60425.266,4.786337e+11
1696,Australia,1993,AUS,1.772290e+07,165.383,1084.443,95.593,61188.770,5.015248e+11
1697,Australia,1994,AUS,1.789743e+07,170.143,1125.552,95.804,62888.992,5.279932e+11
1698,Australia,1995,AUS,1.809534e+07,175.225,1154.299,95.998,63789.848,5.490387e+11
1699,Australia,1996,AUS,1.830530e+07,180.127,1188.137,96.000,64906.695,5.747656e+11
1700,Australia,1997,AUS,1.850491e+07,188.980,1217.288,96.086,65781.891,6.014728e+11
1701,Australia,1998,AUS,1.870171e+07,199.471,1246.330,96.187,66642.594,6.348471e+11
1702,Australia,1999,AUS,1.890998e+07,206.900,1297.347,96.214,68606.484,6.645207e+11
1703,Australia,2000,AUS,1.913247e+07,216.830,1305.260,96.235,68222.211,6.920593e+11
1704,Australia,2001,AUS,1.936544e+07,224.260,1315.385,96.345,67924.375,7.138901e+11
1705,Australia,2002,AUS,1.959536e+07,223.490,1341.745,96.289,68472.609,7.470657e+11
1706,Australia,2003,AUS,1.981945e+07,225.950,1360.862,96.203,68662.977,7.744510e+11
1707,Australia,2004,AUS,2.004668e+07,229.230,1404.444,96.171,70058.688,8.097924e+11
1708,Australia,2005,AUS,2.029449e+07,230.740,1410.350,95.905,69494.242,8.400924e+11
1709,Australia,2006,AUS,2.059057e+07,237.990,1470.838,95.976,71432.609,8.666787e+11
1710,Australia,2007,AUS,2.095454e+07,243.190,1506.167,96.214,71877.820,9.112507e+11
1711,Australia,2008,AUS,2.137060e+07,245.380,1531.745,96.501,71675.375,9.378896e+11
1712,Australia,2009,AUS,2.178301e+07,249.900,1509.545,96.278,69299.156,9.631299e+11
1713,Australia,2010,AUS,2.214158e+07,250.970,1508.838,95.912,68144.984,9.938540e+11
1714,Australia,2011,AUS,2.247978e+07,256.280,1558.602,94.608,69333.531,1.024000e+12
1715,Australia,2012,AUS,2.285265e+07,250.660,1536.113,94.600,67218.164,1.062663e+12
1716,Australia,2013,AUS,2.323627e+07,249.560,1555.586,93.827,66946.461,1.086068e+12
1717,Australia,2014,AUS,2.359560e+07,247.650,1566.458,94.337,66387.727,1.113888e+12
1718,Australia,2015,AUS,2.394800e+07,253.990,1601.626,94.045,66879.320,1.139303e+12
1838,Austria,1965,AUT,7.270413e+06,NaN,189.498,76.060,26064.307,8.963552e+10
1839,Austria,1966,AUT,7.321524e+06,NaN,198.325,75.340,27087.949,9.467431e+10
1840,Austria,1967,AUT,7.376293e+06,NaN,200.363,75.069,27163.170,9.756080e+10
1841,Austria,1968,AUT,7.414627e+06,NaN,214.242,76.058,28894.449,1.019025e+11
1842,Austria,1969,AUT,7.440306e+06,NaN,221.926,78.788,29827.604,1.083046e+11
1843,Austria,1970,AUT,7.466320e+06,NaN,254.149,76.376,34039.426,1.160161e+11
1844,Austria,1971,AUT,7.499635e+06,NaN,253.084,81.316,33746.195,1.219503e+11
1845,Austria,1972,AUT,7.543263e+06,NaN,261.826,81.440,34709.883,1.295264e+11
1846,Austria,1973,AUT,7.585107e+06,NaN,281.510,80.811,37113.535,1.358522e+11
1847,Austria,1974,AUT,7.597963e+06,NaN,282.962,77.379,37241.844,1.412129e+11
1848,Austria,1975,AUT,7.577833e+06,NaN,281.064,76.121,37090.230,1.406948e+11
1849,Austria,1976,AUT,7.564457e+06,NaN,290.894,80.110,38455.332,1.471343e+11
1850,Austria,1977,AUT,7.567332e+06,NaN,291.598,75.891,38533.754,1.540176e+11
1851,Austria,1978,AUT,7.561203e+06,NaN,304.190,76.885,40230.348,1.534619e+11
1852,Austria,1979,AUT,7.548345e+06,NaN,322.217,75.394,42687.133,1.618295e+11
1853,Austria,1980,AUT,7.548407e+06,NaN,320.874,74.383,42508.809,1.655742e+11
1854,Austria,1981,AUT,7.567550e+06,NaN,311.520,71.997,41165.254,1.654082e+11
1855,Austria,1982,AUT,7.573078e+06,NaN,301.322,70.985,39788.531,1.685654e+11
1856,Austria,1983,AUT,7.561166e+06,NaN,300.495,71.182,39741.906,1.732936e+11
1857,Austria,1984,AUT,7.560715e+06,NaN,297.469,74.516,39343.980,1.738659e+11
1858,Austria,1985,AUT,7.564310e+06,43.742,315.806,71.494,41749.422,1.777606e+11
1859,Austria,1986,AUT,7.569397e+06,43.977,316.435,71.086,41804.465,1.819330e+11
1860,Austria,1987,AUT,7.574314e+06,49.688,334.019,69.131,44098.918,1.849934e+11
1861,Austria,1988,AUT,7.585346e+06,48.149,329.132,68.600,43390.504,1.908460e+11
1862,Austria,1989,AUT,7.620405e+06,49.155,330.973,68.916,43432.500,1.989194e+11
1863,Austria,1990,AUT,7.679627e+06,49.270,333.824,72.236,43468.785,2.079791e+11
1864,Austria,1991,AUT,7.757140e+06,50.160,349.400,73.472,45042.395,2.159927e+11
1865,Austria,1992,AUT,7.842715e+06,49.890,344.792,70.172,43963.363,2.214009e+11
1866,Austria,1993,AUT,7.907492e+06,51.310,352.443,69.282,44570.805,2.234629e+11
1867,Austria,1994,AUT,7.938157e+06,51.950,349.408,69.972,44016.273,2.297493e+11
1868,Austria,1995,AUT,7.950322e+06,55.050,367.661,69.860,46244.852,2.368245e+11
1869,Austria,1996,AUT,7.960917e+06,53.450,375.696,72.926,47192.613,2.434807e+11
1870,Austria,1997,AUT,7.969804e+06,55.590,380.569,71.736,47751.309,2.498473e+11
1871,Austria,1998,AUT,7.978465e+06,55.820,389.247,71.468,48787.238,2.597763e+11
1872,Austria,1999,AUT,7.993894e+06,59.720,392.804,69.332,49137.969,2.701862e+11
1873,Austria,2000,AUT,8.012929e+06,59.640,395.171,68.732,49316.637,2.804102e+11
1874,Austria,2001,AUT,8.042233e+06,60.980,406.593,70.589,50557.285,2.853357e+11
1875,Austria,2002,AUT,8.081640e+06,60.630,406.828,71.077,50339.801,2.912314e+11
1876,Austria,2003,AUT,8.122604e+06,57.970,407.704,75.879,50193.703,2.944893e+11
1877,Austria,2004,AUT,8.173496e+06,61.850,422.457,73.881,51686.262,3.036925e+11
1878,Austria,2005,AUT,8.229204e+06,64.370,431.350,73.683,52416.992,3.114411e+11
1879,Austria,2006,AUT,8.269901e+06,62.210,425.865,73.010,51495.746,3.232369e+11
1880,Austria,2007,AUT,8.296948e+06,62.830,420.066,70.906,50628.930,3.363040e+11
1881,Austria,2008,AUT,8.323250e+06,64.380,424.560,70.423,51008.945,3.428925e+11
1882,Austria,2009,AUT,8.345073e+06,66.210,409.772,67.452,49103.516,3.311190e+11
1883,Austria,2010,AUT,8.365087e+06,67.820,421.558,69.887,50394.973,3.388322e+11
1884,Austria,2011,AUT,8.393272e+06,62.200,395.869,70.842,47165.023,3.497135e+11
1885,Austria,2012,AUT,8.431599e+06,68.650,414.402,65.502,49148.723,3.520931e+11
1886,Austria,2013,AUT,8.481411e+06,64.550,410.852,65.976,48441.508,3.521829e+11
1887,Austria,2014,AUT,8.547812e+06,61.550,394.889,64.983,46197.699,3.545118e+11
1888,Austria,2015,AUT,8.644037e+06,61.780,396.383,66.948,45856.262,3.581083e+11
1899,Azerbaijan,1985,AZE,6.799823e+06,20.702,234.951,98.447,34552.445,5.718188e+10
1900,Azerbaijan,1986,AZE,6.891349e+06,21.542,252.834,99.116,36688.668,5.870459e+10
1901,Azerbaijan,1987,AZE,6.977658e+06,22.909,245.023,99.088,35115.332,6.183143e+10
1902,Azerbaijan,1988,AZE,7.081404e+06,23.572,245.204,99.209,34626.512,6.507024e+10
1903,Azerbaijan,1989,AZE,7.167583e+06,23.300,250.052,99.224,34886.496,5.980371e+10
1904,Azerbaijan,1990,AZE,7.231084e+06,23.152,260.551,98.230,36032.113,5.323560e+10
1905,Azerbaijan,1991,AZE,7.314317e+06,23.449,250.351,98.046,34227.562,5.342662e+10
1906,Azerbaijan,1992,AZE,7.405781e+06,19.763,214.394,97.733,28949.521,4.179530e+10
1907,Azerbaijan,1993,AZE,7.504119e+06,19.051,185.980,96.368,24783.752,3.248644e+10
1908,Azerbaijan,1994,AZE,7.608894e+06,17.571,170.865,97.019,22455.918,2.637210e+10
1909,Azerbaijan,1995,AZE,7.719283e+06,17.044,160.648,97.305,20811.258,2.318828e+10
1910,Azerbaijan,1996,AZE,7.830981e+06,17.085,131.741,96.752,16823.014,2.402638e+10
1911,Azerbaijan,1997,AZE,7.936220e+06,16.836,126.155,96.221,15896.062,2.643693e+10
1912,Azerbaijan,1998,AZE,8.025808e+06,17.995,126.645,95.709,15779.740,2.832846e+10
1913,Azerbaijan,1999,AZE,8.100472e+06,18.176,126.353,96.682,15598.277,3.189857e+10
1914,Azerbaijan,2000,AZE,8.174784e+06,18.680,132.055,96.767,16153.973,3.425571e+10
1915,Azerbaijan,2001,AZE,8.251776e+06,18.960,127.227,97.170,15418.192,3.686218e+10
1916,Azerbaijan,2002,AZE,8.326141e+06,18.680,125.609,95.581,15086.057,4.029522e+10
1917,Azerbaijan,2003,AZE,8.400528e+06,21.260,136.035,95.037,16193.649,4.499464e+10
1918,Azerbaijan,2004,AZE,8.489874e+06,21.720,153.898,95.134,18127.234,5.010748e+10
1919,Azerbaijan,2005,AZE,8.597248e+06,22.840,166.837,95.136,19405.906,6.401918e+10
1920,Azerbaijan,2006,AZE,8.711380e+06,24.510,164.092,95.886,18836.461,8.702641e+10
1921,Azerbaijan,2007,AZE,8.828313e+06,21.820,151.071,95.827,17112.117,1.099443e+11
1922,Azerbaijan,2008,AZE,8.942637e+06,21.620,151.163,96.094,16903.684,1.231300e+11
1923,Azerbaijan,2009,AZE,9.046336e+06,18.850,130.168,95.327,14389.062,1.360202e+11
1924,Azerbaijan,2010,AZE,9.146852e+06,18.670,128.439,92.979,14041.920,1.442966e+11
1925,Azerbaijan,2011,AZE,9.256156e+06,20.270,145.739,95.229,15745.113,1.459805e+11
1926,Azerbaijan,2012,AZE,9.376179e+06,22.970,150.091,96.867,16007.676,1.491964e+11
1927,Azerbaijan,2013,AZE,9.504417e+06,23.250,154.212,97.388,16225.271,1.579140e+11
1928,Azerbaijan,2014,AZE,9.631136e+06,24.630,157.241,97.712,16326.349,1.623324e+11
1929,Azerbaijan,2015,AZE,9.752859e+06,24.570,171.826,97.404,17618.029,1.640369e+11
2181,Bangladesh,1971,BGD,7.027676e+07,NaN,13.407,96.366,190.773,6.458577e+10
2182,Bangladesh,1972,BGD,7.164152e+07,NaN,15.191,96.793,212.036,5.703633e+10
2183,Bangladesh,1973,BGD,7.372230e+07,NaN,19.480,95.266,264.238,5.732709e+10
2184,Bangladesh,1974,BGD,7.583935e+07,NaN,20.747,96.740,273.559,6.503783e+10
2185,Bangladesh,1975,BGD,7.785435e+07,NaN,21.331,94.301,273.987,6.419658e+10
2186,Bangladesh,1976,BGD,7.985532e+07,NaN,24.893,94.468,311.726,6.708203e+10
2187,Bangladesh,1977,BGD,8.186727e+07,NaN,25.438,95.213,310.725,6.770429e+10
2188,Bangladesh,1978,BGD,8.388966e+07,NaN,27.024,94.781,322.137,7.270960e+10
2189,Bangladesh,1979,BGD,8.593507e+07,NaN,29.795,94.508,346.714,7.631288e+10
2190,Bangladesh,1980,BGD,8.801644e+07,NaN,34.750,95.326,394.817,7.694517e+10
2191,Bangladesh,1981,BGD,9.030310e+07,NaN,36.840,95.273,407.956,7.947432e+10
2192,Bangladesh,1982,BGD,9.281451e+07,NaN,40.641,96.417,437.877,8.049243e+10
2193,Bangladesh,1983,BGD,9.533516e+07,NaN,40.190,95.411,421.567,8.445620e+10

In [22]:
clean_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3646 entries, 713 to 22613
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   country                     3646 non-null   object
 1   year                        3646 non-null   int64
 2   iso_code                    3646 non-null   object
 3   population                  3646 non-null   float64
 4   electricity_generation      2372 non-null   float64
 5   primary_energy_consumption  3646 non-null   float64
 6   fossil_share_energy         3646 non-null   float64
 7   energy_per_capita           3646 non-null   float64
 8   gdp                         3619 non-null   float64
dtypes: float64(6), int64(1), object(2)
memory usage: 284.8+ KB

In [23]:
d1=clean_data.dropna()
d1.head()

,country,year,iso_code,population,electricity_generation,primary_energy_consumption,fossil_share_energy,energy_per_capita,gdp
733,Algeria,1985,DZA,22008542.0,12.274,262.297,99.316,11917.944,1.203642e+11
734,Algeria,1986,DZA,22745501.0,12.981,277.491,99.750,12199.799,1.191450e+11
735,Algeria,1987,DZA,23443627.0,12.722,285.168,99.514,12163.992,1.183212e+11
736,Algeria,1988,DZA,24109538.0,13.966,305.422,99.834,12668.091,1.158217e+11
737,Algeria,1989,DZA,24754488.0,15.324,297.068,99.789,12000.583,1.197624e+11

In [24]:
d1_inputs.info()

NameError: name 'd1_inputs' is not defined

In [ ]:
d1_inputs=pd.DataFrame(d1[["population","electricity_generation","primary_energy_consumption","fossil_share_energy","energy_per_capita"]])
d1_output=pd.DataFrame(d1[["gdp"]])

In [ ]:
# Import essential models and functions from sklearn
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

import numpy as np
import pandas as pd
import seaborn as sb
import matplotlib.pyplot as plt
sb.set()

# Split the Dataset into Train and Test
X_train, X_test, y_train, y_test = train_test_split(d1_inputs, d1_output, test_size = 0.25)

# Linear Regression using Train Data
linreg = LinearRegression()         # create the linear regression object
linreg.fit(X_train, y_train)        # train the linear regression model

# Coefficients of the Linear Regression line
print('Intercept of Regression \t: b = ', linreg.intercept_)
print('Coefficients of Regression \t: a = ', linreg.coef_)
print()

# Print the Coefficients against Predictors
print(pd.DataFrame(list(zip(X_train.columns, linreg.coef_[0])), columns = ["Predictors", "Coefficients"]))
print()

# Predict Response corresponding to Predictors
y_train_pred = linreg.predict(X_train)
y_test_pred = linreg.predict(X_test)

# Plot the Predictions vs the True values
f, axes = plt.subplots(1, 2, figsize=(24, 12))
axes[0].scatter(y_train, y_train_pred, color = "blue")
axes[0].plot(y_train, y_train, 'w-', linewidth = 1)
axes[0].set_xlabel("True values of the Response Variable (Train)")
axes[0].set_ylabel("Predicted values of the Response Variable (Train)")
axes[1].scatter(y_test, y_test_pred, color = "green")
axes[1].plot(y_test, y_test, 'w-', linewidth = 1)
axes[1].set_xlabel("True values of the Response Variable (Test)")
axes[1].set_ylabel("Predicted values of the Response Variable (Test)")
plt.show()

# Check the Goodness of Fit (on Train Data)
print("Goodness of Fit of Model \tTrain Dataset")
print("Explained Variance (R^2) \t:", linreg.score(X_train, y_train))
print("Mean Squared Error (MSE) \t:", mean_squared_error(y_train, y_train_pred))
print()

# Check the Goodness of Fit (on Test Data)
print("Goodness of Fit of Model \tTest Dataset")
print("Explained Variance (R^2) \t:", linreg.score(X_test, y_test))
print("Mean Squared Error (MSE) \t:", mean_squared_error(y_test, y_test_pred))
print()

In [ ]:
len(d1["country"].unique())

In [ ]:
Algeria=pd.DataFrame(d1[d1["country"]=="Algeria"])

alg_inputs=pd.DataFrame(Algeria[["population","electricity_generation","primary_energy_consumption","fossil_share_energy","energy_per_capita"]])
alg_output=pd.DataFrame(Algeria[["gdp"]])

In [ ]:
# Import essential models and functions from sklearn
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

import numpy as np
import pandas as pd
import seaborn as sb
import matplotlib.pyplot as plt
sb.set()
Algeria = pd.DataFrame(d1[d1["country"] == "Algeria"])

# Just the column names now — plain lists, not DataFrames
feature_cols = ["population", "electricity_generation", "primary_energy_consumption", 
                "fossil_share_energy", "energy_per_capita"]
target_col = "gdp"

train_df = Algeria[Algeria["year"] < 2010]
test_df  = Algeria[(Algeria["year"] >= 2010) & (Algeria["year"] <= 2015)]

X_train = train_df[feature_cols]
y_train = train_df[target_col]
X_test  = test_df[feature_cols]
y_test  = test_df[target_col]

print(X_train.shape, X_test.shape)

# Linear Regression using Train Data
linreg = LinearRegression()         # create the linear regression object
linreg.fit(X_train, y_train)        # train the linear regression model

# Coefficients of the Linear Regression line
print('Intercept of Regression \t: b = ', linreg.intercept_)
print('Coefficients of Regression \t: a = ', linreg.coef_)
print()

# Print the Coefficients against Predictors
print(pd.DataFrame(list(zip(X_train.columns, linreg.coef_)), columns = ["Predictors", "Coefficients"]))
print()

# Predict Response corresponding to Predictors
y_train_pred = linreg.predict(X_train)
y_test_pred = linreg.predict(X_test)

# Plot the Predictions vs the True values
f, axes = plt.subplots(1, 2, figsize=(24, 12))
axes[0].scatter(y_train, y_train_pred, color = "blue")
axes[0].plot(y_train, y_train, 'w-', linewidth = 1)
axes[0].set_xlabel("True values of the Response Variable (Train)")
axes[0].set_ylabel("Predicted values of the Response Variable (Train)")
axes[1].scatter(y_test, y_test_pred, color = "green")
axes[1].plot(y_test, y_test, 'w-', linewidth = 1)
axes[1].set_xlabel("True values of the Response Variable (Test)")
axes[1].set_ylabel("Predicted values of the Response Variable (Test)")
plt.show()

# Check the Goodness of Fit (on Train Data)
print("Goodness of Fit of Model \tTrain Dataset")
print("Explained Variance (R^2) \t:", linreg.score(X_train, y_train))
print("Mean Squared Error (MSE) \t:", mean_squared_error(y_train, y_train_pred))
print()

# Check the Goodness of Fit (on Test Data)
print("Goodness of Fit of Model \tTest Dataset")
print("Explained Variance (R^2) \t:", linreg.score(X_test, y_test))
print("Mean Squared Error (MSE) \t:", mean_squared_error(y_test, y_test_pred))
print()

In [ ]:
# Import essential models and functions from sklearn
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

import numpy as np
import pandas as pd
import seaborn as sb
import matplotlib.pyplot as plt
sb.set()
Algeria = pd.DataFrame(d1[d1["country"] == "Algeria"])

# Just the column names now — plain lists, not DataFrames
feature_cols = ["population", "electricity_generation", "primary_energy_consumption", 
                "fossil_share_energy", "energy_per_capita"]
target_col = "gdp"

train_df = d1[d1["year"] < 2010]
test_df  = d1[(d1["year"] >= 2010) & (d1["year"] <= 2015)]

X_train = train_df[feature_cols]
y_train = train_df[target_col]
X_test  = test_df[feature_cols]
y_test  = test_df[target_col]

print(X_train.shape, X_test.shape)

# Linear Regression using Train Data
linreg = LinearRegression()         # create the linear regression object
linreg.fit(X_train, y_train)        # train the linear regression model

# Coefficients of the Linear Regression line
print('Intercept of Regression \t: b = ', linreg.intercept_)
print('Coefficients of Regression \t: a = ', linreg.coef_)
print()

# Print the Coefficients against Predictors
print(pd.DataFrame(list(zip(X_train.columns, linreg.coef_)), columns = ["Predictors", "Coefficients"]))
print()

# Predict Response corresponding to Predictors
y_train_pred = linreg.predict(X_train)
y_test_pred = linreg.predict(X_test)

# Plot the Predictions vs the True values
f, axes = plt.subplots(1, 2, figsize=(24, 12))
axes[0].scatter(y_train, y_train_pred, color = "blue")
axes[0].plot(y_train, y_train, 'w-', linewidth = 1)
axes[0].set_xlabel("True values of the Response Variable (Train)")
axes[0].set_ylabel("Predicted values of the Response Variable (Train)")
axes[1].scatter(y_test, y_test_pred, color = "green")
axes[1].plot(y_test, y_test, 'w-', linewidth = 1)
axes[1].set_xlabel("True values of the Response Variable (Test)")
axes[1].set_ylabel("Predicted values of the Response Variable (Test)")
plt.show()

# Check the Goodness of Fit (on Train Data)
print("Goodness of Fit of Model \tTrain Dataset")
print("Explained Variance (R^2) \t:", linreg.score(X_train, y_train))
print("Mean Squared Error (MSE) \t:", mean_squared_error(y_train, y_train_pred))
print()

# Check the Goodness of Fit (on Test Data)
print("Goodness of Fit of Model \tTest Dataset")
print("Explained Variance (R^2) \t:", linreg.score(X_test, y_test))
print("Mean Squared Error (MSE) \t:", mean_squared_error(y_test, y_test_pred))
print()

In [ ]:
data_s.info()