In [31]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (accuracy_score, precision_score, recall_score,
                              f1_score, confusion_matrix, ConfusionMatrixDisplay)
import matplotlib.pyplot as plt
from sklearn.model_selection import cross_val_score, StratifiedKFold
from statsmodels.stats.outliers_influence import variance_inflation_factor
from statsmodels.tools.tools import add_constant
import seaborn as sns

data_s=pd.read_csv('owid-energy-data.csv')
pd.set_option('display.max_info_columns', 200)

data_s.info()
np.random.seed(42)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23377 entries, 0 to 23376
Data columns (total 130 columns):
 #    Column                                        Non-Null Count  Dtype
---   ------                                        --------------  -----
 0    country                                       23377 non-null  object
 1    year                                          23377 non-null  int64
 2    iso_code                                      17265 non-null  object
 3    population                                    18894 non-null  float64
 4    gdp                                           11780 non-null  float64
 5    biofuel_cons_change_pct                       2070 non-null   float64
 6    biofuel_cons_change_twh                       7903 non-null   float64
 7    biofuel_cons_per_capita                       6338 non-null   float64
 8    biofuel_consumption                           8057 non-null   float64
 9    biofuel_elec_per_capita                       6015 non-null   float64
 10   biofuel_electricity                           6337 non-null   float64
 11   biofuel_share_elec                            6311 non-null   float64
 12   biofuel_share_energy                          6379 non-null   float64
 13   carbon_intensity_elec                         6332 non-null   float64
 14   coal_cons_change_pct                          5827 non-null   float64
 15   coal_cons_change_twh                          6293 non-null   float64
 16   coal_cons_per_capita                          5145 non-null   float64
 17   coal_consumption                              6405 non-null   float64
 18   coal_elec_per_capita                          6486 non-null   float64
 19   coal_electricity                              7168 non-null   float64
 20   coal_prod_change_pct                          9922 non-null   float64
 21   coal_prod_change_twh                          16562 non-null  float64
 22   coal_prod_per_capita                          14808 non-null  float64
 23   coal_production                               16822 non-null  float64
 24   coal_share_elec                               7142 non-null   float64
 25   coal_share_energy                             6379 non-null   float64
 26   electricity_demand                            6378 non-null   float64
 27   electricity_demand_per_capita                 6056 non-null   float64
 28   electricity_generation                        7913 non-null   float64
 29   electricity_share_energy                      4103 non-null   float64
 30   energy_cons_change_pct                        12745 non-null  float64
 31   energy_cons_change_twh                        12978 non-null  float64
 32   energy_per_capita                             11086 non-null  float64
 33   energy_per_gdp                                7882 non-null   float64
 34   fossil_cons_change_pct                        6267 non-null   float64
 35   fossil_cons_change_twh                        6293 non-null   float64
 36   fossil_elec_per_capita                        6526 non-null   float64
 37   fossil_electricity                            7208 non-null   float64
 38   fossil_energy_per_capita                      5145 non-null   float64
 39   fossil_fuel_consumption                       6405 non-null   float64
 40   fossil_share_elec                             7182 non-null   float64
 41   fossil_share_energy                           6379 non-null   float64
 42   gas_cons_change_pct                           5643 non-null   float64
 43   gas_cons_change_twh                           6293 non-null   float64
 44   gas_consumption                               6405 non-null   float64
 45   gas_elec_per_capita                           6343 non-null   float64
 46   gas_electricity                               7025 non-null   float64
 47   gas_energy_per_capita                         5145 non-null   float64
 48   gas_prod_change_pct                           8103 non-null   float64
 49   gas_prod_change_twh                           16990 non-null  float64
 50   gas_prod_per_capita                           15028 non-null  float64
 51   gas_production                                17251 non-null  float64
 52   gas_share_elec                                6999 non-null   float64
 53   gas_share_energy                              6379 non-null   float64
 54   greenhouse_gas_emissions                      6028 non-null   float64
 55   hydro_cons_change_pct                         5686 non-null   float64
 56   hydro_cons_change_twh                         6293 non-null   float64
 57   hydro_consumption                             6405 non-null   float64
 58   hydro_elec_per_capita                         8501 non-null   float64
 59   hydro_electricity                             9603 non-null   float64
 60   hydro_energy_per_capita                       5145 non-null   float64
 61   hydro_share_elec                              7777 non-null   float64
 62   hydro_share_energy                            6379 non-null   float64
 63   low_carbon_cons_change_pct                    5902 non-null   float64
 64   low_carbon_cons_change_twh                    6293 non-null   float64
 65   low_carbon_consumption                        6405 non-null   float64
 66   low_carbon_elec_per_capita                    8596 non-null   float64
 67   low_carbon_electricity                        9698 non-null   float64
 68   low_carbon_energy_per_capita                  5145 non-null   float64
 69   low_carbon_share_elec                         7872 non-null   float64
 70   low_carbon_share_energy                       6379 non-null   float64
 71   net_elec_imports                              6056 non-null   float64
 72   net_elec_imports_share_demand                 6032 non-null   float64
 73   nuclear_cons_change_pct                       2579 non-null   float64
 74   nuclear_cons_change_twh                       7717 non-null   float64
 75   nuclear_consumption                           7859 non-null   float64
 76   nuclear_elec_per_capita                       9090 non-null   float64
 77   nuclear_electricity                           10192 non-null  float64
 78   nuclear_energy_per_capita                     6585 non-null   float64
 79   nuclear_share_elec                            7718 non-null   float64
 80   nuclear_share_energy                          6379 non-null   float64
 81   oil_cons_change_pct                           6267 non-null   float64
 82   oil_cons_change_twh                           6293 non-null   float64
 83   oil_consumption                               6405 non-null   float64
 84   oil_elec_per_capita                           6465 non-null   float64
 85   oil_electricity                               7147 non-null   float64
 86   oil_energy_per_capita                         5145 non-null   float64
 87   oil_prod_change_pct                           10182 non-null  float64
 88   oil_prod_change_twh                           17729 non-null  float64
 89   oil_prod_per_capita                           15574 non-null  float64
 90   oil_production                                17992 non-null  float64
 91   oil_share_elec                                7121 non-null   float64
 92   oil_share_energy                              6379 non-null   float64
 93   other_renewable_consumption                   6405 non-null   float64
 94   other_renewable_electricity                   9670 non-null   float64
 95   other_renewable_exc_biofuel_electricity       5716 non-null   float64
 96   other_renewables_cons_change_pct              3988 non-null   float64
 97   other_renewables_cons_change_twh              6293 non-null   float64
 98   other_renewables_elec_per_capita              8568 non-null   float64
 99   other_renewables_elec_per_capita_exc_biofuel  5394 non-null   float64
 100  other_renewables_energy_per_capita            5145 non-null   float64
 101  other_renewables_share_elec                   7844 non-null   float64
 102  other_renewables_share_elec_exc_biofuel       5690 non-null   float64
 103  other_renewables_share_energy                 6379 non-null   float64
 104  per_capita_electricity                        7071 non-null   float64
 105  primary_energy_consumption                    13255 non-null  float64
 106  renewables_cons_change_pct                    5895 non-null   float64
 107  renewables_cons_change_twh                    6293 non-null   float64
 108  renewables_consumption                        6405 non-null   float64
 109  renewables_elec_per_capita                    8596 non-null   float64
 110  renewables_electricity                        9698 non-null   float64
 111  renewables_energy_per_capita                  5145 non-null   float64
 112  renewables_share_elec                         7872 non-null   float64
 113  renewables_share_energy                       6379 non-null   float64
 114  solar_cons_change_pct                         2515 non-null   float64
 115  solar_cons_change_twh                         6293 non-null   float64
 116  solar_consumption                             6405 non-null   float64
 117  solar_elec_per_capita                         8613 non-null   float64
 118  solar_electricity                             9715 non-null   float64
 119  solar_energy_per_capita                       5145 non-null   float64
 120  solar_share_elec                              7869 non-null   float64
 121  solar_share_energy                            6379 non-null   float64
 122  wind_cons_change_pct                          2798 non-null   float64
 123  wind_cons_change_twh                          6293 non-null   float64
 124  wind_consumption                              6405 non-null   float64
 125  wind_elec_per_capita                          8405 non-null   float64
 126  wind_electricity                              9507 non-null   float64
 127  wind_energy_per_capita                        5145 non-null   float64
 128  wind_share_elec                               7661 non-null   float64
 129  wind_share_energy                             6379 non-null   float64
dtypes: float64(127), int64(1), object(2)
memory usage: 23.2+ MB

In [3]:
# Stage 1 of cleaning database - remove data for continents

country=pd.DataFrame(data_s[data_s["iso_code"].notnull()])
country.head(200)

,country,year,iso_code,population,gdp,biofuel_cons_change_pct,biofuel_cons_change_twh,biofuel_cons_per_capita,biofuel_consumption,biofuel_elec_per_capita,...,solar_share_elec,solar_share_energy,wind_cons_change_pct,wind_cons_change_twh,wind_consumption,wind_elec_per_capita,wind_electricity,wind_energy_per_capita,wind_share_elec,wind_share_energy
26,Afghanistan,1900,AFG,4707744.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,Afghanistan,1901,AFG,4751177.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Afghanistan,1902,AFG,4802500.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Afghanistan,1903,AFG,4861833.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,Afghanistan,1904,AFG,4921891.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
593,Albania,1970,ALB,2181226.0,6.888219e+09,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
594,Albania,1971,ALB,2234995.0,7.337364e+09,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
595,Albania,1972,ALB,2289265.0,7.811525e+09,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
596,Albania,1973,ALB,2344108.0,8.317288e+09,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
597,Albania,1974,ALB,2399397.0,8.539400e+09,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
country["iso_code"].unique()

array(['AFG', 'ALB', 'DZA', 'ASM', 'AGO', 'ATA', 'ATG', 'ARG', 'ARM',
       'ABW', 'AUS', 'AUT', 'AZE', 'BHS', 'BHR', 'BGD', 'BRB', 'BLR',
       'BEL', 'BLZ', 'BEN', 'BMU', 'BTN', 'BOL', 'BIH', 'BWA', 'BRA',
       'VGB', 'BRN', 'BGR', 'BFA', 'BDI', 'KHM', 'CMR', 'CAN', 'CPV',
       'CYM', 'CAF', 'TCD', 'CHL', 'CHN', 'COL', 'COM', 'COG', 'COK',
       'CRI', 'CIV', 'HRV', 'CUB', 'CUW', 'CYP', 'CZE', 'COD', 'DNK',
       'DJI', 'DMA', 'DOM', 'TLS', 'ECU', 'EGY', 'SLV', 'GNQ', 'ERI',
       'EST', 'SWZ', 'ETH', 'FLK', 'FRO', 'FJI', 'FIN', 'FRA', 'GUF',
       'PYF', 'GAB', 'GMB', 'GEO', 'DEU', 'GHA', 'GIB', 'GRC', 'GRL',
       'GRD', 'GLP', 'GUM', 'GTM', 'GIN', 'GNB', 'GUY', 'HTI', 'HND',
       'HKG', 'HUN', 'ISL', 'IND', 'IDN', 'IRN', 'IRQ', 'IRL', 'ISR',
       'ITA', 'JAM', 'JPN', 'JOR', 'KAZ', 'KEN', 'KIR', 'KWT', 'KGZ',
       'LAO', 'LVA', 'LBN', 'LSO', 'LBR', 'LBY', 'LTU', 'LUX', 'MAC',
       'MDG', 'MWI', 'MYS', 'MDV', 'MLI', 'MLT', 'MTQ', 'MRT', 'MUS',
       'MEX', 'FSM', 'MDA', 'MNG', 'MNE', 'MSR', 'MAR', 'MOZ', 'MMR',
       'NAM', 'NRU', 'NPL', 'NLD', 'ANT', 'NCL', 'NZL', 'NIC', 'NER',
       'NGA', 'NIU', 'PRK', 'MKD', 'MNP', 'NOR', 'OMN', 'PAK', 'PSE',
       'PAN', 'PNG', 'PRY', 'PER', 'PHL', 'POL', 'PRT', 'PRI', 'QAT',
       'REU', 'ROU', 'RUS', 'RWA', 'SHN', 'KNA', 'LCA', 'SPM', 'VCT',
       'WSM', 'STP', 'SAU', 'SEN', 'SRB', 'SYC', 'SLE', 'SGP', 'SVK',
       'SVN', 'SLB', 'SOM', 'ZAF', 'KOR', 'SSD', 'ESP', 'LKA', 'SDN',
       'SUR', 'SWE', 'CHE', 'SYR', 'TWN', 'TJK', 'TZA', 'THA', 'TGO',
       'TON', 'TTO', 'TUN', 'TUR', 'TKM', 'TCA', 'TUV', 'UGA', 'UKR',
       'ARE', 'GBR', 'USA', 'VIR', 'URY', 'UZB', 'VUT', 'VEN', 'VNM',
       'ESH', 'YEM', 'ZMB', 'ZWE'], dtype=object)

In [5]:
country['country'].unique()

array(['Afghanistan', 'Albania', 'Algeria', 'American Samoa', 'Angola',
       'Antarctica', 'Antigua and Barbuda', 'Argentina', 'Armenia',
       'Aruba', 'Australia', 'Austria', 'Azerbaijan', 'Bahamas',
       'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium',
       'Belize', 'Benin', 'Bermuda', 'Bhutan', 'Bolivia',
       'Bosnia and Herzegovina', 'Botswana', 'Brazil',
       'British Virgin Islands', 'Brunei', 'Bulgaria', 'Burkina Faso',
       'Burundi', 'Cambodia', 'Cameroon', 'Canada', 'Cape Verde',
       'Cayman Islands', 'Central African Republic', 'Chad', 'Chile',
       'China', 'Colombia', 'Comoros', 'Congo', 'Cook Islands',
       'Costa Rica', "Cote d'Ivoire", 'Croatia', 'Cuba', 'Curacao',
       'Cyprus', 'Czechia', 'Democratic Republic of Congo', 'Denmark',
       'Djibouti', 'Dominica', 'Dominican Republic', 'East Timor',
       'Ecuador', 'Egypt', 'El Salvador', 'Equatorial Guinea', 'Eritrea',
       'Estonia', 'Eswatini', 'Ethiopia', 'Falkland Islands',
       'Faroe Islands', 'Fiji', 'Finland', 'France', 'French Guiana',
       'French Polynesia', 'Gabon', 'Gambia', 'Georgia', 'Germany',
       'Ghana', 'Gibraltar', 'Greece', 'Greenland', 'Grenada',
       'Guadeloupe', 'Guam', 'Guatemala', 'Guinea', 'Guinea-Bissau',
       'Guyana', 'Haiti', 'Honduras', 'Hong Kong', 'Hungary', 'Iceland',
       'India', 'Indonesia', 'Iran', 'Iraq', 'Ireland', 'Israel', 'Italy',
       'Jamaica', 'Japan', 'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati',
       'Kuwait', 'Kyrgyzstan', 'Laos', 'Latvia', 'Lebanon', 'Lesotho',
       'Liberia', 'Libya', 'Lithuania', 'Luxembourg', 'Macao',
       'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta',
       'Martinique', 'Mauritania', 'Mauritius', 'Mexico',
       'Micronesia (country)', 'Moldova', 'Mongolia', 'Montenegro',
       'Montserrat', 'Morocco', 'Mozambique', 'Myanmar', 'Namibia',
       'Nauru', 'Nepal', 'Netherlands', 'Netherlands Antilles',
       'New Caledonia', 'New Zealand', 'Nicaragua', 'Niger', 'Nigeria',
       'Niue', 'North Korea', 'North Macedonia',
       'Northern Mariana Islands', 'Norway', 'Oman', 'Pakistan',
       'Palestine', 'Panama', 'Papua New Guinea', 'Paraguay', 'Peru',
       'Philippines', 'Poland', 'Portugal', 'Puerto Rico', 'Qatar',
       'Reunion', 'Romania', 'Russia', 'Rwanda', 'Saint Helena',
       'Saint Kitts and Nevis', 'Saint Lucia',
       'Saint Pierre and Miquelon', 'Saint Vincent and the Grenadines',
       'Samoa', 'Sao Tome and Principe', 'Saudi Arabia', 'Senegal',
       'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore', 'Slovakia',
       'Slovenia', 'Solomon Islands', 'Somalia', 'South Africa',
       'South Korea', 'South Sudan', 'Spain', 'Sri Lanka', 'Sudan',
       'Suriname', 'Sweden', 'Switzerland', 'Syria', 'Taiwan',
       'Tajikistan', 'Tanzania', 'Thailand', 'Togo', 'Tonga',
       'Trinidad and Tobago', 'Tunisia', 'Turkey', 'Turkmenistan',
       'Turks and Caicos Islands', 'Tuvalu', 'Uganda', 'Ukraine',
       'United Arab Emirates', 'United Kingdom', 'United States',
       'United States Virgin Islands', 'Uruguay', 'Uzbekistan', 'Vanuatu',
       'Venezuela', 'Vietnam', 'Western Sahara', 'Yemen', 'Zambia',
       'Zimbabwe'], dtype=object)

In [6]:
territories_to_exclude = [
    'ATA',  # Antarctica
    'ASM', 'GUM', 'MNP', 'PRI', 'VIR',  # US territories
    'BMU', 'VGB', 'CYM', 'FLK', 'GIB', 'MSR', 'SHN', 'TCA',  # British territories
    'GUF', 'PYF', 'GLP', 'MTQ', 'NCL', 'REU', 'SPM',  # French territories
    'FRO', 'GRL', 'CUW', 'ANT', 'COK', 'NIU',  # Danish/Dutch/NZ territories
    'HKG', 'MAC', 'TWN', 'ESH', 'PSE'  # judgment calls you chose to exclude
]
sovereign_countries =country[~country['iso_code'].isin(territories_to_exclude)]

In [7]:

print(type(sovereign_countries))
print(sovereign_countries.shape)
sovereign_countries.head(100)

<class 'pandas.core.frame.DataFrame'>
(15649, 130)

,country,year,iso_code,population,gdp,biofuel_cons_change_pct,biofuel_cons_change_twh,biofuel_cons_per_capita,biofuel_consumption,biofuel_elec_per_capita,...,solar_share_elec,solar_share_energy,wind_cons_change_pct,wind_cons_change_twh,wind_consumption,wind_elec_per_capita,wind_electricity,wind_energy_per_capita,wind_share_elec,wind_share_energy
26,Afghanistan,1900,AFG,4707744.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,Afghanistan,1901,AFG,4751177.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Afghanistan,1902,AFG,4802500.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Afghanistan,1903,AFG,4861833.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,Afghanistan,1904,AFG,4921891.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121,Afghanistan,1995,AFG,17065837.0,1.230753e+10,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
122,Afghanistan,1996,AFG,17763266.0,1.207013e+10,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
123,Afghanistan,1997,AFG,18452100.0,1.185075e+10,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
124,Afghanistan,1998,AFG,19159996.0,1.169217e+10,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
125,Afghanistan,1999,AFG,19887792.0,1.151732e+10,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
# For every year, how many countries actually have a non-null value for each column.

pd.set_option('display.max_rows', None)
sovereign_countries.groupby('year')[['gdp', 'renewables_share_energy', 'fossil_share_energy']].count()

      gdp  renewables_share_energy  fossil_share_energy
year
1900   36                        0                    0
1901   32                        0                    0
1902   33                        0                    0
1903   33                        0                    0
1904   33                        0                    0
1905   33                        0                    0
1906   34                        0                    0
1907   33                        0                    0
1908   33                        0                    0
1909   33                        0                    0
1910   38                        0                    0
1911   36                        0                    0
1912   34                        0                    0
1913   54                        0                    0
1914   34                        0                    0
1915   34                        0                    0
1916   35                        0                    0
1917   34                        0                    0
1918   34                        0                    0
1919   34                        0                    0
1920   39                        0                    0
1921   39                        0                    0
1922   37                        0                    0
1923   38                        0                    0
1924   40                        0                    0
1925   40                        0                    0
1926   41                        0                    0
1927   40                        0                    0
1928   40                        0                    0
1929   44                        0                    0
1930   42                        0                    0
1931   43                        0                    0
1932   42                        0                    0
1933   42                        0                    0
1934   42                        0                    0
1935   42                        0                    0
1936   43                        0                    0
1937   42                        0                    0
1938   44                        0                    0
1939   40                        0                    0
1940   40                        0                    0
1941   39                        0                    0
1942   38                        0                    0
1943   36                        0                    0
1944   35                        0                    0
1945   35                        0                    0
1946   37                        0                    0
1947   38                        0                    0
1948   40                        0                    0
1949   41                        0                    0
1950   86                        0                    0
1951   86                        0                    0
1952   86                        0                    0
1953   86                        0                    0
1954   86                        0                    0
1955   86                        0                    0
1956   86                        0                    0
1957   86                        0                    0
1958   86                        0                    0
1959   86                        0                    0
1960   86                        0                    0
1961   86                        0                    0
1962   86                        0                    0
1963   86                        0                    0
1964   86                        0                    0
1965   94                       63                   63
1966   94                       63                   63
1967   94                       63                   63
1968   94                       63                   63
1969   94                       63                   63
1970   95                       63                   63
1971   95                       64                   64
1972   95                       64                   64
1973   96                       64                   64
1974   95                       64                   64
1975   95                       64                   64
1976   95                       64                   64
1977   95                       64                   64
1978   95                       64                   64
1979   95                       64                   64
1980  137                       64                   64
1981  137                       64                   64
1982  137                       64                   64
1983  137                       64                   64
1984  137                       64                   64
1985  148                       74                   74
1986  148                       74                   74
1987  148                       74                   74
1988  148                       74                   74
1989  148                       74                   74
1990  154                       77                   77
1991  153                       77                   77
1992  159                       77                   77
1993  160                       77                   77
1994  160                       77                   77
1995  160                       77                   77
1996  160                       77                   77
1997  160                       77                   77
1998  160                       77                   77
1999  160                       77                   77
2000  160                       77                   77
2001  160                       77                   77
2002  160                       77                   77
2003  160                       77                   77
2004  160                       77                   77
2005  161                       77                   77
2006  161                       77                   77
2007  161                       77                   77
2008  161                       77                   77
2009  161                       77                   77
2010  161                       77                   77
2011  161                       77                   77
2012  161                       77                   77
2013  161                       77                   77
2014  161                       77                   77
2015  161                       77                   77
2016  161                       77                   77
2017  161                       77                   77
2018  161                       77                   77
2019  161                       77                   77
2020  161                       77                   77
2021  161                       77                   77
2022  161                       77                   77
2023    0                       77                   77
2024    0                       77                   77
2025    0                        0                    0

In [9]:
# The set of country codes that had non-null renewables data in 1990.
# The second line does the exact same thing, but for year 2010.
# The & operator between two Python sets computes their intersection — the elements present in both sets

countries_1990 = set(sovereign_countries[sovereign_countries.year==1990].dropna(subset=['renewables_share_energy'])['iso_code'])
countries_2010 = set(sovereign_countries[sovereign_countries.year==2010].dropna(subset=['renewables_share_energy'])['iso_code'])
print(len(countries_1990 & countries_2010))  # intersection

77

In [10]:
# Checking the availability of data for the time frame t0=1995, t1=2010, t2=2015

countries_t0 = set(sovereign_countries[sovereign_countries.year==1995].dropna(subset=['renewables_share_energy','fossil_share_energy'])['iso_code'])
countries_t1 = set(sovereign_countries[sovereign_countries.year==2010].dropna(subset=['renewables_share_energy','fossil_share_energy','gdp'])['iso_code'])
countries_t2 = set(sovereign_countries[sovereign_countries.year==2015].dropna(subset=['gdp'])['iso_code'])

survivors = countries_t0 & countries_t1 & countries_t2
print(len(survivors))

77

In [11]:
# Data size after extending the set of features our model will use 

final_features = [
    'renewables_share_energy', 'fossil_share_energy', 
    'coal_share_energy', 'oil_share_energy', 'gas_share_energy',
    'nuclear_share_energy',
    'renewables_share_elec', 'nuclear_share_elec'
]

countries_t0 = set(sovereign_countries[sovereign_countries.year==1995].dropna(subset=final_features)['iso_code'])
countries_t1 = set(sovereign_countries[sovereign_countries.year==2010].dropna(subset=final_features + ['gdp'])['iso_code'])
countries_t2 = set(sovereign_countries[sovereign_countries.year==2015].dropna(subset=['gdp'])['iso_code'])

final_survivors = countries_t0 & countries_t1 & countries_t2
print(len(final_survivors))

77

In [12]:
sub_1995 = sovereign_countries[(sovereign_countries.year==1995) & (sovereign_countries.iso_code.isin(final_survivors))]
print(sub_1995[final_features].eq(0).sum())
print()
print((sub_1995[final_features] < 0.01).sum())  # near-zero, not just exactly 0

renewables_share_energy     6
fossil_share_energy         0
coal_share_energy           7
oil_share_energy            0
gas_share_energy            5
nuclear_share_energy       48
renewables_share_elec       6
nuclear_share_elec         48
dtype: int64

renewables_share_energy     6
fossil_share_energy         0
coal_share_energy           9
oil_share_energy            0
gas_share_energy            5
nuclear_share_energy       48
renewables_share_elec       6
nuclear_share_elec         48
dtype: int64

In [13]:
# Step 1: Creating three slices, each keeping iso_code + the relevant columns,
# renamed with a year suffix so nothing collides when merged

t0_slice = sovereign_countries[
    (sovereign_countries.year == 1995) & 
    (sovereign_countries.iso_code.isin(final_survivors))
][['iso_code'] + final_features].copy()
t0_slice = t0_slice.rename(columns={col: f"{col}_1995" for col in final_features})

t1_slice = sovereign_countries[
    (sovereign_countries.year == 2010) & 
    (sovereign_countries.iso_code.isin(final_survivors))
][['iso_code'] + final_features + ['gdp']].copy()
t1_slice = t1_slice.rename(columns={col: f"{col}_2010" for col in final_features})
t1_slice = t1_slice.rename(columns={'gdp': 'gdp_2010'})

t2_slice = sovereign_countries[
    (sovereign_countries.year == 2015) & 
    (sovereign_countries.iso_code.isin(final_survivors))
][['iso_code', 'gdp']].copy()
t2_slice = t2_slice.rename(columns={'gdp': 'gdp_2015'})

# Step 2: Merging all three into one wide table, one row per country
model_data = t0_slice.merge(t1_slice, on='iso_code', how='inner')
model_data = model_data.merge(t2_slice, on='iso_code', how='inner')

print(model_data.shape)
model_data.head(80)

(77, 19)

,iso_code,renewables_share_energy_1995,fossil_share_energy_1995,coal_share_energy_1995,oil_share_energy_1995,gas_share_energy_1995,nuclear_share_energy_1995,renewables_share_elec_1995,nuclear_share_elec_1995,renewables_share_energy_2010,fossil_share_energy_2010,coal_share_energy_2010,oil_share_energy_2010,gas_share_energy_2010,nuclear_share_energy_2010,renewables_share_elec_2010,nuclear_share_elec_2010,gdp_2010,gdp_2015
0,DZA,0.171,99.829,2.303,32.941,64.585,0.000,0.979,0.000,0.108,99.892,0.821,41.373,57.698,0.000,0.372,0.000,4.507058e+11,5.515217e+11
1,ARG,11.830,85.032,1.185,41.882,41.965,3.138,39.635,10.520,11.092,86.765,1.538,37.183,48.044,2.143,27.595,5.722,7.857852e+11,8.503566e+11
2,AUS,4.002,95.998,42.049,37.152,16.798,0.000,9.408,0.000,4.088,95.912,40.350,34.499,21.063,0.000,8.830,0.000,9.938540e+11,1.139303e+12
3,AUT,30.140,69.860,11.177,37.580,21.102,0.000,70.681,0.000,30.113,69.887,9.496,37.189,23.202,0.000,66.337,0.000,3.388322e+11,3.581083e+11
4,AZE,2.695,97.305,0.022,48.437,48.847,0.000,9.129,0.000,7.021,92.979,0.038,29.131,63.810,0.000,18.265,0.000,1.442966e+11,1.640369e+11
5,BGD,0.965,99.035,3.486,32.561,62.988,0.000,3.443,0.000,0.834,99.166,3.457,18.982,76.727,0.000,2.031,0.000,4.000878e+11,5.521047e+11
6,BLR,0.022,99.978,4.416,49.587,45.975,0.000,0.080,0.000,0.252,99.748,2.452,29.597,67.698,0.000,0.401,0.000,1.662399e+11,1.737098e+11
7,BEL,0.294,82.549,15.373,48.579,18.598,17.157,0.911,56.257,3.125,80.474,5.727,49.258,25.489,16.401,7.061,51.526,4.112617e+11,4.415515e+11
8,BRA,43.373,56.252,7.377,46.074,2.802,0.375,94.157,0.914,42.505,56.281,5.397,42.034,8.849,1.214,84.802,2.815,2.820493e+12,3.021043e+12
9,BGR,2.226,80.096,32.813,27.766,19.518,17.677,5.210,41.441,7.258,73.795,38.193,22.851,12.750,18.948,12.541,33.203,1.090452e+11,1.144986e+11
10,CAN,28.664,63.196,9.236,30.661,23.299,8.140,61.172,17.417,26.567,67.085,7.771,34.516,24.798,6.349,61.063,14.831,1.406355e+12,1.568026e+12
11,CHL,24.921,75.079,12.065,53.912,9.102,0.000,72.404,0.000,18.941,81.059,14.511,50.601,15.947,0.000,40.199,0.000,3.214574e+11,3.862513e+11
12,CHN,5.239,94.415,74.988,17.695,1.733,0.346,19.286,1.274,7.195,92.132,70.336,18.031,3.765,0.673,18.691,1.776,1.285881e+13,1.830122e+13
13,COL,28.416,71.584,13.202,45.339,13.043,0.000,68.374,0.000,27.404,72.596,13.389,38.264,20.943,0.000,70.513,0.000,4.898702e+11,6.127509e+11
14,HRV,18.212,81.788,2.341,53.540,25.907,0.000,61.580,0.000,22.716,77.284,7.443,41.142,28.699,0.000,62.880,0.000,8.130379e+10,8.173111e+10
15,CYP,0.000,100.000,4.932,95.068,0.000,0.000,0.000,0.000,1.095,98.905,0.501,98.405,0.000,0.000,1.501,0.000,2.728556e+10,2.531251e+10
16,CZE,1.445,91.552,56.220,19.624,15.707,7.003,3.978,20.188,3.759,81.984,42.719,20.906,18.358,14.258,6.935,32.856,2.712320e+11,2.982761e+11
17,DNK,2.209,97.791,31.008,51.520,15.263,0.000,5.085,0.000,14.973,85.027,19.406,43.499,22.123,0.000,32.077,0.000,2.381902e+11,2.554013e+11
18,ECU,15.267,84.733,0.004,81.285,3.443,0.000,61.227,0.000,15.137,84.863,0.075,80.760,4.027,0.000,44.130,0.000,1.379133e+11,1.725384e+11
19,EGY,7.134,92.866,1.853,63.187,27.827,0.000,22.096,0.000,4.198,95.802,0.605,46.558,48.640,0.000,9.963,0.000,8.987514e+11,1.079612e+12
20,EST,0.030,99.970,65.161,23.911,10.898,0.000,0.115,0.000,4.380,95.620,64.102,22.561,8.956,0.000,8.096,0.000,2.758697e+10,3.210602e+10
21,FIN,17.208,66.559,20.863,35.757,9.938,16.233,30.547,30.031,19.122,64.696,21.509,31.932,11.255,16.181,29.985,28.274,2.017460e+11,2.027067e+11
22,FRA,7.396,56.073,6.271,37.810,11.992,36.531,15.051,77.079,7.882,54.455,4.662,33.064,16.728,37.663,13.635,76.200,2.342490e+12,2.464954e+12
23,DEU,1.788,87.406,26.606,41.176,19.624,10.806,4.884,28.846,8.465,81.963,23.434,35.500,23.029,9.571,16.887,22.518,3.301123e+12,3.628074e+12
24,GRC,3.131,96.869,29.711,66.996,0.161,0.000,8.696,0.000,7.696,92.304,24.295,57.007,11.002,0.000,18.601,0.000,2.909844e+11,2.423237e+11
25,HUN,0.220,86.154,17.678,31.158,37.318,13.626,0.647,41.240,3.999,81.163,11.318,28.576,41.268,14.838,8.084,42.184,2.004966e+11,2.264746e+11
26,ISL,60.333,39.667,3.201,36.466,0.000,0.000,99.789,0.000,83.047,16.953,1.925,15.028,0.000,0.000,100.000,0.000,1.153145e+10,1.314788e+10
27,IND,7.258,92.025,55.329,30.565,6.130,0.717,18.022,1.783,6.057,92.977,53.804,29.700,9.474,0.966,15.114,2.465,5.361371e+12,7.391522e+12
28,IDN,3.445,96.555,7.255,56.453,32.847,0.000,19.412,0.000,4.417,95.583,24.679,45.601,25.303,0.000,19.503,0.000,2.039335e+12,2.684764e+12
29,IRN,2.188,97.812,1.136,66.510,30.165,0.000,9.867,0.000,1.106,98.894,0.544,39.574,58.776,0.000,4.425,0.000,1.310507e+12,1.331012e+12
30,IRQ,5.564,94.436,0.000,85.962,8.473,0.000,26.869,0.000,2.404,97.596,0.000,79.378,18.219,0.000,9.753,0.000,2.975072e+11,4.360107e+11
31,IRL,1.517,98.483,25.798,52.307,20.378,0.000,4.155,0.000,6.149,93.851,12.998,50.085,30.768,0.000,13.388,0.000,2.218524e+11,2.499559e+11
32,ISR,0.036,99.964,24.599,75.243,0.122,0.000,0.082,0.000,0.222,99.778,33.927,46.729,19.122,0.000,0.290,0.000,2.103276e+11,2.512239e+11
33,ITA,5.386,94.614,6.518,64.072,24.023,0.000,17.466,0.000,10.921,89.079,7.744,42.790,38.545,0.000,25.948,0.000,2.080546e+12,2.025809e+12
34,JPN,4.483,81.966,16.662,54.996,10.308,13.551,9.213,28.380,5.404,81.799,22.738,42.263,16.798,12.797,10.228,25.290,4.480296e+12,4.707025e+12
35,KAZ,3.875,96.088,53.195,23.946,18.948,0.037,12.483,0.119,3.426,96.574,63.667,18.547,14.360,0.000,9.704,0.000,3.333417e+11,4.219771e+11
36,KWT,0.000,100.000,0.000,41.454,58.546,0.000,0.000,0.000,0.000,100.000,0.011,65.483,34.506,0.000,0.000,0.000,1.760370e+11,2.194060e+11
37,LVA,18.407,81.593,7.011,50.687,23.895,0.000,73.684,0.000,19.887,80.113,2.569,42.617,34.927,0.000,54.902,0.000,3.588118e+10,4.377419e+10
38,LTU,1.051,65.643,2.895,38.816,23.932,33.306,2.737,87.426,4.494,95.506,3.644,47.987,43.874,0.000,18.200,0.000,5.607378e+10,6.753966e+10
39,LUX,0.900,99.100,16.942,63.126,19.031,0.000,22.449,0.000,2.428,97.572,1.556,68.227,27.789,0.000,8.333,0.000,2.752670e+10,3.097649e+10
40,MYS,4.343,95.657,4.877,56.745,34.035,0.000,13.351,0.000,2.202,97.798,18.388,38.701,40.709,0.000,6.094,0.000,5.250566e+11,6.852377e+11
41,MEX,6.739,91.627,4.059,66.188,21.380,1.634,22.630,5.615,5.953,93.326,6.982,55.212,31.131,0.722,16.863,2.134,1.638272e+12,1.916009e+12
42,MAR,1.658,98.342,18.557,79.659,0.125,0.000,5.053,0.000,5.532,94.468,16.688,73.981,3.799,0.000,18.775,0.000,2.256438e+11,2.746900e+11
43,NLD,0.442,98.413,10.631,45.915,41.867,1.145,1.767,5.039,3.039,96.077,7.507,48.579,39.991,0.884,9.475,3.362,7.281932e+11,7.610833e+11
44,NZL,40.821,59.179,6.486,31.494,21.199,0.000,83.934,0.000,38.311,61.689,6.890,36.039,18.760,0.000,73.121,0.000,1.394788e+11,1.607822e+11
45,MKD,7.805,92.195,58.326,33.869,0.000,0.000,13.051,0.000,18.923,81.077,44.971,32.794,3.311,0.000,33.471,0.000,2.258313e+10,2.558382e+10
46,NOR,69.429,30.571,2.304,21.939,6.328,0.000,99.656,0.000,64.629,35.371,1.855,25.071,8.444,0.000,95.793,0.000,3.837609e+11,4.307890e+11
47,OMN,0.000,100.000,0.000,47.792,52.208,0.000,0.000,0.000,0.000,100.000,0.145,30.761,69.093,0.000,0.000,0.000,1.351983e+11,1.617701e+11
48,PAK,15.541,84.103,6.322,45.742,32.039,0.356,35.681,0.818,10.436,88.675,8.406,32.770,47.498,0.890,34.715,2.708,8.054915e+11,1.010825e+12
49,PER,27.773,72.227,3.318,65.962,2.946,0.000,77.485,0.000,25.513,74.487,4.264,45.769,24.453,0.000,57.704,0.000,2.303533e+11,2.906427e+11
50,PHL,14.080,85.920,7.379,78.521,0.020,0.000,36.857,0.000,15.667,84.333,23.752,50.342,10.239,0.000,26.296,0.000,5.655148e+11,7.626790e+11
51,POL,0.492,99.508,73.789,16.281,9.438,0.000,1.430,0.000,3.379,96.621,55.407,27.172,14.042,0.000,6.940,0.000,7.956199e+11,9.360438e+11
52,PRT,10.868,89.132,20.089,69.042,0.000,0.000,28.502,0.000,26.402,73.598,6.395,49.887,17.317,0.000,53.010,0.000,2.672774e+11,2.569119e+11
53,QAT,0.000,100.000,0.000,10.518,89.482,0.000,0.000,0.000,0.000,100.000,0.000,24.175,75.825,0.000,0.000,0.000,2.386481e+11,3.612427e+11
54,ROU,8.403,91.597,22.267,28.779,40.551,0.000,28.264,0.000,13.830,78.453,20.877,25.590,31.986,7.716,33.598,19.232,3.354896e+11,3.843065e+11
55,RUS,6.390,90.002,18.114,23.295,48.593,3.607,20.501,11.573,5.597,88.695,13.538,20.640,54.518,5.707,16.090,16.417,3.105249e+12,3.456430e+12
56,SAU,0.000,100.000,0.000,63.909,36.091,0.000,0.000,0.000,0.000,100.000,0.032,65.992,33.975,0.000,0.000,0.000,1.156842e+12,1.591797e+12
57,SGP,0.197,99.803,0.034,96.105,3.664,0.000,1.111,0.000,0.233,99.767,0.011,89.230,10.525,0.000,2.601,0.000,2.975868e+11,3.745874e+11
58,SVK,6.511,78.229,30.410,18.675,29.144,15.260,18.464,43.284,8.314,73.053,21.988,22.480,28.585,18.633,21.668,53.059,1.183443e+11,1.327556e+11
59,SVN,12.293,69.641,21.814,36.127,11.699,18.066,25.194,37.054,15.228,67.530,19.543,36.251,11.737,17.242,29.213,34.809,5.364978e+10,5.441424e+10
60,ZAF,0.132,97.057,74.297,21.604,1.156,2.811,0.283,6.054,0.310,97.282,73.792,20.673,2.818,2.408,0.613,5.212,6.076016e+11,6.959332e+11
61,KOR,0.476,89.040,19.328,64.282,5.430,10.484,1.480,32.930,0.630,86.668,30.073,41.819,14.777,12.702,1.149,30.018,1.562823e+12,1.803764e+12
62,ESP,5.624,81.665,18.203,56.052,7.410,12.711,14.769,33.598,16.490,73.916,4.796,47.479,21.642,9.593,32.831,20.816,1.480376e+12,1.488099e+12
63,LKA,31.403,68.597,0.029,68.567,0.000,0.000,94.036,0.000,21.793,78.206,1.016,77.191,0.000,0.000,53.451,0.000,1.806428e+11,2.449143e+11
64,SWE,30.274,39.844,4.978,33.656,1.209,29.883,47.579,47.161,37.370,37.797,5.134,30.108,2.555,24.833,55.298,38.956,3.998390e+11,4.290374e+11
65,CHE,29.600,49.972,0.659,42.478,6.836,20.428,56.872,39.327,27.969,52.380,0.491,41.935,9.955,19.650,56.730,39.879,4.511397e+11,5.004847e+11
66,THA,3.056,96.944,13.606,66.122,17.216,0.000,8.447,0.000,2.750,97.250,15.233,45.349,36.668,0.000,5.566,0.000,8.701093e+11,1.002012e+12
67,TTO,0.116,99.884,0.000,16.920,82.964,0.000,0.766,0.000,0.005,99.995,0.000,11.180,88.815,0.000,0.000,0.000,4.128543e+10,4.543580e+10
68,TUR,14.165,85.835,27.330,49.262,9.242,0.000,41.570,0.000,11.710,88.290,29.389,30.107,28.793,0.000,26.385,0.000,1.240497e+12,1.727193e+12
69,TKM,0.011,99.989,0.056,27.121,72.813,0.000,0.040,0.000,0.003,99.997,0.000,25.951,74.046,0.000,0.000,0.000,7.111515e+10,9.334615e+10
70,UKR,1.500,87.876,32.169,16.586,39.120,10.625,5.091,36.079,2.464,81.179,31.342,11.396,38.440,16.357,7.091,47.214,4.394298e+11,3.980454e+11
71,ARE,0.000,100.000,0.000,50.151,49.849,0.000,0.000,0.000,0.005,99.995,0.787,38.260,60.948,0.000,0.021,0.000,4.900489e+11,6.747427e+11
72,GBR,0.752,89.543,21.676,38.879,28.988,9.705,1.980,26.365,3.043,90.401,14.375,36.122,39.904,6.556,6.852,16.264,2.190920e+12,2.426436e+12
73,USA,4.551,87.328,23.069,39.595,24.664,8.121,10.602,19.870,5.642,85.799,22.443,38.277,25.079,8.559,10.318,19.616,1.523959e+13,1.693763e+13
74,UZB,3.398,96.602,2.051,15.314,79.237,0.000,13.040,0.000,4.069,95.931,1.761,10.158,84.012,0.000,15.759,0.000,1.951602e+11,2.739836e+11
75,VEN,19.900,80.100,0.008,37.587,42.505,0.000,70.051,0.000,21.151,78.849,0.246,45.477,33.126,0.000,67.493,0.000,4.775917e+11,4.849755e+11
76,VNM,23.467,76.533,28.752,46.659,1.121,0.000,72.242,0.000,13.931,86.069,31.618,37.503,16.948,0.000,31.204,0.000,4.136663e+11,5.558221e+11

In [14]:
# Step 3: Compute absolute change for each energy feature, in a loop
for feature in final_features:
    model_data[f"{feature}_change"] = model_data[f"{feature}_2010"] - model_data[f"{feature}_1995"]

# Step 4: Compute GDP growth (percentage)
model_data['gdp_growth'] = (model_data['gdp_2015'] - model_data['gdp_2010']) / model_data['gdp_2010']

# Step 5: Median split into binary target
model_data['high_growth'] = (model_data['gdp_growth'] > model_data['gdp_growth'].median()).astype(int)

model_data.head()

,iso_code,renewables_share_energy_1995,fossil_share_energy_1995,coal_share_energy_1995,oil_share_energy_1995,gas_share_energy_1995,nuclear_share_energy_1995,renewables_share_elec_1995,nuclear_share_elec_1995,renewables_share_energy_2010,...,renewables_share_energy_change,fossil_share_energy_change,coal_share_energy_change,oil_share_energy_change,gas_share_energy_change,nuclear_share_energy_change,renewables_share_elec_change,nuclear_share_elec_change,gdp_growth,high_growth
0,DZA,0.171,99.829,2.303,32.941,64.585,0.000,0.979,0.00,0.108,...,-0.063,0.063,-1.482,8.432,-6.887,0.000,-0.607,0.000,0.223685,1
1,ARG,11.830,85.032,1.185,41.882,41.965,3.138,39.635,10.52,11.092,...,-0.738,1.733,0.353,-4.699,6.079,-0.995,-12.040,-4.798,0.082174,0
2,AUS,4.002,95.998,42.049,37.152,16.798,0.000,9.408,0.00,4.088,...,0.086,-0.086,-1.699,-2.653,4.265,0.000,-0.578,0.000,0.146349,1
3,AUT,30.140,69.860,11.177,37.580,21.102,0.000,70.681,0.00,30.113,...,-0.027,0.027,-1.681,-0.391,2.100,0.000,-4.344,0.000,0.056890,0
4,AZE,2.695,97.305,0.022,48.437,48.847,0.000,9.129,0.00,7.021,...,4.326,-4.326,0.016,-19.306,14.963,0.000,9.136,0.000,0.136804,0

In [15]:
model_data['high_growth'].value_counts()

high_growth
0    39
1    38
Name: count, dtype: int64

In [16]:
model_data.head(80)

,iso_code,renewables_share_energy_1995,fossil_share_energy_1995,coal_share_energy_1995,oil_share_energy_1995,gas_share_energy_1995,nuclear_share_energy_1995,renewables_share_elec_1995,nuclear_share_elec_1995,renewables_share_energy_2010,...,renewables_share_energy_change,fossil_share_energy_change,coal_share_energy_change,oil_share_energy_change,gas_share_energy_change,nuclear_share_energy_change,renewables_share_elec_change,nuclear_share_elec_change,gdp_growth,high_growth
0,DZA,0.171,99.829,2.303,32.941,64.585,0.000,0.979,0.000,0.108,...,-0.063,0.063,-1.482,8.432,-6.887,0.000,-0.607,0.000,0.223685,1
1,ARG,11.830,85.032,1.185,41.882,41.965,3.138,39.635,10.520,11.092,...,-0.738,1.733,0.353,-4.699,6.079,-0.995,-12.040,-4.798,0.082174,0
2,AUS,4.002,95.998,42.049,37.152,16.798,0.000,9.408,0.000,4.088,...,0.086,-0.086,-1.699,-2.653,4.265,0.000,-0.578,0.000,0.146349,1
3,AUT,30.140,69.860,11.177,37.580,21.102,0.000,70.681,0.000,30.113,...,-0.027,0.027,-1.681,-0.391,2.100,0.000,-4.344,0.000,0.056890,0
4,AZE,2.695,97.305,0.022,48.437,48.847,0.000,9.129,0.000,7.021,...,4.326,-4.326,0.016,-19.306,14.963,0.000,9.136,0.000,0.136804,0
5,BGD,0.965,99.035,3.486,32.561,62.988,0.000,3.443,0.000,0.834,...,-0.131,0.131,-0.029,-13.579,13.739,0.000,-1.412,0.000,0.379959,1
6,BLR,0.022,99.978,4.416,49.587,45.975,0.000,0.080,0.000,0.252,...,0.230,-0.230,-1.964,-19.990,21.723,0.000,0.321,0.000,0.044935,0
7,BEL,0.294,82.549,15.373,48.579,18.598,17.157,0.911,56.257,3.125,...,2.831,-2.075,-9.646,0.679,6.891,-0.756,6.150,-4.731,0.073651,0
8,BRA,43.373,56.252,7.377,46.074,2.802,0.375,94.157,0.914,42.505,...,-0.868,0.029,-1.980,-4.040,6.047,0.839,-9.355,1.901,0.071105,0
9,BGR,2.226,80.096,32.813,27.766,19.518,17.677,5.210,41.441,7.258,...,5.032,-6.301,5.380,-4.915,-6.768,1.271,7.331,-8.238,0.050010,0
10,CAN,28.664,63.196,9.236,30.661,23.299,8.140,61.172,17.417,26.567,...,-2.097,3.889,-1.465,3.855,1.499,-1.791,-0.109,-2.586,0.114957,0
11,CHL,24.921,75.079,12.065,53.912,9.102,0.000,72.404,0.000,18.941,...,-5.980,5.980,2.446,-3.311,6.845,0.000,-32.205,0.000,0.201563,1
12,CHN,5.239,94.415,74.988,17.695,1.733,0.346,19.286,1.274,7.195,...,1.956,-2.283,-4.652,0.336,2.032,0.327,-0.595,0.502,0.423244,1
13,COL,28.416,71.584,13.202,45.339,13.043,0.000,68.374,0.000,27.404,...,-1.012,1.012,0.187,-7.075,7.900,0.000,2.139,0.000,0.250843,1
14,HRV,18.212,81.788,2.341,53.540,25.907,0.000,61.580,0.000,22.716,...,4.504,-4.504,5.102,-12.398,2.792,0.000,1.300,0.000,0.005256,0
15,CYP,0.000,100.000,4.932,95.068,0.000,0.000,0.000,0.000,1.095,...,1.095,-1.095,-4.431,3.337,0.000,0.000,1.501,0.000,-0.072311,0
16,CZE,1.445,91.552,56.220,19.624,15.707,7.003,3.978,20.188,3.759,...,2.314,-9.568,-13.501,1.282,2.651,7.255,2.957,12.668,0.099708,0
17,DNK,2.209,97.791,31.008,51.520,15.263,0.000,5.085,0.000,14.973,...,12.764,-12.764,-11.602,-8.021,6.860,0.000,26.992,0.000,0.072258,0
18,ECU,15.267,84.733,0.004,81.285,3.443,0.000,61.227,0.000,15.137,...,-0.130,0.130,0.071,-0.525,0.584,0.000,-17.097,0.000,0.251065,1
19,EGY,7.134,92.866,1.853,63.187,27.827,0.000,22.096,0.000,4.198,...,-2.936,2.936,-1.248,-16.629,20.813,0.000,-12.133,0.000,0.201235,1
20,EST,0.030,99.970,65.161,23.911,10.898,0.000,0.115,0.000,4.380,...,4.350,-4.350,-1.059,-1.350,-1.942,0.000,7.981,0.000,0.163811,1
21,FIN,17.208,66.559,20.863,35.757,9.938,16.233,30.547,30.031,19.122,...,1.914,-1.863,0.646,-3.825,1.317,-0.052,-0.562,-1.757,0.004762,0
22,FRA,7.396,56.073,6.271,37.810,11.992,36.531,15.051,77.079,7.882,...,0.486,-1.618,-1.609,-4.746,4.736,1.132,-1.416,-0.879,0.052279,0
23,DEU,1.788,87.406,26.606,41.176,19.624,10.806,4.884,28.846,8.465,...,6.677,-5.443,-3.172,-5.676,3.405,-1.235,12.003,-6.328,0.099042,0
24,GRC,3.131,96.869,29.711,66.996,0.161,0.000,8.696,0.000,7.696,...,4.565,-4.565,-5.416,-9.989,10.841,0.000,9.905,0.000,-0.167228,0
25,HUN,0.220,86.154,17.678,31.158,37.318,13.626,0.647,41.240,3.999,...,3.779,-4.991,-6.360,-2.582,3.950,1.212,7.437,0.944,0.129568,0
26,ISL,60.333,39.667,3.201,36.466,0.000,0.000,99.789,0.000,83.047,...,22.714,-22.714,-1.276,-21.438,0.000,0.000,0.211,0.000,0.140176,0
27,IND,7.258,92.025,55.329,30.565,6.130,0.717,18.022,1.783,6.057,...,-1.201,0.952,-1.525,-0.865,3.344,0.249,-2.908,0.682,0.378662,1
28,IDN,3.445,96.555,7.255,56.453,32.847,0.000,19.412,0.000,4.417,...,0.972,-0.972,17.424,-10.852,-7.544,0.000,0.091,0.000,0.316490,1
29,IRN,2.188,97.812,1.136,66.510,30.165,0.000,9.867,0.000,1.106,...,-1.082,1.082,-0.592,-26.936,28.611,0.000,-5.442,0.000,0.015647,0
30,IRQ,5.564,94.436,0.000,85.962,8.473,0.000,26.869,0.000,2.404,...,-3.160,3.160,0.000,-6.584,9.746,0.000,-17.116,0.000,0.465547,1
31,IRL,1.517,98.483,25.798,52.307,20.378,0.000,4.155,0.000,6.149,...,4.632,-4.632,-12.800,-2.222,10.390,0.000,9.233,0.000,0.126676,0
32,ISR,0.036,99.964,24.599,75.243,0.122,0.000,0.082,0.000,0.222,...,0.186,-0.186,9.328,-28.514,19.000,0.000,0.208,0.000,0.194441,1
33,ITA,5.386,94.614,6.518,64.072,24.023,0.000,17.466,0.000,10.921,...,5.535,-5.535,1.226,-21.282,14.522,0.000,8.482,0.000,-0.026309,0
34,JPN,4.483,81.966,16.662,54.996,10.308,13.551,9.213,28.380,5.404,...,0.921,-0.167,6.076,-12.733,6.490,-0.754,1.015,-3.090,0.050606,0
35,KAZ,3.875,96.088,53.195,23.946,18.948,0.037,12.483,0.119,3.426,...,-0.449,0.486,10.472,-5.399,-4.588,-0.037,-2.779,-0.119,0.265899,1
36,KWT,0.000,100.000,0.000,41.454,58.546,0.000,0.000,0.000,0.000,...,0.000,0.000,0.011,24.029,-24.040,0.000,0.000,0.000,0.246364,1
37,LVA,18.407,81.593,7.011,50.687,23.895,0.000,73.684,0.000,19.887,...,1.480,-1.480,-4.442,-8.070,11.032,0.000,-18.782,0.000,0.219976,1
38,LTU,1.051,65.643,2.895,38.816,23.932,33.306,2.737,87.426,4.494,...,3.443,29.863,0.749,9.171,19.942,-33.306,15.463,-87.426,0.204479,1
39,LUX,0.900,99.100,16.942,63.126,19.031,0.000,22.449,0.000,2.428,...,1.528,-1.528,-15.386,5.101,8.758,0.000,-14.116,0.000,0.125325,0
40,MYS,4.343,95.657,4.877,56.745,34.035,0.000,13.351,0.000,2.202,...,-2.141,2.141,13.511,-18.044,6.674,0.000,-7.257,0.000,0.305074,1
41,MEX,6.739,91.627,4.059,66.188,21.380,1.634,22.630,5.615,5.953,...,-0.786,1.699,2.923,-10.976,9.751,-0.912,-5.767,-3.481,0.169531,1
42,MAR,1.658,98.342,18.557,79.659,0.125,0.000,5.053,0.000,5.532,...,3.874,-3.874,-1.869,-5.678,3.674,0.000,13.722,0.000,0.217361,1
43,NLD,0.442,98.413,10.631,45.915,41.867,1.145,1.767,5.039,3.039,...,2.597,-2.336,-3.124,2.664,-1.876,-0.261,7.708,-1.677,0.045167,0
44,NZL,40.821,59.179,6.486,31.494,21.199,0.000,83.934,0.000,38.311,...,-2.510,2.510,0.404,4.545,-2.439,0.000,-10.813,0.000,0.152736,1
45,MKD,7.805,92.195,58.326,33.869,0.000,0.000,13.051,0.000,18.923,...,11.118,-11.118,-13.355,-1.075,3.311,0.000,20.420,0.000,0.132873,0
46,NOR,69.429,30.571,2.304,21.939,6.328,0.000,99.656,0.000,64.629,...,-4.800,4.800,-0.449,3.132,2.116,0.000,-3.863,0.000,0.122545,0
47,OMN,0.000,100.000,0.000,47.792,52.208,0.000,0.000,0.000,0.000,...,0.000,0.000,0.145,-17.031,16.885,0.000,0.000,0.000,0.196539,1
48,PAK,15.541,84.103,6.322,45.742,32.039,0.356,35.681,0.818,10.436,...,-5.105,4.572,2.084,-12.972,15.459,0.534,-0.966,1.890,0.254917,1
49,PER,27.773,72.227,3.318,65.962,2.946,0.000,77.485,0.000,25.513,...,-2.260,2.260,0.946,-20.193,21.507,0.000,-19.781,0.000,0.261726,1
50,PHL,14.080,85.920,7.379,78.521,0.020,0.000,36.857,0.000,15.667,...,1.587,-1.587,16.373,-28.179,10.219,0.000,-10.561,0.000,0.348645,1
51,POL,0.492,99.508,73.789,16.281,9.438,0.000,1.430,0.000,3.379,...,2.887,-2.887,-18.382,10.891,4.604,0.000,5.510,0.000,0.176496,1
52,PRT,10.868,89.132,20.089,69.042,0.000,0.000,28.502,0.000,26.402,...,15.534,-15.534,-13.694,-19.155,17.317,0.000,24.508,0.000,-0.038782,0
53,QAT,0.000,100.000,0.000,10.518,89.482,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,13.657,-13.657,0.000,0.000,0.000,0.513705,1
54,ROU,8.403,91.597,22.267,28.779,40.551,0.000,28.264,0.000,13.830,...,5.427,-13.144,-1.390,-3.189,-8.565,7.716,5.334,19.232,0.145509,1
55,RUS,6.390,90.002,18.114,23.295,48.593,3.607,20.501,11.573,5.597,...,-0.793,-1.307,-4.576,-2.655,5.925,2.100,-4.411,4.844,0.113093,0
56,SAU,0.000,100.000,0.000,63.909,36.091,0.000,0.000,0.000,0.000,...,0.000,0.000,0.032,2.083,-2.116,0.000,0.000,0.000,0.375985,1
57,SGP,0.197,99.803,0.034,96.105,3.664,0.000,1.111,0.000,0.233,...,0.036,-0.036,-0.023,-6.875,6.861,0.000,1.490,0.000,0.258750,1
58,SVK,6.511,78.229,30.410,18.675,29.144,15.260,18.464,43.284,8.314,...,1.803,-5.176,-8.422,3.805,-0.559,3.373,3.204,9.775,0.121774,0
59,SVN,12.293,69.641,21.814,36.127,11.699,18.066,25.194,37.054,15.228,...,2.935,-2.111,-2.271,0.124,0.038,-0.824,4.019,-2.245,0.014249,0
60,ZAF,0.132,97.057,74.297,21.604,1.156,2.811,0.283,6.054,0.310,...,0.178,0.225,-0.505,-0.931,1.662,-0.403,0.330,-0.842,0.145377,0
61,KOR,0.476,89.040,19.328,64.282,5.430,10.484,1.480,32.930,0.630,...,0.154,-2.372,10.745,-22.463,9.347,2.218,-0.331,-2.912,0.154170,1
62,ESP,5.624,81.665,18.203,56.052,7.410,12.711,14.769,33.598,16.490,...,10.866,-7.749,-13.407,-8.573,14.232,-3.118,18.062,-12.782,0.005217,0
63,LKA,31.403,68.597,0.029,68.567,0.000,0.000,94.036,0.000,21.793,...,-9.610,9.609,0.987,8.624,0.000,0.000,-40.585,0.000,0.355793,1
64,SWE,30.274,39.844,4.978,33.656,1.209,29.883,47.579,47.161,37.370,...,7.096,-2.047,0.156,-3.548,1.346,-5.050,7.719,-8.205,0.073026,0
65,CHE,29.600,49.972,0.659,42.478,6.836,20.428,56.872,39.327,27.969,...,-1.631,2.408,-0.168,-0.543,3.119,-0.778,-0.142,0.552,0.109378,0
66,THA,3.056,96.944,13.606,66.122,17.216,0.000,8.447,0.000,2.750,...,-0.306,0.306,1.627,-20.773,19.452,0.000,-2.881,0.000,0.151593,1
67,TTO,0.116,99.884,0.000,16.920,82.964,0.000,0.766,0.000,0.005,...,-0.111,0.111,0.000,-5.740,5.851,0.000,-0.766,0.000,0.100529,0
68,TUR,14.165,85.835,27.330,49.262,9.242,0.000,41.570,0.000,11.710,...,-2.455,2.455,2.059,-19.155,19.551,0.000,-15.185,0.000,0.392340,1
69,TKM,0.011,99.989,0.056,27.121,72.813,0.000,0.040,0.000,0.003,...,-0.008,0.008,-0.056,-1.170,1.233,0.000,-0.040,0.000,0.312606,1
70,UKR,1.500,87.876,32.169,16.586,39.120,10.625,5.091,36.079,2.464,...,0.964,-6.697,-0.827,-5.190,-0.680,5.732,2.000,11.135,-0.094177,0
71,ARE,0.000,100.000,0.000,50.151,49.849,0.000,0.000,0.000,0.005,...,0.005,-0.005,0.787,-11.891,11.099,0.000,0.021,0.000,0.376888,1
72,GBR,0.752,89.543,21.676,38.879,28.988,9.705,1.980,26.365,3.043,...,2.291,0.858,-7.301,-2.757,10.916,-3.149,4.872,-10.101,0.107496,0
73,USA,4.551,87.328,23.069,39.595,24.664,8.121,10.602,19.870,5.642,...,1.091,-1.529,-0.626,-1.318,0.415,0.438,-0.284,-0.254,0.111423,0
74,UZB,3.398,96.602,2.051,15.314,79.237,0.000,13.040,0.000,4.069,...,0.671,-0.671,-0.290,-5.156,4.775,0.000,2.719,0.000,0.403891,1
75,VEN,19.900,80.100,0.008,37.587,42.505,0.000,70.051,0.000,21.151,...,1.251,-1.251,0.238,7.890,-9.379,0.000,-2.558,0.000,0.015460,0
76,VNM,23.467,76.533,28.752,46.659,1.121,0.000,72.242,0.000,13.931,...,-9.536,9.536,2.866,-9.156,15.827,0.000,-41.038,0.000,0.343649,1

In [17]:
X=model_data[["renewables_share_energy_change","fossil_share_energy_change","coal_share_energy_change","oil_share_energy_change","gas_share_energy_change","nuclear_share_energy_change","renewables_share_elec_change","nuclear_share_elec_change"]]  #Predictor 
Y=model_data["high_growth"] #Response 

print(X.shape) 
print(Y.shape)

(77, 8)
(77,)

In [36]:
# define predictors and response
predictors = [
    "renewables_share_energy_change",
    "coal_share_energy_change",
    "nuclear_share_energy_change",
    "renewables_share_elec_change",
]
response = "high_growth"

X = model_data[predictors].copy()
y = model_data[response].copy()

print("Rows available:", X.shape[0])
print("Class balance:\n", y.value_counts(normalize=True))

# train/test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# scaling for Logistic Regression
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled  = scaler.transform(X_test)

# definition of the three models
models = {
    "Logistic Regression": LogisticRegression(max_iter=1000, random_state=42),
    "Decision Tree":       DecisionTreeClassifier(max_depth=4, random_state=42),
    "Gradient Boosting":   GradientBoostingClassifier(n_estimators=100, max_depth=3, random_state=42),
}

results = []
fitted_models = {}

for name, model in models.items():
    if name == "Logistic Regression":
        model.fit(X_train_scaled, y_train)
        preds = model.predict(X_test_scaled)
    else:
        model.fit(X_train, y_train)
        preds = model.predict(X_test)

    fitted_models[name] = model
    results.append({
        "Model": name,
        "Accuracy": accuracy_score(y_test, preds),
        "Precision": precision_score(y_test, preds),
        "Recall": recall_score(y_test, preds),
        "F1": f1_score(y_test, preds),
    })

results_df = pd.DataFrame(results).set_index("Model").round(3)
print(results_df)
results_df.to_csv("model_comparison_results.csv")

# confusion matrices for all three models
fig, axes = plt.subplots(1, 3, figsize=(15, 4))
for ax, (name, model) in zip(axes, fitted_models.items()):
    Xt = X_test_scaled if name == "Logistic Regression" else X_test
    preds = model.predict(Xt)
    cm = confusion_matrix(y_test, preds)
    ConfusionMatrixDisplay(cm, display_labels=["Low growth", "High growth"]).plot(ax=ax, colorbar=False)
    ax.set_title(name)
plt.tight_layout()
plt.savefig("confusion_matrices.png", dpi=150)
plt.close()

# interpretability extras 
coef_df = pd.DataFrame({
    "feature": predictors,
    "coefficient": fitted_models["Logistic Regression"].coef_[0]
}).sort_values("coefficient", key=abs, ascending=False)
print("\nLogistic Regression coefficients:\n", coef_df)

importance_df = pd.DataFrame({
    "feature": predictors,
    "importance": fitted_models["Decision Tree"].feature_importances_
}).sort_values("importance", ascending=False)
print("\nDecision Tree feature importances:\n", importance_df)

plt.figure(figsize=(16, 8))
plot_tree(fitted_models["Decision Tree"], feature_names=predictors,
          class_names=["Low growth", "High growth"], filled=True, fontsize=8)
plt.savefig("decision_tree.png", dpi=150, bbox_inches="tight")
plt.close()

gb_importance_df = pd.DataFrame({
    "feature": predictors,
    "importance": fitted_models["Gradient Boosting"].feature_importances_
}).sort_values("importance", ascending=False)
print("\nGradient Boosting feature importances:\n", gb_importance_df)

Rows available: 77
Class balance:
 high_growth
0    0.506494
1    0.493506
Name: proportion, dtype: float64
                     Accuracy  Precision  Recall     F1
Model
Logistic Regression     0.688      0.667   0.750  0.706
Decision Tree           0.750      0.833   0.625  0.714
Gradient Boosting       0.750      0.750   0.750  0.750

Logistic Regression coefficients:
                           feature  coefficient
0  renewables_share_energy_change    -1.083611
2     nuclear_share_energy_change    -0.450794
3    renewables_share_elec_change    -0.447768
1        coal_share_energy_change     0.376614

Decision Tree feature importances:
                           feature  importance
0  renewables_share_energy_change    0.447118
1        coal_share_energy_change    0.319390
2     nuclear_share_energy_change    0.151954
3    renewables_share_elec_change    0.081538

Gradient Boosting feature importances:
                           feature  importance
3    renewables_share_elec_change    0.264493
0  renewables_share_energy_change    0.264056
1        coal_share_energy_change    0.240112
2     nuclear_share_energy_change    0.231339

In [37]:
# sanity checks: train-vs-test accuracy and cross-validation
print("Train vs Test accuracy (checking overfitting):")
for name, model in fitted_models.items():
    Xtr = X_train_scaled if name == "Logistic Regression" else X_train
    Xte = X_test_scaled if name == "Logistic Regression" else X_test
    train_acc = model.score(Xtr, y_train)
    test_acc = model.score(Xte, y_test)
    print(f"{name:20s} train={train_acc:.3f}  test={test_acc:.3f}")

print("\n5-fold Cross-Validation accuracy (more reliable than single split):")
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
for name, model in models.items():
    Xcv = scaler.fit_transform(X) if name == "Logistic Regression" else X
    scores = cross_val_score(model, Xcv, y, cv=cv, scoring="accuracy")
    print(f"{name:20s} mean={scores.mean():.3f}  std={scores.std():.3f}  folds={np.round(scores,2)}")

print("\nFeature correlation matrix:")
print(X.corr().round(2))

Train vs Test accuracy (checking overfitting):
Logistic Regression  train=0.770  test=0.688
Decision Tree        train=0.885  test=0.750
Gradient Boosting    train=1.000  test=0.750

5-fold Cross-Validation accuracy (more reliable than single split):
Logistic Regression  mean=0.714  std=0.135  folds=[0.62 0.81 0.93 0.6  0.6 ]
Decision Tree        mean=0.675  std=0.116  folds=[0.56 0.81 0.67 0.53 0.8 ]
Gradient Boosting    mean=0.662  std=0.094  folds=[0.56 0.75 0.73 0.53 0.73]

Feature correlation matrix:
                                renewables_share_energy_change  \
renewables_share_energy_change                            1.00
coal_share_energy_change                                 -0.39
nuclear_share_energy_change                              -0.06
renewables_share_elec_change                              0.73

                                coal_share_energy_change  \
renewables_share_energy_change                     -0.39
coal_share_energy_change                            1.00
nuclear_share_energy_change                        -0.05
renewables_share_elec_change                       -0.35

                                nuclear_share_energy_change  \
renewables_share_energy_change                        -0.06
coal_share_energy_change                              -0.05
nuclear_share_energy_change                            1.00
renewables_share_elec_change                          -0.15

                                renewables_share_elec_change
renewables_share_energy_change                          0.73
coal_share_energy_change                               -0.35
nuclear_share_energy_change                            -0.15
renewables_share_elec_change                            1.00

In [38]:
# correlation heatmap
plt.figure(figsize=(9, 7))
corr_matrix = X.corr()
sns.heatmap(corr_matrix, annot=True, fmt=".2f", cmap="coolwarm",
            vmin=-1, vmax=1, square=True, cbar_kws={"label": "Correlation"})
plt.title("Predictor Correlation Matrix")
plt.tight_layout()
plt.savefig("correlation_heatmap.png", dpi=150)
plt.close()

# flag highly correlated pairs (|r| > 0.7)
pairs = []
for i in range(len(corr_matrix.columns)):
    for j in range(i+1, len(corr_matrix.columns)):
        r = corr_matrix.iloc[i, j]
        if abs(r) > 0.7:
            pairs.append((corr_matrix.columns[i], corr_matrix.columns[j], round(r, 3)))

pairs_df = pd.DataFrame(pairs, columns=["Feature 1", "Feature 2", "Correlation"])
pairs_df = pairs_df.sort_values("Correlation", key=abs, ascending=False)
print("Highly correlated feature pairs (|r| > 0.7):")
print(pairs_df)

# variance Inflation Factor (VIF) — the proper multicollinearity metric
# VIF = 1        -> no correlation with other predictors
# VIF 1-5        -> moderate correlation, usually fine
# VIF > 5-10     -> problematic multicollinearity, consider dropping the feature
X_vif = add_constant(X)
vif_data = pd.DataFrame({
    "feature": X_vif.columns,
    "VIF": [variance_inflation_factor(X_vif.values, i) for i in range(X_vif.shape[1])]
})
vif_data = vif_data[vif_data["feature"] != "const"].sort_values("VIF", ascending=False)
print("\nVariance Inflation Factor (VIF) per feature:")
print(vif_data.to_string(index=False))

vif_data.to_csv("vif_results.csv", index=False)
pairs_df.to_csv("high_correlation_pairs.csv", index=False)

# suggested features to drop (VIF > 5), keeping the more interpretable/original one
high_vif = vif_data[vif_data["VIF"] > 5]["feature"].tolist()
print("\nFeatures with VIF > 5 (candidates to drop):", high_vif)

Highly correlated feature pairs (|r| > 0.7):
                        Feature 1                     Feature 2  Correlation
0  renewables_share_energy_change  renewables_share_elec_change        0.729

Variance Inflation Factor (VIF) per feature:
                       feature      VIF
renewables_share_energy_change 2.229218
  renewables_share_elec_change 2.226697
      coal_share_energy_change 1.202744
   nuclear_share_energy_change 1.040473

Features with VIF > 5 (candidates to drop): []

In [28]:
"""
Highly correlated feature pairs (|r| > 0.7):
                        Feature 1                     Feature 2  Correlation
3     nuclear_share_energy_change     nuclear_share_elec_change        0.981
0  renewables_share_energy_change    fossil_share_energy_change       -0.733
1  renewables_share_energy_change  renewables_share_elec_change        0.729
2         oil_share_energy_change       gas_share_energy_change       -0.713

Variance Inflation Factor (VIF) per feature:
                       feature          VIF
    fossil_share_energy_change 2.133545e+08
       oil_share_energy_change 1.547654e+08
renewables_share_energy_change 1.352273e+08
       gas_share_energy_change 1.205493e+08
   nuclear_share_energy_change 1.045690e+08
      coal_share_energy_change 6.322501e+07
     nuclear_share_elec_change 3.013404e+01
  renewables_share_elec_change 2.380418e+00

Features with VIF > 5 (candidates to drop): ['fossil_share_energy_change', 'oil_share_energy_change', 'renewables_share_energy_change', 'gas_share_energy_change', 'nuclear_share_energy_change', 'coal_share_energy_change', 'nuclear_share_elec_change']
"""
# after removal of the multicollinear features
"""
Highly correlated feature pairs (|r| > 0.7):
                        Feature 1                     Feature 2  Correlation
0  renewables_share_energy_change  renewables_share_elec_change        0.729

Variance Inflation Factor (VIF) per feature:
                       feature      VIF
renewables_share_energy_change 2.229218
  renewables_share_elec_change 2.226697
      coal_share_energy_change 1.202744
   nuclear_share_energy_change 1.040473

Features with VIF > 5 (candidates to drop): []


"""

SyntaxError: incomplete input (3951088659.py, line 1)

In [39]:
# regularization to reduce overfitting in tree-based models
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

regularized_models = {
    "Logistic Regression (C=0.5)": LogisticRegression(C=0.5, max_iter=1000, random_state=42),
    "Decision Tree (depth=2, leaf=8)": DecisionTreeClassifier(max_depth=2, min_samples_leaf=8, random_state=42),
    "Gradient Boosting (depth=2, n=50, leaf=8)": GradientBoostingClassifier(
        n_estimators=50, max_depth=2, min_samples_leaf=8, learning_rate=0.05, random_state=42),
}

print("Regularized models — 5-fold CV accuracy:")
for name, model in regularized_models.items():
    Xcv = scaler.fit_transform(X) if "Logistic" in name else X
    scores = cross_val_score(model, Xcv, y, cv=cv, scoring="accuracy")
    print(f"{name:40s} mean={scores.mean():.3f}  std={scores.std():.3f}")

print("\nTrain vs CV gap check (refit on full train/test split):")
for name, model in regularized_models.items():
    Xtr = X_train_scaled if "Logistic" in name else X_train
    model.fit(Xtr, y_train)
    train_acc = model.score(Xtr, y_train)
    Xcv = scaler.fit_transform(X) if "Logistic" in name else X
    cv_acc = cross_val_score(model, Xcv, y, cv=cv, scoring="accuracy").mean()
    print(f"{name:40s} train={train_acc:.3f}  cv={cv_acc:.3f}  gap={train_acc-cv_acc:.3f}")

Regularized models — 5-fold CV accuracy:
Logistic Regression (C=0.5)              mean=0.728  std=0.127
Decision Tree (depth=2, leaf=8)          mean=0.713  std=0.055
Gradient Boosting (depth=2, n=50, leaf=8) mean=0.715  std=0.062

Train vs CV gap check (refit on full train/test split):
Logistic Regression (C=0.5)              train=0.787  cv=0.728  gap=0.059
Decision Tree (depth=2, leaf=8)          train=0.787  cv=0.713  gap=0.074
Gradient Boosting (depth=2, n=50, leaf=8) train=0.902  cv=0.715  gap=0.187